// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer24_out_dout,
        layer24_out_num_data_valid,
        layer24_out_fifo_cap,
        layer24_out_empty_n,
        layer24_out_read,
        layer19_out_TDATA,
        layer19_out_TVALID,
        layer19_out_TREADY
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [159:0] layer24_out_dout;
input  [1:0] layer24_out_num_data_valid;
input  [1:0] layer24_out_fifo_cap;
input   layer24_out_empty_n;
output   layer24_out_read;
output  [159:0] layer19_out_TDATA;
output   layer19_out_TVALID;
input   layer19_out_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg layer24_out_read;
reg layer19_out_TVALID;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [9:0] exp_table_address0;
reg    exp_table_ce0;
wire   [10:0] exp_table_q0;
wire   [9:0] exp_table_address1;
reg    exp_table_ce1;
wire   [10:0] exp_table_q1;
wire   [9:0] exp_table_address2;
reg    exp_table_ce2;
wire   [10:0] exp_table_q2;
wire   [9:0] exp_table_address3;
reg    exp_table_ce3;
wire   [10:0] exp_table_q3;
wire   [9:0] exp_table_address4;
reg    exp_table_ce4;
wire   [10:0] exp_table_q4;
wire   [9:0] exp_table_address5;
reg    exp_table_ce5;
wire   [10:0] exp_table_q5;
wire   [9:0] exp_table_address6;
reg    exp_table_ce6;
wire   [10:0] exp_table_q6;
wire   [9:0] exp_table_address7;
reg    exp_table_ce7;
wire   [10:0] exp_table_q7;
wire   [9:0] exp_table_address8;
reg    exp_table_ce8;
wire   [10:0] exp_table_q8;
wire   [9:0] exp_table_address9;
reg    exp_table_ce9;
wire   [10:0] exp_table_q9;
wire   [9:0] invert_table_address0;
reg    invert_table_ce0;
wire   [17:0] invert_table_q0;
reg    layer24_out_blk_n;
reg    layer19_out_TDATA_blk_n;
wire    ap_CS_fsm_state7;
reg   [15:0] data_array_8_reg_1561;
reg   [15:0] data_array_9_reg_1567;
wire   [15:0] select_ln66_fu_758_p3;
reg   [15:0] select_ln66_reg_1573;
wire   [15:0] select_ln66_1_fu_778_p3;
reg   [15:0] select_ln66_1_reg_1579;
wire   [15:0] select_ln66_3_fu_798_p3;
reg   [15:0] select_ln66_3_reg_1585;
wire   [15:0] select_ln66_4_fu_818_p3;
reg   [15:0] select_ln66_4_reg_1591;
wire   [14:0] trunc_ln213_fu_826_p1;
reg   [14:0] trunc_ln213_reg_1597;
reg   [14:0] trunc_ln213_2_reg_1602;
reg   [14:0] trunc_ln213_3_reg_1607;
reg   [14:0] trunc_ln213_4_reg_1612;
reg   [14:0] trunc_ln213_5_reg_1617;
reg   [14:0] trunc_ln213_6_reg_1622;
reg   [14:0] trunc_ln213_7_reg_1627;
reg   [14:0] trunc_ln213_8_reg_1632;
reg   [14:0] trunc_ln213_9_reg_1637;
reg   [14:0] trunc_ln213_s_reg_1642;
wire   [14:0] select_ln66_8_fu_1008_p3;
reg   [14:0] select_ln66_8_reg_1647;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg   [10:0] exp_res_reg_1711;
wire    ap_CS_fsm_state4;
reg   [10:0] exp_res_1_reg_1716;
reg   [10:0] exp_res_2_reg_1721;
reg   [10:0] exp_res_3_reg_1726;
reg   [10:0] exp_res_4_reg_1731;
reg   [10:0] exp_res_5_reg_1736;
reg   [10:0] exp_res_6_reg_1741;
reg   [10:0] exp_res_7_reg_1746;
reg   [10:0] exp_res_8_reg_1751;
reg   [10:0] exp_res_9_reg_1757;
wire   [12:0] add_ln51_5_fu_1242_p2;
reg   [12:0] add_ln51_5_reg_1763;
wire   [12:0] add_ln51_8_fu_1284_p2;
reg   [12:0] add_ln51_8_reg_1768;
wire    ap_CS_fsm_state5;
reg   [17:0] inv_exp_sum_reg_1778;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln223_fu_1066_p1;
wire   [63:0] zext_ln223_1_fu_1081_p1;
wire   [63:0] zext_ln223_2_fu_1096_p1;
wire   [63:0] zext_ln223_3_fu_1111_p1;
wire   [63:0] zext_ln223_4_fu_1126_p1;
wire   [63:0] zext_ln223_5_fu_1141_p1;
wire   [63:0] zext_ln223_6_fu_1156_p1;
wire   [63:0] zext_ln223_7_fu_1171_p1;
wire   [63:0] zext_ln223_8_fu_1186_p1;
wire   [63:0] zext_ln223_9_fu_1201_p1;
wire   [63:0] zext_ln232_fu_1338_p1;
reg    ap_block_state1;
wire  signed [17:0] mul_ln241_fu_281_p0;
wire  signed [28:0] sext_ln238_fu_1343_p1;
wire   [10:0] mul_ln241_fu_281_p1;
wire  signed [17:0] mul_ln241_2_fu_282_p0;
wire   [10:0] mul_ln241_2_fu_282_p1;
wire  signed [17:0] mul_ln241_4_fu_283_p0;
wire   [10:0] mul_ln241_4_fu_283_p1;
wire  signed [17:0] mul_ln241_6_fu_284_p0;
wire   [10:0] mul_ln241_6_fu_284_p1;
wire  signed [17:0] mul_ln241_3_fu_285_p0;
wire   [10:0] mul_ln241_3_fu_285_p1;
wire  signed [17:0] mul_ln241_7_fu_286_p0;
wire   [10:0] mul_ln241_7_fu_286_p1;
wire  signed [17:0] mul_ln241_5_fu_287_p0;
wire   [10:0] mul_ln241_5_fu_287_p1;
wire  signed [17:0] mul_ln241_1_fu_288_p0;
wire   [10:0] mul_ln241_1_fu_288_p1;
wire  signed [17:0] mul_ln241_8_fu_289_p0;
wire   [10:0] mul_ln241_8_fu_289_p1;
wire  signed [17:0] mul_ln241_9_fu_290_p0;
wire   [10:0] mul_ln241_9_fu_290_p1;
wire   [15:0] data_array_fu_652_p1;
wire   [15:0] data_array_1_fu_676_p4;
wire   [0:0] icmp_ln66_fu_746_p2;
wire   [0:0] xor_ln66_fu_752_p2;
wire   [15:0] data_array_2_fu_686_p4;
wire   [15:0] data_array_3_fu_696_p4;
wire   [0:0] icmp_ln66_1_fu_766_p2;
wire   [0:0] xor_ln66_1_fu_772_p2;
wire   [15:0] data_array_4_fu_706_p4;
wire   [15:0] data_array_5_fu_716_p4;
wire   [0:0] icmp_ln66_3_fu_786_p2;
wire   [0:0] xor_ln66_3_fu_792_p2;
wire   [15:0] data_array_6_fu_726_p4;
wire   [15:0] data_array_7_fu_736_p4;
wire   [0:0] icmp_ln66_4_fu_806_p2;
wire   [0:0] xor_ln66_4_fu_812_p2;
wire   [0:0] icmp_ln66_2_fu_920_p2;
wire   [0:0] xor_ln66_2_fu_924_p2;
wire   [0:0] icmp_ln66_5_fu_936_p2;
wire   [0:0] xor_ln66_5_fu_940_p2;
wire   [15:0] select_ln66_2_fu_930_p3;
wire   [15:0] select_ln66_5_fu_946_p3;
wire   [0:0] icmp_ln66_6_fu_952_p2;
wire   [0:0] xor_ln66_6_fu_958_p2;
wire   [0:0] icmp_ln66_7_fu_972_p2;
wire   [0:0] xor_ln66_7_fu_976_p2;
wire   [15:0] select_ln66_6_fu_964_p3;
wire   [15:0] select_ln66_7_fu_982_p3;
wire   [0:0] icmp_ln66_8_fu_988_p2;
wire   [0:0] xor_ln66_8_fu_994_p2;
wire   [14:0] trunc_ln66_fu_1000_p1;
wire   [14:0] trunc_ln66_1_fu_1004_p1;
wire   [14:0] d_xi_xmax_fu_1016_p2;
wire   [9:0] tmp_fu_1056_p4;
wire   [14:0] d_xi_xmax_10_fu_1020_p2;
wire   [9:0] tmp_s_fu_1071_p4;
wire   [14:0] d_xi_xmax_11_fu_1024_p2;
wire   [9:0] tmp_1_fu_1086_p4;
wire   [14:0] d_xi_xmax_12_fu_1028_p2;
wire   [9:0] tmp_2_fu_1101_p4;
wire   [14:0] d_xi_xmax_13_fu_1032_p2;
wire   [9:0] tmp_3_fu_1116_p4;
wire   [14:0] d_xi_xmax_14_fu_1036_p2;
wire   [9:0] tmp_4_fu_1131_p4;
wire   [14:0] d_xi_xmax_15_fu_1040_p2;
wire   [9:0] tmp_5_fu_1146_p4;
wire   [14:0] d_xi_xmax_16_fu_1044_p2;
wire   [9:0] tmp_6_fu_1161_p4;
wire   [14:0] d_xi_xmax_17_fu_1048_p2;
wire   [9:0] tmp_7_fu_1176_p4;
wire   [14:0] d_xi_xmax_18_fu_1052_p2;
wire   [9:0] tmp_8_fu_1191_p4;
wire   [11:0] zext_ln51_1_fu_1210_p1;
wire   [11:0] zext_ln51_fu_1206_p1;
wire   [11:0] add_ln51_fu_1214_p2;
wire   [11:0] zext_ln51_4_fu_1228_p1;
wire   [11:0] zext_ln51_3_fu_1224_p1;
wire   [11:0] add_ln51_3_fu_1232_p2;
wire   [12:0] zext_ln51_5_fu_1238_p1;
wire   [12:0] zext_ln51_2_fu_1220_p1;
wire   [11:0] zext_ln51_7_fu_1252_p1;
wire   [11:0] zext_ln51_6_fu_1248_p1;
wire   [11:0] add_ln51_6_fu_1256_p2;
wire   [11:0] zext_ln51_10_fu_1270_p1;
wire   [11:0] zext_ln51_9_fu_1266_p1;
wire   [11:0] add_ln51_7_fu_1274_p2;
wire   [12:0] zext_ln51_11_fu_1280_p1;
wire   [12:0] zext_ln51_8_fu_1262_p1;
wire   [13:0] add_ln51_i_cast_fu_1296_p1;
wire   [13:0] zext_ln51_12_fu_1299_p1;
wire   [13:0] add_ln51_1_fu_1302_p2;
wire   [11:0] exp_res_9_cast_fu_1293_p1;
wire   [11:0] exp_res_8_cast_fu_1290_p1;
wire   [11:0] add_ln51_2_fu_1312_p2;
wire   [14:0] zext_ln51_13_fu_1308_p1;
wire   [14:0] zext_ln51_14_fu_1318_p1;
wire   [14:0] add_ln51_4_fu_1322_p2;
wire   [6:0] tmp_9_fu_1328_p4;
wire   [28:0] mul_ln241_fu_281_p2;
wire   [14:0] trunc_ln1_fu_1360_p4;
wire   [28:0] mul_ln241_1_fu_288_p2;
wire   [14:0] trunc_ln241_1_fu_1378_p4;
wire   [28:0] mul_ln241_2_fu_282_p2;
wire   [14:0] trunc_ln241_2_fu_1396_p4;
wire   [28:0] mul_ln241_3_fu_285_p2;
wire   [14:0] trunc_ln241_3_fu_1414_p4;
wire   [28:0] mul_ln241_4_fu_283_p2;
wire   [14:0] trunc_ln241_4_fu_1432_p4;
wire   [28:0] mul_ln241_5_fu_287_p2;
wire   [14:0] trunc_ln241_5_fu_1450_p4;
wire   [28:0] mul_ln241_6_fu_284_p2;
wire   [14:0] trunc_ln241_6_fu_1468_p4;
wire   [28:0] mul_ln241_7_fu_286_p2;
wire   [14:0] trunc_ln241_7_fu_1486_p4;
wire   [28:0] mul_ln241_8_fu_289_p2;
wire   [14:0] trunc_ln241_8_fu_1504_p4;
wire   [28:0] mul_ln241_9_fu_290_p2;
wire   [14:0] trunc_ln241_9_fu_1522_p4;
wire  signed [15:0] sext_ln241_8_fu_1514_p1;
wire  signed [15:0] sext_ln241_7_fu_1496_p1;
wire  signed [15:0] sext_ln241_6_fu_1478_p1;
wire  signed [15:0] sext_ln241_5_fu_1460_p1;
wire  signed [15:0] sext_ln241_4_fu_1442_p1;
wire  signed [15:0] sext_ln241_3_fu_1424_p1;
wire  signed [15:0] sext_ln241_2_fu_1406_p1;
wire  signed [15:0] sext_ln241_1_fu_1388_p1;
wire  signed [15:0] sext_ln241_fu_1370_p1;
wire   [158:0] tmp_10_fu_1532_p11;
wire    ap_CS_fsm_state8;
reg   [7:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire   [28:0] mul_ln241_1_fu_288_p10;
wire   [28:0] mul_ln241_2_fu_282_p10;
wire   [28:0] mul_ln241_3_fu_285_p10;
wire   [28:0] mul_ln241_4_fu_283_p10;
wire   [28:0] mul_ln241_5_fu_287_p10;
wire   [28:0] mul_ln241_6_fu_284_p10;
wire   [28:0] mul_ln241_7_fu_286_p10;
wire   [28:0] mul_ln241_8_fu_289_p10;
wire   [28:0] mul_ln241_9_fu_290_p10;
wire   [28:0] mul_ln241_fu_281_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
end

myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_s_exp_tab1iI #(
    .DataWidth( 11 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
exp_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(exp_table_address0),
    .ce0(exp_table_ce0),
    .q0(exp_table_q0),
    .address1(exp_table_address1),
    .ce1(exp_table_ce1),
    .q1(exp_table_q1),
    .address2(exp_table_address2),
    .ce2(exp_table_ce2),
    .q2(exp_table_q2),
    .address3(exp_table_address3),
    .ce3(exp_table_ce3),
    .q3(exp_table_q3),
    .address4(exp_table_address4),
    .ce4(exp_table_ce4),
    .q4(exp_table_q4),
    .address5(exp_table_address5),
    .ce5(exp_table_ce5),
    .q5(exp_table_q5),
    .address6(exp_table_address6),
    .ce6(exp_table_ce6),
    .q6(exp_table_q6),
    .address7(exp_table_address7),
    .ce7(exp_table_ce7),
    .q7(exp_table_q7),
    .address8(exp_table_address8),
    .ce8(exp_table_ce8),
    .q8(exp_table_q8),
    .address9(exp_table_address9),
    .ce9(exp_table_ce9),
    .q9(exp_table_q9)
);

myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_s_invert_2iS #(
    .DataWidth( 18 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
invert_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(invert_table_address0),
    .ce0(invert_table_ce0),
    .q0(invert_table_q0)
);

myproject_mul_18s_11ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 29 ))
mul_18s_11ns_29_1_1_U2664(
    .din0(mul_ln241_fu_281_p0),
    .din1(mul_ln241_fu_281_p1),
    .dout(mul_ln241_fu_281_p2)
);

myproject_mul_18s_11ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 29 ))
mul_18s_11ns_29_1_1_U2665(
    .din0(mul_ln241_2_fu_282_p0),
    .din1(mul_ln241_2_fu_282_p1),
    .dout(mul_ln241_2_fu_282_p2)
);

myproject_mul_18s_11ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 29 ))
mul_18s_11ns_29_1_1_U2666(
    .din0(mul_ln241_4_fu_283_p0),
    .din1(mul_ln241_4_fu_283_p1),
    .dout(mul_ln241_4_fu_283_p2)
);

myproject_mul_18s_11ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 29 ))
mul_18s_11ns_29_1_1_U2667(
    .din0(mul_ln241_6_fu_284_p0),
    .din1(mul_ln241_6_fu_284_p1),
    .dout(mul_ln241_6_fu_284_p2)
);

myproject_mul_18s_11ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 29 ))
mul_18s_11ns_29_1_1_U2668(
    .din0(mul_ln241_3_fu_285_p0),
    .din1(mul_ln241_3_fu_285_p1),
    .dout(mul_ln241_3_fu_285_p2)
);

myproject_mul_18s_11ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 29 ))
mul_18s_11ns_29_1_1_U2669(
    .din0(mul_ln241_7_fu_286_p0),
    .din1(mul_ln241_7_fu_286_p1),
    .dout(mul_ln241_7_fu_286_p2)
);

myproject_mul_18s_11ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 29 ))
mul_18s_11ns_29_1_1_U2670(
    .din0(mul_ln241_5_fu_287_p0),
    .din1(mul_ln241_5_fu_287_p1),
    .dout(mul_ln241_5_fu_287_p2)
);

myproject_mul_18s_11ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 29 ))
mul_18s_11ns_29_1_1_U2671(
    .din0(mul_ln241_1_fu_288_p0),
    .din1(mul_ln241_1_fu_288_p1),
    .dout(mul_ln241_1_fu_288_p2)
);

myproject_mul_18s_11ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 29 ))
mul_18s_11ns_29_1_1_U2672(
    .din0(mul_ln241_8_fu_289_p0),
    .din1(mul_ln241_8_fu_289_p1),
    .dout(mul_ln241_8_fu_289_p2)
);

myproject_mul_18s_11ns_29_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 29 ))
mul_18s_11ns_29_1_1_U2673(
    .din0(mul_ln241_9_fu_290_p0),
    .din1(mul_ln241_9_fu_290_p1),
    .dout(mul_ln241_9_fu_290_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln51_5_reg_1763 <= add_ln51_5_fu_1242_p2;
        add_ln51_8_reg_1768 <= add_ln51_8_fu_1284_p2;
        exp_res_1_reg_1716 <= exp_table_q8;
        exp_res_2_reg_1721 <= exp_table_q7;
        exp_res_3_reg_1726 <= exp_table_q6;
        exp_res_4_reg_1731 <= exp_table_q5;
        exp_res_5_reg_1736 <= exp_table_q4;
        exp_res_6_reg_1741 <= exp_table_q3;
        exp_res_7_reg_1746 <= exp_table_q2;
        exp_res_8_reg_1751 <= exp_table_q1;
        exp_res_9_reg_1757 <= exp_table_q0;
        exp_res_reg_1711 <= exp_table_q9;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        data_array_8_reg_1561 <= {{layer24_out_dout[143:128]}};
        data_array_9_reg_1567 <= {{layer24_out_dout[159:144]}};
        select_ln66_1_reg_1579 <= select_ln66_1_fu_778_p3;
        select_ln66_3_reg_1585 <= select_ln66_3_fu_798_p3;
        select_ln66_4_reg_1591 <= select_ln66_4_fu_818_p3;
        select_ln66_reg_1573 <= select_ln66_fu_758_p3;
        trunc_ln213_2_reg_1602 <= {{layer24_out_dout[30:16]}};
        trunc_ln213_3_reg_1607 <= {{layer24_out_dout[46:32]}};
        trunc_ln213_4_reg_1612 <= {{layer24_out_dout[62:48]}};
        trunc_ln213_5_reg_1617 <= {{layer24_out_dout[78:64]}};
        trunc_ln213_6_reg_1622 <= {{layer24_out_dout[94:80]}};
        trunc_ln213_7_reg_1627 <= {{layer24_out_dout[110:96]}};
        trunc_ln213_8_reg_1632 <= {{layer24_out_dout[126:112]}};
        trunc_ln213_9_reg_1637 <= {{layer24_out_dout[142:128]}};
        trunc_ln213_reg_1597 <= trunc_ln213_fu_826_p1;
        trunc_ln213_s_reg_1642 <= {{layer24_out_dout[158:144]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        inv_exp_sum_reg_1778 <= invert_table_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        select_ln66_8_reg_1647 <= select_ln66_8_fu_1008_p3;
    end
end

always @ (*) begin
    if (((layer24_out_empty_n == 1'b0) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((layer19_out_TREADY == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce0 = 1'b1;
    end else begin
        exp_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce1 = 1'b1;
    end else begin
        exp_table_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce2 = 1'b1;
    end else begin
        exp_table_ce2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce3 = 1'b1;
    end else begin
        exp_table_ce3 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce4 = 1'b1;
    end else begin
        exp_table_ce4 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce5 = 1'b1;
    end else begin
        exp_table_ce5 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce6 = 1'b1;
    end else begin
        exp_table_ce6 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce7 = 1'b1;
    end else begin
        exp_table_ce7 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce8 = 1'b1;
    end else begin
        exp_table_ce8 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        exp_table_ce9 = 1'b1;
    end else begin
        exp_table_ce9 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        invert_table_ce0 = 1'b1;
    end else begin
        invert_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        layer19_out_TDATA_blk_n = layer19_out_TREADY;
    end else begin
        layer19_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer19_out_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        layer19_out_TVALID = 1'b1;
    end else begin
        layer19_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        layer24_out_blk_n = layer24_out_empty_n;
    end else begin
        layer24_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((layer24_out_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer24_out_read = 1'b1;
    end else begin
        layer24_out_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((layer24_out_empty_n == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((layer19_out_TREADY == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln51_1_fu_1302_p2 = (add_ln51_i_cast_fu_1296_p1 + zext_ln51_12_fu_1299_p1);

assign add_ln51_2_fu_1312_p2 = (exp_res_9_cast_fu_1293_p1 + exp_res_8_cast_fu_1290_p1);

assign add_ln51_3_fu_1232_p2 = (zext_ln51_4_fu_1228_p1 + zext_ln51_3_fu_1224_p1);

assign add_ln51_4_fu_1322_p2 = (zext_ln51_13_fu_1308_p1 + zext_ln51_14_fu_1318_p1);

assign add_ln51_5_fu_1242_p2 = (zext_ln51_5_fu_1238_p1 + zext_ln51_2_fu_1220_p1);

assign add_ln51_6_fu_1256_p2 = (zext_ln51_7_fu_1252_p1 + zext_ln51_6_fu_1248_p1);

assign add_ln51_7_fu_1274_p2 = (zext_ln51_10_fu_1270_p1 + zext_ln51_9_fu_1266_p1);

assign add_ln51_8_fu_1284_p2 = (zext_ln51_11_fu_1280_p1 + zext_ln51_8_fu_1262_p1);

assign add_ln51_fu_1214_p2 = (zext_ln51_1_fu_1210_p1 + zext_ln51_fu_1206_p1);

assign add_ln51_i_cast_fu_1296_p1 = add_ln51_5_reg_1763;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_block_state1 = ((layer24_out_empty_n == 1'b0) | (ap_start == 1'b0));
end

assign d_xi_xmax_10_fu_1020_p2 = (select_ln66_8_reg_1647 - trunc_ln213_2_reg_1602);

assign d_xi_xmax_11_fu_1024_p2 = (select_ln66_8_reg_1647 - trunc_ln213_3_reg_1607);

assign d_xi_xmax_12_fu_1028_p2 = (select_ln66_8_reg_1647 - trunc_ln213_4_reg_1612);

assign d_xi_xmax_13_fu_1032_p2 = (select_ln66_8_reg_1647 - trunc_ln213_5_reg_1617);

assign d_xi_xmax_14_fu_1036_p2 = (select_ln66_8_reg_1647 - trunc_ln213_6_reg_1622);

assign d_xi_xmax_15_fu_1040_p2 = (select_ln66_8_reg_1647 - trunc_ln213_7_reg_1627);

assign d_xi_xmax_16_fu_1044_p2 = (select_ln66_8_reg_1647 - trunc_ln213_8_reg_1632);

assign d_xi_xmax_17_fu_1048_p2 = (select_ln66_8_reg_1647 - trunc_ln213_9_reg_1637);

assign d_xi_xmax_18_fu_1052_p2 = (select_ln66_8_reg_1647 - trunc_ln213_s_reg_1642);

assign d_xi_xmax_fu_1016_p2 = (select_ln66_8_reg_1647 - trunc_ln213_reg_1597);

assign data_array_1_fu_676_p4 = {{layer24_out_dout[31:16]}};

assign data_array_2_fu_686_p4 = {{layer24_out_dout[47:32]}};

assign data_array_3_fu_696_p4 = {{layer24_out_dout[63:48]}};

assign data_array_4_fu_706_p4 = {{layer24_out_dout[79:64]}};

assign data_array_5_fu_716_p4 = {{layer24_out_dout[95:80]}};

assign data_array_6_fu_726_p4 = {{layer24_out_dout[111:96]}};

assign data_array_7_fu_736_p4 = {{layer24_out_dout[127:112]}};

assign data_array_fu_652_p1 = layer24_out_dout[15:0];

assign exp_res_8_cast_fu_1290_p1 = exp_res_8_reg_1751;

assign exp_res_9_cast_fu_1293_p1 = exp_res_9_reg_1757;

assign exp_table_address0 = zext_ln223_9_fu_1201_p1;

assign exp_table_address1 = zext_ln223_8_fu_1186_p1;

assign exp_table_address2 = zext_ln223_7_fu_1171_p1;

assign exp_table_address3 = zext_ln223_6_fu_1156_p1;

assign exp_table_address4 = zext_ln223_5_fu_1141_p1;

assign exp_table_address5 = zext_ln223_4_fu_1126_p1;

assign exp_table_address6 = zext_ln223_3_fu_1111_p1;

assign exp_table_address7 = zext_ln223_2_fu_1096_p1;

assign exp_table_address8 = zext_ln223_1_fu_1081_p1;

assign exp_table_address9 = zext_ln223_fu_1066_p1;

assign icmp_ln66_1_fu_766_p2 = (($signed(data_array_2_fu_686_p4) < $signed(data_array_3_fu_696_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_2_fu_920_p2 = (($signed(select_ln66_reg_1573) < $signed(select_ln66_1_reg_1579)) ? 1'b1 : 1'b0);

assign icmp_ln66_3_fu_786_p2 = (($signed(data_array_4_fu_706_p4) < $signed(data_array_5_fu_716_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_4_fu_806_p2 = (($signed(data_array_6_fu_726_p4) < $signed(data_array_7_fu_736_p4)) ? 1'b1 : 1'b0);

assign icmp_ln66_5_fu_936_p2 = (($signed(select_ln66_3_reg_1585) < $signed(select_ln66_4_reg_1591)) ? 1'b1 : 1'b0);

assign icmp_ln66_6_fu_952_p2 = (($signed(select_ln66_2_fu_930_p3) < $signed(select_ln66_5_fu_946_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_7_fu_972_p2 = (($signed(data_array_8_reg_1561) < $signed(data_array_9_reg_1567)) ? 1'b1 : 1'b0);

assign icmp_ln66_8_fu_988_p2 = (($signed(select_ln66_6_fu_964_p3) < $signed(select_ln66_7_fu_982_p3)) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_746_p2 = (($signed(data_array_fu_652_p1) < $signed(data_array_1_fu_676_p4)) ? 1'b1 : 1'b0);

assign invert_table_address0 = zext_ln232_fu_1338_p1;

assign layer19_out_TDATA = $signed(tmp_10_fu_1532_p11);

assign mul_ln241_1_fu_288_p0 = sext_ln238_fu_1343_p1;

assign mul_ln241_1_fu_288_p1 = mul_ln241_1_fu_288_p10;

assign mul_ln241_1_fu_288_p10 = exp_res_1_reg_1716;

assign mul_ln241_2_fu_282_p0 = sext_ln238_fu_1343_p1;

assign mul_ln241_2_fu_282_p1 = mul_ln241_2_fu_282_p10;

assign mul_ln241_2_fu_282_p10 = exp_res_2_reg_1721;

assign mul_ln241_3_fu_285_p0 = sext_ln238_fu_1343_p1;

assign mul_ln241_3_fu_285_p1 = mul_ln241_3_fu_285_p10;

assign mul_ln241_3_fu_285_p10 = exp_res_3_reg_1726;

assign mul_ln241_4_fu_283_p0 = sext_ln238_fu_1343_p1;

assign mul_ln241_4_fu_283_p1 = mul_ln241_4_fu_283_p10;

assign mul_ln241_4_fu_283_p10 = exp_res_4_reg_1731;

assign mul_ln241_5_fu_287_p0 = sext_ln238_fu_1343_p1;

assign mul_ln241_5_fu_287_p1 = mul_ln241_5_fu_287_p10;

assign mul_ln241_5_fu_287_p10 = exp_res_5_reg_1736;

assign mul_ln241_6_fu_284_p0 = sext_ln238_fu_1343_p1;

assign mul_ln241_6_fu_284_p1 = mul_ln241_6_fu_284_p10;

assign mul_ln241_6_fu_284_p10 = exp_res_6_reg_1741;

assign mul_ln241_7_fu_286_p0 = sext_ln238_fu_1343_p1;

assign mul_ln241_7_fu_286_p1 = mul_ln241_7_fu_286_p10;

assign mul_ln241_7_fu_286_p10 = exp_res_7_reg_1746;

assign mul_ln241_8_fu_289_p0 = sext_ln238_fu_1343_p1;

assign mul_ln241_8_fu_289_p1 = mul_ln241_8_fu_289_p10;

assign mul_ln241_8_fu_289_p10 = exp_res_8_reg_1751;

assign mul_ln241_9_fu_290_p0 = sext_ln238_fu_1343_p1;

assign mul_ln241_9_fu_290_p1 = mul_ln241_9_fu_290_p10;

assign mul_ln241_9_fu_290_p10 = exp_res_9_reg_1757;

assign mul_ln241_fu_281_p0 = sext_ln238_fu_1343_p1;

assign mul_ln241_fu_281_p1 = mul_ln241_fu_281_p10;

assign mul_ln241_fu_281_p10 = exp_res_reg_1711;

assign select_ln66_1_fu_778_p3 = ((xor_ln66_1_fu_772_p2[0:0] == 1'b1) ? data_array_2_fu_686_p4 : data_array_3_fu_696_p4);

assign select_ln66_2_fu_930_p3 = ((xor_ln66_2_fu_924_p2[0:0] == 1'b1) ? select_ln66_reg_1573 : select_ln66_1_reg_1579);

assign select_ln66_3_fu_798_p3 = ((xor_ln66_3_fu_792_p2[0:0] == 1'b1) ? data_array_4_fu_706_p4 : data_array_5_fu_716_p4);

assign select_ln66_4_fu_818_p3 = ((xor_ln66_4_fu_812_p2[0:0] == 1'b1) ? data_array_6_fu_726_p4 : data_array_7_fu_736_p4);

assign select_ln66_5_fu_946_p3 = ((xor_ln66_5_fu_940_p2[0:0] == 1'b1) ? select_ln66_3_reg_1585 : select_ln66_4_reg_1591);

assign select_ln66_6_fu_964_p3 = ((xor_ln66_6_fu_958_p2[0:0] == 1'b1) ? select_ln66_2_fu_930_p3 : select_ln66_5_fu_946_p3);

assign select_ln66_7_fu_982_p3 = ((xor_ln66_7_fu_976_p2[0:0] == 1'b1) ? data_array_8_reg_1561 : data_array_9_reg_1567);

assign select_ln66_8_fu_1008_p3 = ((xor_ln66_8_fu_994_p2[0:0] == 1'b1) ? trunc_ln66_fu_1000_p1 : trunc_ln66_1_fu_1004_p1);

assign select_ln66_fu_758_p3 = ((xor_ln66_fu_752_p2[0:0] == 1'b1) ? data_array_fu_652_p1 : data_array_1_fu_676_p4);

assign sext_ln238_fu_1343_p1 = $signed(inv_exp_sum_reg_1778);

assign sext_ln241_1_fu_1388_p1 = $signed(trunc_ln241_1_fu_1378_p4);

assign sext_ln241_2_fu_1406_p1 = $signed(trunc_ln241_2_fu_1396_p4);

assign sext_ln241_3_fu_1424_p1 = $signed(trunc_ln241_3_fu_1414_p4);

assign sext_ln241_4_fu_1442_p1 = $signed(trunc_ln241_4_fu_1432_p4);

assign sext_ln241_5_fu_1460_p1 = $signed(trunc_ln241_5_fu_1450_p4);

assign sext_ln241_6_fu_1478_p1 = $signed(trunc_ln241_6_fu_1468_p4);

assign sext_ln241_7_fu_1496_p1 = $signed(trunc_ln241_7_fu_1486_p4);

assign sext_ln241_8_fu_1514_p1 = $signed(trunc_ln241_8_fu_1504_p4);

assign sext_ln241_fu_1370_p1 = $signed(trunc_ln1_fu_1360_p4);

assign tmp_10_fu_1532_p11 = {{{{{{{{{{trunc_ln241_9_fu_1522_p4}, {sext_ln241_8_fu_1514_p1}}, {sext_ln241_7_fu_1496_p1}}, {sext_ln241_6_fu_1478_p1}}, {sext_ln241_5_fu_1460_p1}}, {sext_ln241_4_fu_1442_p1}}, {sext_ln241_3_fu_1424_p1}}, {sext_ln241_2_fu_1406_p1}}, {sext_ln241_1_fu_1388_p1}}, {sext_ln241_fu_1370_p1}};

assign tmp_1_fu_1086_p4 = {{d_xi_xmax_11_fu_1024_p2[14:5]}};

assign tmp_2_fu_1101_p4 = {{d_xi_xmax_12_fu_1028_p2[14:5]}};

assign tmp_3_fu_1116_p4 = {{d_xi_xmax_13_fu_1032_p2[14:5]}};

assign tmp_4_fu_1131_p4 = {{d_xi_xmax_14_fu_1036_p2[14:5]}};

assign tmp_5_fu_1146_p4 = {{d_xi_xmax_15_fu_1040_p2[14:5]}};

assign tmp_6_fu_1161_p4 = {{d_xi_xmax_16_fu_1044_p2[14:5]}};

assign tmp_7_fu_1176_p4 = {{d_xi_xmax_17_fu_1048_p2[14:5]}};

assign tmp_8_fu_1191_p4 = {{d_xi_xmax_18_fu_1052_p2[14:5]}};

assign tmp_9_fu_1328_p4 = {{add_ln51_4_fu_1322_p2[14:8]}};

assign tmp_fu_1056_p4 = {{d_xi_xmax_fu_1016_p2[14:5]}};

assign tmp_s_fu_1071_p4 = {{d_xi_xmax_10_fu_1020_p2[14:5]}};

assign trunc_ln1_fu_1360_p4 = {{mul_ln241_fu_281_p2[28:14]}};

assign trunc_ln213_fu_826_p1 = layer24_out_dout[14:0];

assign trunc_ln241_1_fu_1378_p4 = {{mul_ln241_1_fu_288_p2[28:14]}};

assign trunc_ln241_2_fu_1396_p4 = {{mul_ln241_2_fu_282_p2[28:14]}};

assign trunc_ln241_3_fu_1414_p4 = {{mul_ln241_3_fu_285_p2[28:14]}};

assign trunc_ln241_4_fu_1432_p4 = {{mul_ln241_4_fu_283_p2[28:14]}};

assign trunc_ln241_5_fu_1450_p4 = {{mul_ln241_5_fu_287_p2[28:14]}};

assign trunc_ln241_6_fu_1468_p4 = {{mul_ln241_6_fu_284_p2[28:14]}};

assign trunc_ln241_7_fu_1486_p4 = {{mul_ln241_7_fu_286_p2[28:14]}};

assign trunc_ln241_8_fu_1504_p4 = {{mul_ln241_8_fu_289_p2[28:14]}};

assign trunc_ln241_9_fu_1522_p4 = {{mul_ln241_9_fu_290_p2[28:14]}};

assign trunc_ln66_1_fu_1004_p1 = select_ln66_7_fu_982_p3[14:0];

assign trunc_ln66_fu_1000_p1 = select_ln66_6_fu_964_p3[14:0];

assign xor_ln66_1_fu_772_p2 = (icmp_ln66_1_fu_766_p2 ^ 1'd1);

assign xor_ln66_2_fu_924_p2 = (icmp_ln66_2_fu_920_p2 ^ 1'd1);

assign xor_ln66_3_fu_792_p2 = (icmp_ln66_3_fu_786_p2 ^ 1'd1);

assign xor_ln66_4_fu_812_p2 = (icmp_ln66_4_fu_806_p2 ^ 1'd1);

assign xor_ln66_5_fu_940_p2 = (icmp_ln66_5_fu_936_p2 ^ 1'd1);

assign xor_ln66_6_fu_958_p2 = (icmp_ln66_6_fu_952_p2 ^ 1'd1);

assign xor_ln66_7_fu_976_p2 = (icmp_ln66_7_fu_972_p2 ^ 1'd1);

assign xor_ln66_8_fu_994_p2 = (icmp_ln66_8_fu_988_p2 ^ 1'd1);

assign xor_ln66_fu_752_p2 = (icmp_ln66_fu_746_p2 ^ 1'd1);

assign zext_ln223_1_fu_1081_p1 = tmp_s_fu_1071_p4;

assign zext_ln223_2_fu_1096_p1 = tmp_1_fu_1086_p4;

assign zext_ln223_3_fu_1111_p1 = tmp_2_fu_1101_p4;

assign zext_ln223_4_fu_1126_p1 = tmp_3_fu_1116_p4;

assign zext_ln223_5_fu_1141_p1 = tmp_4_fu_1131_p4;

assign zext_ln223_6_fu_1156_p1 = tmp_5_fu_1146_p4;

assign zext_ln223_7_fu_1171_p1 = tmp_6_fu_1161_p4;

assign zext_ln223_8_fu_1186_p1 = tmp_7_fu_1176_p4;

assign zext_ln223_9_fu_1201_p1 = tmp_8_fu_1191_p4;

assign zext_ln223_fu_1066_p1 = tmp_fu_1056_p4;

assign zext_ln232_fu_1338_p1 = tmp_9_fu_1328_p4;

assign zext_ln51_10_fu_1270_p1 = exp_table_q2;

assign zext_ln51_11_fu_1280_p1 = add_ln51_7_fu_1274_p2;

assign zext_ln51_12_fu_1299_p1 = add_ln51_8_reg_1768;

assign zext_ln51_13_fu_1308_p1 = add_ln51_1_fu_1302_p2;

assign zext_ln51_14_fu_1318_p1 = add_ln51_2_fu_1312_p2;

assign zext_ln51_1_fu_1210_p1 = exp_table_q8;

assign zext_ln51_2_fu_1220_p1 = add_ln51_fu_1214_p2;

assign zext_ln51_3_fu_1224_p1 = exp_table_q7;

assign zext_ln51_4_fu_1228_p1 = exp_table_q6;

assign zext_ln51_5_fu_1238_p1 = add_ln51_3_fu_1232_p2;

assign zext_ln51_6_fu_1248_p1 = exp_table_q5;

assign zext_ln51_7_fu_1252_p1 = exp_table_q4;

assign zext_ln51_8_fu_1262_p1 = add_ln51_6_fu_1256_p2;

assign zext_ln51_9_fu_1266_p1 = exp_table_q3;

assign zext_ln51_fu_1206_p1 = exp_table_q9;

endmodule //myproject_softmax_stable_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_s
