// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer21_out_dout,
        layer21_out_num_data_valid,
        layer21_out_fifo_cap,
        layer21_out_empty_n,
        layer21_out_read,
        layer8_out_din,
        layer8_out_num_data_valid,
        layer8_out_fifo_cap,
        layer8_out_full_n,
        layer8_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [255:0] layer21_out_dout;
input  [6:0] layer21_out_num_data_valid;
input  [6:0] layer21_out_fifo_cap;
input   layer21_out_empty_n;
output   layer21_out_read;
output  [127:0] layer8_out_din;
input  [6:0] layer8_out_num_data_valid;
input  [6:0] layer8_out_fifo_cap;
input   layer8_out_full_n;
output   layer8_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer21_out_read;
reg layer8_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_273_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer21_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer8_out_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] out_data_19_fu_608_p3;
reg   [7:0] out_data_19_reg_2520;
wire   [7:0] out_data_21_fu_736_p3;
reg   [7:0] out_data_21_reg_2525;
wire   [7:0] out_data_23_fu_864_p3;
reg   [7:0] out_data_23_reg_2530;
wire   [7:0] out_data_25_fu_992_p3;
reg   [7:0] out_data_25_reg_2535;
wire   [7:0] out_data_27_fu_1120_p3;
reg   [7:0] out_data_27_reg_2540;
wire   [7:0] out_data_29_fu_1248_p3;
reg   [7:0] out_data_29_reg_2545;
wire   [7:0] out_data_31_fu_1376_p3;
reg   [7:0] out_data_31_reg_2550;
wire   [7:0] out_data_33_fu_1504_p3;
reg   [7:0] out_data_33_reg_2555;
wire   [7:0] select_ln51_fu_1624_p3;
reg   [7:0] select_ln51_reg_2560;
wire   [7:0] select_ln51_84_fu_1744_p3;
reg   [7:0] select_ln51_84_reg_2565;
wire   [7:0] select_ln51_85_fu_1864_p3;
reg   [7:0] select_ln51_85_reg_2570;
wire   [7:0] select_ln51_86_fu_1984_p3;
reg   [7:0] select_ln51_86_reg_2575;
wire   [7:0] select_ln51_87_fu_2104_p3;
reg   [7:0] select_ln51_87_reg_2580;
wire   [7:0] select_ln51_88_fu_2224_p3;
reg   [7:0] select_ln51_88_reg_2585;
wire   [7:0] select_ln51_89_fu_2352_p3;
reg   [7:0] select_ln51_89_reg_2590;
wire   [7:0] select_ln51_90_fu_2480_p3;
reg   [7:0] select_ln51_90_reg_2595;
reg   [6:0] i_fu_248;
wire   [6:0] i_4_fu_279_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_3;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] in_data_fu_290_p1;
wire   [0:0] tmp_614_fu_508_p3;
wire   [0:0] trunc_ln52_fu_524_p1;
wire   [0:0] or_ln52_fu_528_p2;
wire   [0:0] tmp_615_fu_516_p3;
wire   [0:0] and_ln52_fu_534_p2;
wire   [7:0] trunc_ln4_fu_498_p4;
wire   [7:0] zext_ln52_fu_540_p1;
wire   [5:0] tmp_258_fu_550_p4;
wire   [7:0] add_ln52_fu_544_p2;
wire   [0:0] tmp_617_fu_574_p3;
wire   [0:0] tmp_616_fu_566_p3;
wire   [0:0] xor_ln52_fu_582_p2;
wire   [0:0] icmp_ln52_fu_560_p2;
wire   [0:0] or_ln52_174_fu_588_p2;
wire   [0:0] and_ln52_179_fu_594_p2;
wire   [0:0] icmp_ln51_fu_492_p2;
wire   [7:0] out_data_fu_600_p3;
wire   [15:0] in_data_7_fu_362_p4;
wire   [0:0] tmp_618_fu_632_p3;
wire   [0:0] tmp_620_fu_648_p3;
wire   [0:0] or_ln52_89_fu_656_p2;
wire   [0:0] tmp_619_fu_640_p3;
wire   [0:0] and_ln52_180_fu_662_p2;
wire   [7:0] trunc_ln52_s_fu_622_p4;
wire   [7:0] zext_ln52_89_fu_668_p1;
wire   [5:0] tmp_259_fu_678_p4;
wire   [7:0] add_ln52_89_fu_672_p2;
wire   [0:0] tmp_622_fu_702_p3;
wire   [0:0] tmp_621_fu_694_p3;
wire   [0:0] xor_ln52_89_fu_710_p2;
wire   [0:0] icmp_ln52_89_fu_688_p2;
wire   [0:0] or_ln52_175_fu_716_p2;
wire   [0:0] and_ln52_181_fu_722_p2;
wire   [0:0] icmp_ln51_89_fu_616_p2;
wire   [7:0] out_data_20_fu_728_p3;
wire   [15:0] in_data_8_fu_372_p4;
wire   [0:0] tmp_623_fu_760_p3;
wire   [0:0] tmp_625_fu_776_p3;
wire   [0:0] or_ln52_90_fu_784_p2;
wire   [0:0] tmp_624_fu_768_p3;
wire   [0:0] and_ln52_182_fu_790_p2;
wire   [7:0] trunc_ln52_87_fu_750_p4;
wire   [7:0] zext_ln52_90_fu_796_p1;
wire   [5:0] tmp_260_fu_806_p4;
wire   [7:0] add_ln52_90_fu_800_p2;
wire   [0:0] tmp_627_fu_830_p3;
wire   [0:0] tmp_626_fu_822_p3;
wire   [0:0] xor_ln52_90_fu_838_p2;
wire   [0:0] icmp_ln52_90_fu_816_p2;
wire   [0:0] or_ln52_176_fu_844_p2;
wire   [0:0] and_ln52_183_fu_850_p2;
wire   [0:0] icmp_ln51_90_fu_744_p2;
wire   [7:0] out_data_22_fu_856_p3;
wire   [15:0] in_data_9_fu_382_p4;
wire   [0:0] tmp_628_fu_888_p3;
wire   [0:0] tmp_630_fu_904_p3;
wire   [0:0] or_ln52_91_fu_912_p2;
wire   [0:0] tmp_629_fu_896_p3;
wire   [0:0] and_ln52_184_fu_918_p2;
wire   [7:0] trunc_ln52_88_fu_878_p4;
wire   [7:0] zext_ln52_91_fu_924_p1;
wire   [5:0] tmp_261_fu_934_p4;
wire   [7:0] add_ln52_91_fu_928_p2;
wire   [0:0] tmp_632_fu_958_p3;
wire   [0:0] tmp_631_fu_950_p3;
wire   [0:0] xor_ln52_91_fu_966_p2;
wire   [0:0] icmp_ln52_91_fu_944_p2;
wire   [0:0] or_ln52_177_fu_972_p2;
wire   [0:0] and_ln52_185_fu_978_p2;
wire   [0:0] icmp_ln51_91_fu_872_p2;
wire   [7:0] out_data_24_fu_984_p3;
wire   [15:0] tmp_fu_392_p4;
wire   [0:0] tmp_633_fu_1016_p3;
wire   [0:0] tmp_635_fu_1032_p3;
wire   [0:0] or_ln52_92_fu_1040_p2;
wire   [0:0] tmp_634_fu_1024_p3;
wire   [0:0] and_ln52_186_fu_1046_p2;
wire   [7:0] trunc_ln52_89_fu_1006_p4;
wire   [7:0] zext_ln52_92_fu_1052_p1;
wire   [5:0] tmp_262_fu_1062_p4;
wire   [7:0] add_ln52_92_fu_1056_p2;
wire   [0:0] tmp_637_fu_1086_p3;
wire   [0:0] tmp_636_fu_1078_p3;
wire   [0:0] xor_ln52_92_fu_1094_p2;
wire   [0:0] icmp_ln52_92_fu_1072_p2;
wire   [0:0] or_ln52_178_fu_1100_p2;
wire   [0:0] and_ln52_187_fu_1106_p2;
wire   [0:0] icmp_ln51_92_fu_1000_p2;
wire   [7:0] out_data_26_fu_1112_p3;
wire   [15:0] tmp_s_fu_402_p4;
wire   [0:0] tmp_638_fu_1144_p3;
wire   [0:0] tmp_640_fu_1160_p3;
wire   [0:0] or_ln52_93_fu_1168_p2;
wire   [0:0] tmp_639_fu_1152_p3;
wire   [0:0] and_ln52_188_fu_1174_p2;
wire   [7:0] trunc_ln52_90_fu_1134_p4;
wire   [7:0] zext_ln52_93_fu_1180_p1;
wire   [5:0] tmp_263_fu_1190_p4;
wire   [7:0] add_ln52_93_fu_1184_p2;
wire   [0:0] tmp_642_fu_1214_p3;
wire   [0:0] tmp_641_fu_1206_p3;
wire   [0:0] xor_ln52_93_fu_1222_p2;
wire   [0:0] icmp_ln52_93_fu_1200_p2;
wire   [0:0] or_ln52_179_fu_1228_p2;
wire   [0:0] and_ln52_189_fu_1234_p2;
wire   [0:0] icmp_ln51_93_fu_1128_p2;
wire   [7:0] out_data_28_fu_1240_p3;
wire   [15:0] tmp_250_fu_412_p4;
wire   [0:0] tmp_643_fu_1272_p3;
wire   [0:0] tmp_645_fu_1288_p3;
wire   [0:0] or_ln52_94_fu_1296_p2;
wire   [0:0] tmp_644_fu_1280_p3;
wire   [0:0] and_ln52_190_fu_1302_p2;
wire   [7:0] trunc_ln52_91_fu_1262_p4;
wire   [7:0] zext_ln52_94_fu_1308_p1;
wire   [5:0] tmp_264_fu_1318_p4;
wire   [7:0] add_ln52_94_fu_1312_p2;
wire   [0:0] tmp_647_fu_1342_p3;
wire   [0:0] tmp_646_fu_1334_p3;
wire   [0:0] xor_ln52_94_fu_1350_p2;
wire   [0:0] icmp_ln52_94_fu_1328_p2;
wire   [0:0] or_ln52_180_fu_1356_p2;
wire   [0:0] and_ln52_191_fu_1362_p2;
wire   [0:0] icmp_ln51_94_fu_1256_p2;
wire   [7:0] out_data_30_fu_1368_p3;
wire   [15:0] tmp_251_fu_422_p4;
wire   [0:0] tmp_648_fu_1400_p3;
wire   [0:0] tmp_650_fu_1416_p3;
wire   [0:0] or_ln52_95_fu_1424_p2;
wire   [0:0] tmp_649_fu_1408_p3;
wire   [0:0] and_ln52_192_fu_1430_p2;
wire   [7:0] trunc_ln52_92_fu_1390_p4;
wire   [7:0] zext_ln52_95_fu_1436_p1;
wire   [5:0] tmp_265_fu_1446_p4;
wire   [7:0] add_ln52_95_fu_1440_p2;
wire   [0:0] tmp_652_fu_1470_p3;
wire   [0:0] tmp_651_fu_1462_p3;
wire   [0:0] xor_ln52_95_fu_1478_p2;
wire   [0:0] icmp_ln52_95_fu_1456_p2;
wire   [0:0] or_ln52_181_fu_1484_p2;
wire   [0:0] and_ln52_193_fu_1490_p2;
wire   [0:0] icmp_ln51_95_fu_1384_p2;
wire   [7:0] out_data_32_fu_1496_p3;
wire   [15:0] tmp_252_fu_432_p4;
wire   [0:0] tmp_653_fu_1528_p3;
wire   [0:0] tmp_608_fu_314_p3;
wire   [0:0] or_ln52_96_fu_1544_p2;
wire   [0:0] tmp_654_fu_1536_p3;
wire   [0:0] and_ln52_194_fu_1550_p2;
wire   [7:0] trunc_ln52_93_fu_1518_p4;
wire   [7:0] zext_ln52_96_fu_1556_p1;
wire   [5:0] tmp_266_fu_1566_p4;
wire   [7:0] add_ln52_96_fu_1560_p2;
wire   [0:0] tmp_656_fu_1590_p3;
wire   [0:0] tmp_655_fu_1582_p3;
wire   [0:0] xor_ln52_96_fu_1598_p2;
wire   [0:0] icmp_ln52_96_fu_1576_p2;
wire   [0:0] or_ln52_182_fu_1604_p2;
wire   [0:0] and_ln52_195_fu_1610_p2;
wire   [0:0] icmp_ln51_96_fu_1512_p2;
wire   [7:0] select_ln52_fu_1616_p3;
wire   [15:0] tmp_253_fu_442_p4;
wire   [0:0] tmp_657_fu_1648_p3;
wire   [0:0] tmp_609_fu_322_p3;
wire   [0:0] or_ln52_97_fu_1664_p2;
wire   [0:0] tmp_658_fu_1656_p3;
wire   [0:0] and_ln52_196_fu_1670_p2;
wire   [7:0] trunc_ln52_94_fu_1638_p4;
wire   [7:0] zext_ln52_97_fu_1676_p1;
wire   [5:0] tmp_267_fu_1686_p4;
wire   [7:0] add_ln52_97_fu_1680_p2;
wire   [0:0] tmp_660_fu_1710_p3;
wire   [0:0] tmp_659_fu_1702_p3;
wire   [0:0] xor_ln52_97_fu_1718_p2;
wire   [0:0] icmp_ln52_97_fu_1696_p2;
wire   [0:0] or_ln52_183_fu_1724_p2;
wire   [0:0] and_ln52_197_fu_1730_p2;
wire   [0:0] icmp_ln51_97_fu_1632_p2;
wire   [7:0] select_ln52_76_fu_1736_p3;
wire   [15:0] tmp_254_fu_452_p4;
wire   [0:0] tmp_661_fu_1768_p3;
wire   [0:0] tmp_610_fu_330_p3;
wire   [0:0] or_ln52_98_fu_1784_p2;
wire   [0:0] tmp_662_fu_1776_p3;
wire   [0:0] and_ln52_198_fu_1790_p2;
wire   [7:0] trunc_ln52_95_fu_1758_p4;
wire   [7:0] zext_ln52_98_fu_1796_p1;
wire   [5:0] tmp_268_fu_1806_p4;
wire   [7:0] add_ln52_98_fu_1800_p2;
wire   [0:0] tmp_664_fu_1830_p3;
wire   [0:0] tmp_663_fu_1822_p3;
wire   [0:0] xor_ln52_98_fu_1838_p2;
wire   [0:0] icmp_ln52_98_fu_1816_p2;
wire   [0:0] or_ln52_184_fu_1844_p2;
wire   [0:0] and_ln52_199_fu_1850_p2;
wire   [0:0] icmp_ln51_98_fu_1752_p2;
wire   [7:0] select_ln52_77_fu_1856_p3;
wire   [15:0] tmp_255_fu_462_p4;
wire   [0:0] tmp_665_fu_1888_p3;
wire   [0:0] tmp_611_fu_338_p3;
wire   [0:0] or_ln52_99_fu_1904_p2;
wire   [0:0] tmp_666_fu_1896_p3;
wire   [0:0] and_ln52_200_fu_1910_p2;
wire   [7:0] trunc_ln52_96_fu_1878_p4;
wire   [7:0] zext_ln52_99_fu_1916_p1;
wire   [5:0] tmp_269_fu_1926_p4;
wire   [7:0] add_ln52_99_fu_1920_p2;
wire   [0:0] tmp_668_fu_1950_p3;
wire   [0:0] tmp_667_fu_1942_p3;
wire   [0:0] xor_ln52_99_fu_1958_p2;
wire   [0:0] icmp_ln52_99_fu_1936_p2;
wire   [0:0] or_ln52_185_fu_1964_p2;
wire   [0:0] and_ln52_201_fu_1970_p2;
wire   [0:0] icmp_ln51_99_fu_1872_p2;
wire   [7:0] select_ln52_78_fu_1976_p3;
wire   [15:0] tmp_256_fu_472_p4;
wire   [0:0] tmp_669_fu_2008_p3;
wire   [0:0] tmp_612_fu_346_p3;
wire   [0:0] or_ln52_100_fu_2024_p2;
wire   [0:0] tmp_670_fu_2016_p3;
wire   [0:0] and_ln52_202_fu_2030_p2;
wire   [7:0] trunc_ln52_97_fu_1998_p4;
wire   [7:0] zext_ln52_100_fu_2036_p1;
wire   [5:0] tmp_270_fu_2046_p4;
wire   [7:0] add_ln52_100_fu_2040_p2;
wire   [0:0] tmp_672_fu_2070_p3;
wire   [0:0] tmp_671_fu_2062_p3;
wire   [0:0] xor_ln52_100_fu_2078_p2;
wire   [0:0] icmp_ln52_100_fu_2056_p2;
wire   [0:0] or_ln52_186_fu_2084_p2;
wire   [0:0] and_ln52_203_fu_2090_p2;
wire   [0:0] icmp_ln51_100_fu_1992_p2;
wire   [7:0] select_ln52_79_fu_2096_p3;
wire   [15:0] tmp_257_fu_482_p4;
wire   [0:0] tmp_673_fu_2128_p3;
wire   [0:0] tmp_613_fu_354_p3;
wire   [0:0] or_ln52_101_fu_2144_p2;
wire   [0:0] tmp_674_fu_2136_p3;
wire   [0:0] and_ln52_204_fu_2150_p2;
wire   [7:0] trunc_ln52_98_fu_2118_p4;
wire   [7:0] zext_ln52_101_fu_2156_p1;
wire   [5:0] tmp_271_fu_2166_p4;
wire   [7:0] add_ln52_101_fu_2160_p2;
wire   [0:0] tmp_676_fu_2190_p3;
wire   [0:0] tmp_675_fu_2182_p3;
wire   [0:0] xor_ln52_101_fu_2198_p2;
wire   [0:0] icmp_ln52_101_fu_2176_p2;
wire   [0:0] or_ln52_187_fu_2204_p2;
wire   [0:0] and_ln52_205_fu_2210_p2;
wire   [0:0] icmp_ln51_101_fu_2112_p2;
wire   [7:0] select_ln52_80_fu_2216_p3;
wire   [15:0] trunc_ln44_s_fu_294_p4;
wire   [0:0] tmp_677_fu_2248_p3;
wire   [0:0] tmp_679_fu_2264_p3;
wire   [0:0] or_ln52_102_fu_2272_p2;
wire   [0:0] tmp_678_fu_2256_p3;
wire   [0:0] and_ln52_206_fu_2278_p2;
wire   [7:0] trunc_ln52_99_fu_2238_p4;
wire   [7:0] zext_ln52_102_fu_2284_p1;
wire   [5:0] tmp_272_fu_2294_p4;
wire   [7:0] add_ln52_102_fu_2288_p2;
wire   [0:0] tmp_681_fu_2318_p3;
wire   [0:0] tmp_680_fu_2310_p3;
wire   [0:0] xor_ln52_102_fu_2326_p2;
wire   [0:0] icmp_ln52_102_fu_2304_p2;
wire   [0:0] or_ln52_188_fu_2332_p2;
wire   [0:0] and_ln52_207_fu_2338_p2;
wire   [0:0] icmp_ln51_102_fu_2232_p2;
wire   [7:0] select_ln52_81_fu_2344_p3;
wire   [15:0] trunc_ln44_2_fu_304_p4;
wire   [0:0] tmp_682_fu_2376_p3;
wire   [0:0] tmp_684_fu_2392_p3;
wire   [0:0] or_ln52_103_fu_2400_p2;
wire   [0:0] tmp_683_fu_2384_p3;
wire   [0:0] and_ln52_208_fu_2406_p2;
wire   [7:0] trunc_ln52_100_fu_2366_p4;
wire   [7:0] zext_ln52_103_fu_2412_p1;
wire   [5:0] tmp_273_fu_2422_p4;
wire   [7:0] add_ln52_103_fu_2416_p2;
wire   [0:0] tmp_686_fu_2446_p3;
wire   [0:0] tmp_685_fu_2438_p3;
wire   [0:0] xor_ln52_103_fu_2454_p2;
wire   [0:0] icmp_ln52_103_fu_2432_p2;
wire   [0:0] or_ln52_189_fu_2460_p2;
wire   [0:0] and_ln52_209_fu_2466_p2;
wire   [0:0] icmp_ln51_103_fu_2360_p2;
wire   [7:0] select_ln52_82_fu_2472_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_142;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_142)) begin
        if ((icmp_ln41_fu_273_p2 == 1'd0)) begin
            i_fu_248 <= i_4_fu_279_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_248 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        out_data_19_reg_2520 <= out_data_19_fu_608_p3;
        out_data_21_reg_2525 <= out_data_21_fu_736_p3;
        out_data_23_reg_2530 <= out_data_23_fu_864_p3;
        out_data_25_reg_2535 <= out_data_25_fu_992_p3;
        out_data_27_reg_2540 <= out_data_27_fu_1120_p3;
        out_data_29_reg_2545 <= out_data_29_fu_1248_p3;
        out_data_31_reg_2550 <= out_data_31_fu_1376_p3;
        out_data_33_reg_2555 <= out_data_33_fu_1504_p3;
        select_ln51_84_reg_2565 <= select_ln51_84_fu_1744_p3;
        select_ln51_85_reg_2570 <= select_ln51_85_fu_1864_p3;
        select_ln51_86_reg_2575 <= select_ln51_86_fu_1984_p3;
        select_ln51_87_reg_2580 <= select_ln51_87_fu_2104_p3;
        select_ln51_88_reg_2585 <= select_ln51_88_fu_2224_p3;
        select_ln51_89_reg_2590 <= select_ln51_89_fu_2352_p3;
        select_ln51_90_reg_2595 <= select_ln51_90_fu_2480_p3;
        select_ln51_reg_2560 <= select_ln51_fu_1624_p3;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_273_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_3 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_3 = i_fu_248;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer21_out_blk_n = layer21_out_empty_n;
    end else begin
        layer21_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer21_out_read = 1'b1;
    end else begin
        layer21_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer8_out_blk_n = layer8_out_full_n;
    end else begin
        layer8_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer8_out_write = 1'b1;
    end else begin
        layer8_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_100_fu_2040_p2 = (trunc_ln52_97_fu_1998_p4 + zext_ln52_100_fu_2036_p1);

assign add_ln52_101_fu_2160_p2 = (trunc_ln52_98_fu_2118_p4 + zext_ln52_101_fu_2156_p1);

assign add_ln52_102_fu_2288_p2 = (trunc_ln52_99_fu_2238_p4 + zext_ln52_102_fu_2284_p1);

assign add_ln52_103_fu_2416_p2 = (trunc_ln52_100_fu_2366_p4 + zext_ln52_103_fu_2412_p1);

assign add_ln52_89_fu_672_p2 = (trunc_ln52_s_fu_622_p4 + zext_ln52_89_fu_668_p1);

assign add_ln52_90_fu_800_p2 = (trunc_ln52_87_fu_750_p4 + zext_ln52_90_fu_796_p1);

assign add_ln52_91_fu_928_p2 = (trunc_ln52_88_fu_878_p4 + zext_ln52_91_fu_924_p1);

assign add_ln52_92_fu_1056_p2 = (trunc_ln52_89_fu_1006_p4 + zext_ln52_92_fu_1052_p1);

assign add_ln52_93_fu_1184_p2 = (trunc_ln52_90_fu_1134_p4 + zext_ln52_93_fu_1180_p1);

assign add_ln52_94_fu_1312_p2 = (trunc_ln52_91_fu_1262_p4 + zext_ln52_94_fu_1308_p1);

assign add_ln52_95_fu_1440_p2 = (trunc_ln52_92_fu_1390_p4 + zext_ln52_95_fu_1436_p1);

assign add_ln52_96_fu_1560_p2 = (trunc_ln52_93_fu_1518_p4 + zext_ln52_96_fu_1556_p1);

assign add_ln52_97_fu_1680_p2 = (trunc_ln52_94_fu_1638_p4 + zext_ln52_97_fu_1676_p1);

assign add_ln52_98_fu_1800_p2 = (trunc_ln52_95_fu_1758_p4 + zext_ln52_98_fu_1796_p1);

assign add_ln52_99_fu_1920_p2 = (trunc_ln52_96_fu_1878_p4 + zext_ln52_99_fu_1916_p1);

assign add_ln52_fu_544_p2 = (trunc_ln4_fu_498_p4 + zext_ln52_fu_540_p1);

assign and_ln52_179_fu_594_p2 = (or_ln52_174_fu_588_p2 & icmp_ln52_fu_560_p2);

assign and_ln52_180_fu_662_p2 = (tmp_619_fu_640_p3 & or_ln52_89_fu_656_p2);

assign and_ln52_181_fu_722_p2 = (or_ln52_175_fu_716_p2 & icmp_ln52_89_fu_688_p2);

assign and_ln52_182_fu_790_p2 = (tmp_624_fu_768_p3 & or_ln52_90_fu_784_p2);

assign and_ln52_183_fu_850_p2 = (or_ln52_176_fu_844_p2 & icmp_ln52_90_fu_816_p2);

assign and_ln52_184_fu_918_p2 = (tmp_629_fu_896_p3 & or_ln52_91_fu_912_p2);

assign and_ln52_185_fu_978_p2 = (or_ln52_177_fu_972_p2 & icmp_ln52_91_fu_944_p2);

assign and_ln52_186_fu_1046_p2 = (tmp_634_fu_1024_p3 & or_ln52_92_fu_1040_p2);

assign and_ln52_187_fu_1106_p2 = (or_ln52_178_fu_1100_p2 & icmp_ln52_92_fu_1072_p2);

assign and_ln52_188_fu_1174_p2 = (tmp_639_fu_1152_p3 & or_ln52_93_fu_1168_p2);

assign and_ln52_189_fu_1234_p2 = (or_ln52_179_fu_1228_p2 & icmp_ln52_93_fu_1200_p2);

assign and_ln52_190_fu_1302_p2 = (tmp_644_fu_1280_p3 & or_ln52_94_fu_1296_p2);

assign and_ln52_191_fu_1362_p2 = (or_ln52_180_fu_1356_p2 & icmp_ln52_94_fu_1328_p2);

assign and_ln52_192_fu_1430_p2 = (tmp_649_fu_1408_p3 & or_ln52_95_fu_1424_p2);

assign and_ln52_193_fu_1490_p2 = (or_ln52_181_fu_1484_p2 & icmp_ln52_95_fu_1456_p2);

assign and_ln52_194_fu_1550_p2 = (tmp_654_fu_1536_p3 & or_ln52_96_fu_1544_p2);

assign and_ln52_195_fu_1610_p2 = (or_ln52_182_fu_1604_p2 & icmp_ln52_96_fu_1576_p2);

assign and_ln52_196_fu_1670_p2 = (tmp_658_fu_1656_p3 & or_ln52_97_fu_1664_p2);

assign and_ln52_197_fu_1730_p2 = (or_ln52_183_fu_1724_p2 & icmp_ln52_97_fu_1696_p2);

assign and_ln52_198_fu_1790_p2 = (tmp_662_fu_1776_p3 & or_ln52_98_fu_1784_p2);

assign and_ln52_199_fu_1850_p2 = (or_ln52_184_fu_1844_p2 & icmp_ln52_98_fu_1816_p2);

assign and_ln52_200_fu_1910_p2 = (tmp_666_fu_1896_p3 & or_ln52_99_fu_1904_p2);

assign and_ln52_201_fu_1970_p2 = (or_ln52_185_fu_1964_p2 & icmp_ln52_99_fu_1936_p2);

assign and_ln52_202_fu_2030_p2 = (tmp_670_fu_2016_p3 & or_ln52_100_fu_2024_p2);

assign and_ln52_203_fu_2090_p2 = (or_ln52_186_fu_2084_p2 & icmp_ln52_100_fu_2056_p2);

assign and_ln52_204_fu_2150_p2 = (tmp_674_fu_2136_p3 & or_ln52_101_fu_2144_p2);

assign and_ln52_205_fu_2210_p2 = (or_ln52_187_fu_2204_p2 & icmp_ln52_101_fu_2176_p2);

assign and_ln52_206_fu_2278_p2 = (tmp_678_fu_2256_p3 & or_ln52_102_fu_2272_p2);

assign and_ln52_207_fu_2338_p2 = (or_ln52_188_fu_2332_p2 & icmp_ln52_102_fu_2304_p2);

assign and_ln52_208_fu_2406_p2 = (tmp_683_fu_2384_p3 & or_ln52_103_fu_2400_p2);

assign and_ln52_209_fu_2466_p2 = (or_ln52_189_fu_2460_p2 & icmp_ln52_103_fu_2432_p2);

assign and_ln52_fu_534_p2 = (tmp_615_fu_516_p3 & or_ln52_fu_528_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((layer8_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer21_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((layer8_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer21_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((layer8_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer21_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer21_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (layer8_out_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_142 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_4_fu_279_p2 = (ap_sig_allocacmp_i_3 + 7'd1);

assign icmp_ln41_fu_273_p2 = ((ap_sig_allocacmp_i_3 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln51_100_fu_1992_p2 = (($signed(tmp_256_fu_472_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_101_fu_2112_p2 = (($signed(tmp_257_fu_482_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_102_fu_2232_p2 = (($signed(trunc_ln44_s_fu_294_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_103_fu_2360_p2 = (($signed(trunc_ln44_2_fu_304_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_89_fu_616_p2 = (($signed(in_data_7_fu_362_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_90_fu_744_p2 = (($signed(in_data_8_fu_372_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_91_fu_872_p2 = (($signed(in_data_9_fu_382_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_92_fu_1000_p2 = (($signed(tmp_fu_392_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_93_fu_1128_p2 = (($signed(tmp_s_fu_402_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_94_fu_1256_p2 = (($signed(tmp_250_fu_412_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_95_fu_1384_p2 = (($signed(tmp_251_fu_422_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_96_fu_1512_p2 = (($signed(tmp_252_fu_432_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_97_fu_1632_p2 = (($signed(tmp_253_fu_442_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_98_fu_1752_p2 = (($signed(tmp_254_fu_452_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_99_fu_1872_p2 = (($signed(tmp_255_fu_462_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_492_p2 = (($signed(in_data_fu_290_p1) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln52_100_fu_2056_p2 = ((tmp_270_fu_2046_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_101_fu_2176_p2 = ((tmp_271_fu_2166_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_102_fu_2304_p2 = ((tmp_272_fu_2294_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_103_fu_2432_p2 = ((tmp_273_fu_2422_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_89_fu_688_p2 = ((tmp_259_fu_678_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_90_fu_816_p2 = ((tmp_260_fu_806_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_91_fu_944_p2 = ((tmp_261_fu_934_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_92_fu_1072_p2 = ((tmp_262_fu_1062_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_93_fu_1200_p2 = ((tmp_263_fu_1190_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_94_fu_1328_p2 = ((tmp_264_fu_1318_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_95_fu_1456_p2 = ((tmp_265_fu_1446_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_96_fu_1576_p2 = ((tmp_266_fu_1566_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_97_fu_1696_p2 = ((tmp_267_fu_1686_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_98_fu_1816_p2 = ((tmp_268_fu_1806_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_99_fu_1936_p2 = ((tmp_269_fu_1926_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_560_p2 = ((tmp_258_fu_550_p4 == 6'd0) ? 1'b1 : 1'b0);

assign in_data_7_fu_362_p4 = {{layer21_out_dout[31:16]}};

assign in_data_8_fu_372_p4 = {{layer21_out_dout[47:32]}};

assign in_data_9_fu_382_p4 = {{layer21_out_dout[63:48]}};

assign in_data_fu_290_p1 = layer21_out_dout[15:0];

assign layer8_out_din = {{{{{{{{{{{{{{{{select_ln51_90_reg_2595}, {select_ln51_89_reg_2590}}, {select_ln51_88_reg_2585}}, {select_ln51_87_reg_2580}}, {select_ln51_86_reg_2575}}, {select_ln51_85_reg_2570}}, {select_ln51_84_reg_2565}}, {select_ln51_reg_2560}}, {out_data_33_reg_2555}}, {out_data_31_reg_2550}}, {out_data_29_reg_2545}}, {out_data_27_reg_2540}}, {out_data_25_reg_2535}}, {out_data_23_reg_2530}}, {out_data_21_reg_2525}}, {out_data_19_reg_2520}};

assign or_ln52_100_fu_2024_p2 = (tmp_669_fu_2008_p3 | tmp_612_fu_346_p3);

assign or_ln52_101_fu_2144_p2 = (tmp_673_fu_2128_p3 | tmp_613_fu_354_p3);

assign or_ln52_102_fu_2272_p2 = (tmp_679_fu_2264_p3 | tmp_677_fu_2248_p3);

assign or_ln52_103_fu_2400_p2 = (tmp_684_fu_2392_p3 | tmp_682_fu_2376_p3);

assign or_ln52_174_fu_588_p2 = (xor_ln52_fu_582_p2 | tmp_616_fu_566_p3);

assign or_ln52_175_fu_716_p2 = (xor_ln52_89_fu_710_p2 | tmp_621_fu_694_p3);

assign or_ln52_176_fu_844_p2 = (xor_ln52_90_fu_838_p2 | tmp_626_fu_822_p3);

assign or_ln52_177_fu_972_p2 = (xor_ln52_91_fu_966_p2 | tmp_631_fu_950_p3);

assign or_ln52_178_fu_1100_p2 = (xor_ln52_92_fu_1094_p2 | tmp_636_fu_1078_p3);

assign or_ln52_179_fu_1228_p2 = (xor_ln52_93_fu_1222_p2 | tmp_641_fu_1206_p3);

assign or_ln52_180_fu_1356_p2 = (xor_ln52_94_fu_1350_p2 | tmp_646_fu_1334_p3);

assign or_ln52_181_fu_1484_p2 = (xor_ln52_95_fu_1478_p2 | tmp_651_fu_1462_p3);

assign or_ln52_182_fu_1604_p2 = (xor_ln52_96_fu_1598_p2 | tmp_655_fu_1582_p3);

assign or_ln52_183_fu_1724_p2 = (xor_ln52_97_fu_1718_p2 | tmp_659_fu_1702_p3);

assign or_ln52_184_fu_1844_p2 = (xor_ln52_98_fu_1838_p2 | tmp_663_fu_1822_p3);

assign or_ln52_185_fu_1964_p2 = (xor_ln52_99_fu_1958_p2 | tmp_667_fu_1942_p3);

assign or_ln52_186_fu_2084_p2 = (xor_ln52_100_fu_2078_p2 | tmp_671_fu_2062_p3);

assign or_ln52_187_fu_2204_p2 = (xor_ln52_101_fu_2198_p2 | tmp_675_fu_2182_p3);

assign or_ln52_188_fu_2332_p2 = (xor_ln52_102_fu_2326_p2 | tmp_680_fu_2310_p3);

assign or_ln52_189_fu_2460_p2 = (xor_ln52_103_fu_2454_p2 | tmp_685_fu_2438_p3);

assign or_ln52_89_fu_656_p2 = (tmp_620_fu_648_p3 | tmp_618_fu_632_p3);

assign or_ln52_90_fu_784_p2 = (tmp_625_fu_776_p3 | tmp_623_fu_760_p3);

assign or_ln52_91_fu_912_p2 = (tmp_630_fu_904_p3 | tmp_628_fu_888_p3);

assign or_ln52_92_fu_1040_p2 = (tmp_635_fu_1032_p3 | tmp_633_fu_1016_p3);

assign or_ln52_93_fu_1168_p2 = (tmp_640_fu_1160_p3 | tmp_638_fu_1144_p3);

assign or_ln52_94_fu_1296_p2 = (tmp_645_fu_1288_p3 | tmp_643_fu_1272_p3);

assign or_ln52_95_fu_1424_p2 = (tmp_650_fu_1416_p3 | tmp_648_fu_1400_p3);

assign or_ln52_96_fu_1544_p2 = (tmp_653_fu_1528_p3 | tmp_608_fu_314_p3);

assign or_ln52_97_fu_1664_p2 = (tmp_657_fu_1648_p3 | tmp_609_fu_322_p3);

assign or_ln52_98_fu_1784_p2 = (tmp_661_fu_1768_p3 | tmp_610_fu_330_p3);

assign or_ln52_99_fu_1904_p2 = (tmp_665_fu_1888_p3 | tmp_611_fu_338_p3);

assign or_ln52_fu_528_p2 = (trunc_ln52_fu_524_p1 | tmp_614_fu_508_p3);

assign out_data_19_fu_608_p3 = ((icmp_ln51_fu_492_p2[0:0] == 1'b1) ? out_data_fu_600_p3 : 8'd0);

assign out_data_20_fu_728_p3 = ((and_ln52_181_fu_722_p2[0:0] == 1'b1) ? add_ln52_89_fu_672_p2 : 8'd255);

assign out_data_21_fu_736_p3 = ((icmp_ln51_89_fu_616_p2[0:0] == 1'b1) ? out_data_20_fu_728_p3 : 8'd0);

assign out_data_22_fu_856_p3 = ((and_ln52_183_fu_850_p2[0:0] == 1'b1) ? add_ln52_90_fu_800_p2 : 8'd255);

assign out_data_23_fu_864_p3 = ((icmp_ln51_90_fu_744_p2[0:0] == 1'b1) ? out_data_22_fu_856_p3 : 8'd0);

assign out_data_24_fu_984_p3 = ((and_ln52_185_fu_978_p2[0:0] == 1'b1) ? add_ln52_91_fu_928_p2 : 8'd255);

assign out_data_25_fu_992_p3 = ((icmp_ln51_91_fu_872_p2[0:0] == 1'b1) ? out_data_24_fu_984_p3 : 8'd0);

assign out_data_26_fu_1112_p3 = ((and_ln52_187_fu_1106_p2[0:0] == 1'b1) ? add_ln52_92_fu_1056_p2 : 8'd255);

assign out_data_27_fu_1120_p3 = ((icmp_ln51_92_fu_1000_p2[0:0] == 1'b1) ? out_data_26_fu_1112_p3 : 8'd0);

assign out_data_28_fu_1240_p3 = ((and_ln52_189_fu_1234_p2[0:0] == 1'b1) ? add_ln52_93_fu_1184_p2 : 8'd255);

assign out_data_29_fu_1248_p3 = ((icmp_ln51_93_fu_1128_p2[0:0] == 1'b1) ? out_data_28_fu_1240_p3 : 8'd0);

assign out_data_30_fu_1368_p3 = ((and_ln52_191_fu_1362_p2[0:0] == 1'b1) ? add_ln52_94_fu_1312_p2 : 8'd255);

assign out_data_31_fu_1376_p3 = ((icmp_ln51_94_fu_1256_p2[0:0] == 1'b1) ? out_data_30_fu_1368_p3 : 8'd0);

assign out_data_32_fu_1496_p3 = ((and_ln52_193_fu_1490_p2[0:0] == 1'b1) ? add_ln52_95_fu_1440_p2 : 8'd255);

assign out_data_33_fu_1504_p3 = ((icmp_ln51_95_fu_1384_p2[0:0] == 1'b1) ? out_data_32_fu_1496_p3 : 8'd0);

assign out_data_fu_600_p3 = ((and_ln52_179_fu_594_p2[0:0] == 1'b1) ? add_ln52_fu_544_p2 : 8'd255);

assign select_ln51_84_fu_1744_p3 = ((icmp_ln51_97_fu_1632_p2[0:0] == 1'b1) ? select_ln52_76_fu_1736_p3 : 8'd0);

assign select_ln51_85_fu_1864_p3 = ((icmp_ln51_98_fu_1752_p2[0:0] == 1'b1) ? select_ln52_77_fu_1856_p3 : 8'd0);

assign select_ln51_86_fu_1984_p3 = ((icmp_ln51_99_fu_1872_p2[0:0] == 1'b1) ? select_ln52_78_fu_1976_p3 : 8'd0);

assign select_ln51_87_fu_2104_p3 = ((icmp_ln51_100_fu_1992_p2[0:0] == 1'b1) ? select_ln52_79_fu_2096_p3 : 8'd0);

assign select_ln51_88_fu_2224_p3 = ((icmp_ln51_101_fu_2112_p2[0:0] == 1'b1) ? select_ln52_80_fu_2216_p3 : 8'd0);

assign select_ln51_89_fu_2352_p3 = ((icmp_ln51_102_fu_2232_p2[0:0] == 1'b1) ? select_ln52_81_fu_2344_p3 : 8'd0);

assign select_ln51_90_fu_2480_p3 = ((icmp_ln51_103_fu_2360_p2[0:0] == 1'b1) ? select_ln52_82_fu_2472_p3 : 8'd0);

assign select_ln51_fu_1624_p3 = ((icmp_ln51_96_fu_1512_p2[0:0] == 1'b1) ? select_ln52_fu_1616_p3 : 8'd0);

assign select_ln52_76_fu_1736_p3 = ((and_ln52_197_fu_1730_p2[0:0] == 1'b1) ? add_ln52_97_fu_1680_p2 : 8'd255);

assign select_ln52_77_fu_1856_p3 = ((and_ln52_199_fu_1850_p2[0:0] == 1'b1) ? add_ln52_98_fu_1800_p2 : 8'd255);

assign select_ln52_78_fu_1976_p3 = ((and_ln52_201_fu_1970_p2[0:0] == 1'b1) ? add_ln52_99_fu_1920_p2 : 8'd255);

assign select_ln52_79_fu_2096_p3 = ((and_ln52_203_fu_2090_p2[0:0] == 1'b1) ? add_ln52_100_fu_2040_p2 : 8'd255);

assign select_ln52_80_fu_2216_p3 = ((and_ln52_205_fu_2210_p2[0:0] == 1'b1) ? add_ln52_101_fu_2160_p2 : 8'd255);

assign select_ln52_81_fu_2344_p3 = ((and_ln52_207_fu_2338_p2[0:0] == 1'b1) ? add_ln52_102_fu_2288_p2 : 8'd255);

assign select_ln52_82_fu_2472_p3 = ((and_ln52_209_fu_2466_p2[0:0] == 1'b1) ? add_ln52_103_fu_2416_p2 : 8'd255);

assign select_ln52_fu_1616_p3 = ((and_ln52_195_fu_1610_p2[0:0] == 1'b1) ? add_ln52_96_fu_1560_p2 : 8'd255);

assign start_out = real_start;

assign tmp_250_fu_412_p4 = {{layer21_out_dout[111:96]}};

assign tmp_251_fu_422_p4 = {{layer21_out_dout[127:112]}};

assign tmp_252_fu_432_p4 = {{layer21_out_dout[143:128]}};

assign tmp_253_fu_442_p4 = {{layer21_out_dout[159:144]}};

assign tmp_254_fu_452_p4 = {{layer21_out_dout[175:160]}};

assign tmp_255_fu_462_p4 = {{layer21_out_dout[191:176]}};

assign tmp_256_fu_472_p4 = {{layer21_out_dout[207:192]}};

assign tmp_257_fu_482_p4 = {{layer21_out_dout[223:208]}};

assign tmp_258_fu_550_p4 = {{layer21_out_dout[15:10]}};

assign tmp_259_fu_678_p4 = {{layer21_out_dout[31:26]}};

assign tmp_260_fu_806_p4 = {{layer21_out_dout[47:42]}};

assign tmp_261_fu_934_p4 = {{layer21_out_dout[63:58]}};

assign tmp_262_fu_1062_p4 = {{layer21_out_dout[79:74]}};

assign tmp_263_fu_1190_p4 = {{layer21_out_dout[95:90]}};

assign tmp_264_fu_1318_p4 = {{layer21_out_dout[111:106]}};

assign tmp_265_fu_1446_p4 = {{layer21_out_dout[127:122]}};

assign tmp_266_fu_1566_p4 = {{layer21_out_dout[143:138]}};

assign tmp_267_fu_1686_p4 = {{layer21_out_dout[159:154]}};

assign tmp_268_fu_1806_p4 = {{layer21_out_dout[175:170]}};

assign tmp_269_fu_1926_p4 = {{layer21_out_dout[191:186]}};

assign tmp_270_fu_2046_p4 = {{layer21_out_dout[207:202]}};

assign tmp_271_fu_2166_p4 = {{layer21_out_dout[223:218]}};

assign tmp_272_fu_2294_p4 = {{layer21_out_dout[239:234]}};

assign tmp_273_fu_2422_p4 = {{layer21_out_dout[255:250]}};

assign tmp_608_fu_314_p3 = layer21_out_dout[32'd128];

assign tmp_609_fu_322_p3 = layer21_out_dout[32'd144];

assign tmp_610_fu_330_p3 = layer21_out_dout[32'd160];

assign tmp_611_fu_338_p3 = layer21_out_dout[32'd176];

assign tmp_612_fu_346_p3 = layer21_out_dout[32'd192];

assign tmp_613_fu_354_p3 = layer21_out_dout[32'd208];

assign tmp_614_fu_508_p3 = layer21_out_dout[32'd2];

assign tmp_615_fu_516_p3 = layer21_out_dout[32'd1];

assign tmp_616_fu_566_p3 = add_ln52_fu_544_p2[32'd7];

assign tmp_617_fu_574_p3 = layer21_out_dout[32'd9];

assign tmp_618_fu_632_p3 = layer21_out_dout[32'd18];

assign tmp_619_fu_640_p3 = layer21_out_dout[32'd17];

assign tmp_620_fu_648_p3 = layer21_out_dout[32'd16];

assign tmp_621_fu_694_p3 = add_ln52_89_fu_672_p2[32'd7];

assign tmp_622_fu_702_p3 = layer21_out_dout[32'd25];

assign tmp_623_fu_760_p3 = layer21_out_dout[32'd34];

assign tmp_624_fu_768_p3 = layer21_out_dout[32'd33];

assign tmp_625_fu_776_p3 = layer21_out_dout[32'd32];

assign tmp_626_fu_822_p3 = add_ln52_90_fu_800_p2[32'd7];

assign tmp_627_fu_830_p3 = layer21_out_dout[32'd41];

assign tmp_628_fu_888_p3 = layer21_out_dout[32'd50];

assign tmp_629_fu_896_p3 = layer21_out_dout[32'd49];

assign tmp_630_fu_904_p3 = layer21_out_dout[32'd48];

assign tmp_631_fu_950_p3 = add_ln52_91_fu_928_p2[32'd7];

assign tmp_632_fu_958_p3 = layer21_out_dout[32'd57];

assign tmp_633_fu_1016_p3 = layer21_out_dout[32'd66];

assign tmp_634_fu_1024_p3 = layer21_out_dout[32'd65];

assign tmp_635_fu_1032_p3 = layer21_out_dout[32'd64];

assign tmp_636_fu_1078_p3 = add_ln52_92_fu_1056_p2[32'd7];

assign tmp_637_fu_1086_p3 = layer21_out_dout[32'd73];

assign tmp_638_fu_1144_p3 = layer21_out_dout[32'd82];

assign tmp_639_fu_1152_p3 = layer21_out_dout[32'd81];

assign tmp_640_fu_1160_p3 = layer21_out_dout[32'd80];

assign tmp_641_fu_1206_p3 = add_ln52_93_fu_1184_p2[32'd7];

assign tmp_642_fu_1214_p3 = layer21_out_dout[32'd89];

assign tmp_643_fu_1272_p3 = layer21_out_dout[32'd98];

assign tmp_644_fu_1280_p3 = layer21_out_dout[32'd97];

assign tmp_645_fu_1288_p3 = layer21_out_dout[32'd96];

assign tmp_646_fu_1334_p3 = add_ln52_94_fu_1312_p2[32'd7];

assign tmp_647_fu_1342_p3 = layer21_out_dout[32'd105];

assign tmp_648_fu_1400_p3 = layer21_out_dout[32'd114];

assign tmp_649_fu_1408_p3 = layer21_out_dout[32'd113];

assign tmp_650_fu_1416_p3 = layer21_out_dout[32'd112];

assign tmp_651_fu_1462_p3 = add_ln52_95_fu_1440_p2[32'd7];

assign tmp_652_fu_1470_p3 = layer21_out_dout[32'd121];

assign tmp_653_fu_1528_p3 = layer21_out_dout[32'd130];

assign tmp_654_fu_1536_p3 = layer21_out_dout[32'd129];

assign tmp_655_fu_1582_p3 = add_ln52_96_fu_1560_p2[32'd7];

assign tmp_656_fu_1590_p3 = layer21_out_dout[32'd137];

assign tmp_657_fu_1648_p3 = layer21_out_dout[32'd146];

assign tmp_658_fu_1656_p3 = layer21_out_dout[32'd145];

assign tmp_659_fu_1702_p3 = add_ln52_97_fu_1680_p2[32'd7];

assign tmp_660_fu_1710_p3 = layer21_out_dout[32'd153];

assign tmp_661_fu_1768_p3 = layer21_out_dout[32'd162];

assign tmp_662_fu_1776_p3 = layer21_out_dout[32'd161];

assign tmp_663_fu_1822_p3 = add_ln52_98_fu_1800_p2[32'd7];

assign tmp_664_fu_1830_p3 = layer21_out_dout[32'd169];

assign tmp_665_fu_1888_p3 = layer21_out_dout[32'd178];

assign tmp_666_fu_1896_p3 = layer21_out_dout[32'd177];

assign tmp_667_fu_1942_p3 = add_ln52_99_fu_1920_p2[32'd7];

assign tmp_668_fu_1950_p3 = layer21_out_dout[32'd185];

assign tmp_669_fu_2008_p3 = layer21_out_dout[32'd194];

assign tmp_670_fu_2016_p3 = layer21_out_dout[32'd193];

assign tmp_671_fu_2062_p3 = add_ln52_100_fu_2040_p2[32'd7];

assign tmp_672_fu_2070_p3 = layer21_out_dout[32'd201];

assign tmp_673_fu_2128_p3 = layer21_out_dout[32'd210];

assign tmp_674_fu_2136_p3 = layer21_out_dout[32'd209];

assign tmp_675_fu_2182_p3 = add_ln52_101_fu_2160_p2[32'd7];

assign tmp_676_fu_2190_p3 = layer21_out_dout[32'd217];

assign tmp_677_fu_2248_p3 = layer21_out_dout[32'd226];

assign tmp_678_fu_2256_p3 = layer21_out_dout[32'd225];

assign tmp_679_fu_2264_p3 = layer21_out_dout[32'd224];

assign tmp_680_fu_2310_p3 = add_ln52_102_fu_2288_p2[32'd7];

assign tmp_681_fu_2318_p3 = layer21_out_dout[32'd233];

assign tmp_682_fu_2376_p3 = layer21_out_dout[32'd242];

assign tmp_683_fu_2384_p3 = layer21_out_dout[32'd241];

assign tmp_684_fu_2392_p3 = layer21_out_dout[32'd240];

assign tmp_685_fu_2438_p3 = add_ln52_103_fu_2416_p2[32'd7];

assign tmp_686_fu_2446_p3 = layer21_out_dout[32'd249];

assign tmp_fu_392_p4 = {{layer21_out_dout[79:64]}};

assign tmp_s_fu_402_p4 = {{layer21_out_dout[95:80]}};

assign trunc_ln44_2_fu_304_p4 = {{layer21_out_dout[255:240]}};

assign trunc_ln44_s_fu_294_p4 = {{layer21_out_dout[239:224]}};

assign trunc_ln4_fu_498_p4 = {{layer21_out_dout[9:2]}};

assign trunc_ln52_100_fu_2366_p4 = {{layer21_out_dout[249:242]}};

assign trunc_ln52_87_fu_750_p4 = {{layer21_out_dout[41:34]}};

assign trunc_ln52_88_fu_878_p4 = {{layer21_out_dout[57:50]}};

assign trunc_ln52_89_fu_1006_p4 = {{layer21_out_dout[73:66]}};

assign trunc_ln52_90_fu_1134_p4 = {{layer21_out_dout[89:82]}};

assign trunc_ln52_91_fu_1262_p4 = {{layer21_out_dout[105:98]}};

assign trunc_ln52_92_fu_1390_p4 = {{layer21_out_dout[121:114]}};

assign trunc_ln52_93_fu_1518_p4 = {{layer21_out_dout[137:130]}};

assign trunc_ln52_94_fu_1638_p4 = {{layer21_out_dout[153:146]}};

assign trunc_ln52_95_fu_1758_p4 = {{layer21_out_dout[169:162]}};

assign trunc_ln52_96_fu_1878_p4 = {{layer21_out_dout[185:178]}};

assign trunc_ln52_97_fu_1998_p4 = {{layer21_out_dout[201:194]}};

assign trunc_ln52_98_fu_2118_p4 = {{layer21_out_dout[217:210]}};

assign trunc_ln52_99_fu_2238_p4 = {{layer21_out_dout[233:226]}};

assign trunc_ln52_fu_524_p1 = layer21_out_dout[0:0];

assign trunc_ln52_s_fu_622_p4 = {{layer21_out_dout[25:18]}};

assign xor_ln52_100_fu_2078_p2 = (tmp_672_fu_2070_p3 ^ 1'd1);

assign xor_ln52_101_fu_2198_p2 = (tmp_676_fu_2190_p3 ^ 1'd1);

assign xor_ln52_102_fu_2326_p2 = (tmp_681_fu_2318_p3 ^ 1'd1);

assign xor_ln52_103_fu_2454_p2 = (tmp_686_fu_2446_p3 ^ 1'd1);

assign xor_ln52_89_fu_710_p2 = (tmp_622_fu_702_p3 ^ 1'd1);

assign xor_ln52_90_fu_838_p2 = (tmp_627_fu_830_p3 ^ 1'd1);

assign xor_ln52_91_fu_966_p2 = (tmp_632_fu_958_p3 ^ 1'd1);

assign xor_ln52_92_fu_1094_p2 = (tmp_637_fu_1086_p3 ^ 1'd1);

assign xor_ln52_93_fu_1222_p2 = (tmp_642_fu_1214_p3 ^ 1'd1);

assign xor_ln52_94_fu_1350_p2 = (tmp_647_fu_1342_p3 ^ 1'd1);

assign xor_ln52_95_fu_1478_p2 = (tmp_652_fu_1470_p3 ^ 1'd1);

assign xor_ln52_96_fu_1598_p2 = (tmp_656_fu_1590_p3 ^ 1'd1);

assign xor_ln52_97_fu_1718_p2 = (tmp_660_fu_1710_p3 ^ 1'd1);

assign xor_ln52_98_fu_1838_p2 = (tmp_664_fu_1830_p3 ^ 1'd1);

assign xor_ln52_99_fu_1958_p2 = (tmp_668_fu_1950_p3 ^ 1'd1);

assign xor_ln52_fu_582_p2 = (tmp_617_fu_574_p3 ^ 1'd1);

assign zext_ln52_100_fu_2036_p1 = and_ln52_202_fu_2030_p2;

assign zext_ln52_101_fu_2156_p1 = and_ln52_204_fu_2150_p2;

assign zext_ln52_102_fu_2284_p1 = and_ln52_206_fu_2278_p2;

assign zext_ln52_103_fu_2412_p1 = and_ln52_208_fu_2406_p2;

assign zext_ln52_89_fu_668_p1 = and_ln52_180_fu_662_p2;

assign zext_ln52_90_fu_796_p1 = and_ln52_182_fu_790_p2;

assign zext_ln52_91_fu_924_p1 = and_ln52_184_fu_918_p2;

assign zext_ln52_92_fu_1052_p1 = and_ln52_186_fu_1046_p2;

assign zext_ln52_93_fu_1180_p1 = and_ln52_188_fu_1174_p2;

assign zext_ln52_94_fu_1308_p1 = and_ln52_190_fu_1302_p2;

assign zext_ln52_95_fu_1436_p1 = and_ln52_192_fu_1430_p2;

assign zext_ln52_96_fu_1556_p1 = and_ln52_194_fu_1550_p2;

assign zext_ln52_97_fu_1676_p1 = and_ln52_196_fu_1670_p2;

assign zext_ln52_98_fu_1796_p1 = and_ln52_198_fu_1790_p2;

assign zext_ln52_99_fu_1916_p1 = and_ln52_200_fu_1910_p2;

assign zext_ln52_fu_540_p1 = and_ln52_fu_534_p2;

endmodule //myproject_relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_s
