// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps
module myproject_dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_s_w14_ROM_0iy (
    address0, ce0, q0, 
    reset, clk);

parameter DataWidth = 1344;
parameter AddressWidth = 6;
parameter AddressRange = 60;
 
input[AddressWidth-1:0] address0;
input ce0;
output reg[DataWidth-1:0] q0;

input reset;
input clk;

 
(* rom_style = "block" *)reg [DataWidth-1:0] rom0[0:AddressRange-1];


initial begin
     
    $readmemh("/home/mohamed/Nile_intern/Tasks/Mobilenet_project/test/lenet_project/lenet5_hls/myproject_prj/solution1/syn/verilog/myproject_dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_s_w14_ROM_0iy.dat", rom0);
end

  
always @(posedge clk) 
begin 
    if (ce0) 
    begin
        q0 <= rom0[address0];
    end
end


endmodule

