// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer4_out_dout,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer4_out_empty_n,
        layer4_out_read,
        layer5_out_din,
        layer5_out_num_data_valid,
        layer5_out_fifo_cap,
        layer5_out_full_n,
        layer5_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [47:0] layer4_out_dout;
input  [10:0] layer4_out_num_data_valid;
input  [10:0] layer4_out_fifo_cap;
input   layer4_out_empty_n;
output   layer4_out_read;
output  [47:0] layer5_out_din;
input  [8:0] layer5_out_num_data_valid;
input  [8:0] layer5_out_fifo_cap;
input   layer5_out_full_n;
output   layer5_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer4_out_read;
reg layer5_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
reg   [0:0] icmp_ln55_reg_1686;
reg   [0:0] icmp_ln55_reg_1686_pp0_iter2_reg;
reg   [0:0] and_ln55_1_reg_1780;
reg   [0:0] and_ln55_1_reg_1780_pp0_iter2_reg;
reg    ap_predicate_op265_write_state4;
reg    ap_block_state4_pp0_stage0_iter3;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln109_fu_198_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [31:0] sY;
reg   [31:0] pY;
reg   [31:0] pX;
reg   [31:0] sX;
reg   [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3;
reg   [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2;
reg   [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1;
reg   [7:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_7;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_6;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_5;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_4;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_3;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_2;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_1;
reg   [7:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_5_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_5_we0;
wire   [7:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_5_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_4_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_4_we0;
wire   [7:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_4_d0;
wire   [7:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_4_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_3_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_3_we0;
wire   [7:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_3_d0;
wire   [7:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_3_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_2_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_2_we0;
wire   [7:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_2_d0;
wire   [7:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_2_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_1_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_1_we0;
wire   [7:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_1_d0;
wire   [7:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_1_q0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_ce0;
reg    void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_we0;
wire   [7:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_d0;
wire   [7:0] void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_q0;
reg    layer4_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer5_out_blk_n;
reg   [0:0] icmp_ln109_reg_1682;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln55_fu_214_p2;
reg   [0:0] icmp_ln55_reg_1686_pp0_iter1_reg;
wire   [0:0] icmp_ln55_2_fu_228_p2;
reg   [0:0] icmp_ln55_2_reg_1690;
wire   [0:0] icmp_ln55_3_fu_234_p2;
reg   [0:0] icmp_ln55_3_reg_1695;
wire   [0:0] icmp_ln76_fu_246_p2;
reg   [0:0] icmp_ln76_reg_1700;
wire   [0:0] icmp_ln80_fu_300_p2;
reg   [0:0] icmp_ln80_reg_1704;
wire   [7:0] trunc_ln115_fu_323_p1;
reg   [7:0] trunc_ln115_reg_1708;
reg   [7:0] trunc_ln115_4_reg_1714;
reg   [7:0] trunc_ln115_5_reg_1720;
reg   [7:0] p_s_reg_1726;
reg   [7:0] p_1_reg_1732;
reg   [7:0] p_2_reg_1738;
reg   [7:0] p_5_reg_1744;
reg   [7:0] p_6_reg_1750;
reg   [7:0] p_7_reg_1756;
reg   [7:0] p_8_reg_1762;
reg   [7:0] p_9_reg_1768;
reg   [7:0] p_0_reg_1774;
wire   [0:0] and_ln55_1_fu_451_p2;
wire   [1:0] trunc_ln51_fu_457_p1;
reg   [1:0] trunc_ln51_reg_1784;
reg   [1:0] tmp_s_reg_1789;
reg   [1:0] tmp_506_reg_1794;
reg   [1:0] tmp_507_reg_1799;
reg   [1:0] tmp_508_reg_1804;
reg   [1:0] tmp_509_reg_1809;
wire   [7:0] res_pack_fu_811_p3;
reg   [7:0] res_pack_reg_1814;
wire   [7:0] res_pack_1_fu_980_p3;
reg   [7:0] res_pack_1_reg_1819;
wire   [7:0] res_pack_2_fu_1149_p3;
reg   [7:0] res_pack_2_reg_1824;
wire   [7:0] res_pack_3_fu_1318_p3;
reg   [7:0] res_pack_3_reg_1829;
wire   [7:0] res_pack_4_fu_1487_p3;
reg   [7:0] res_pack_4_reg_1834;
wire   [7:0] res_pack_5_fu_1656_p3;
reg   [7:0] res_pack_5_reg_1839;
reg   [31:0] ap_phi_mux_storemerge_phi_fu_183_p4;
wire   [31:0] add_ln86_fu_529_p2;
reg   [31:0] ap_phi_reg_pp0_iter1_storemerge_reg_179;
wire   [31:0] ap_phi_reg_pp0_iter0_storemerge_reg_179;
wire   [31:0] add_ln80_fu_294_p2;
wire   [31:0] add_ln76_fu_240_p2;
wire   [31:0] add_ln91_fu_266_p2;
reg   [9:0] indvar_flatten_fu_162;
wire   [9:0] add_ln109_fu_204_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_indvar_flatten_load;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] select_ln91_fu_258_p3;
wire   [0:0] and_ln55_fu_447_p2;
wire   [0:0] icmp_ln55_1_fu_441_p2;
wire   [0:0] icmp_ln86_fu_515_p2;
wire   [31:0] select_ln86_fu_521_p3;
wire   [9:0] pool_window_fu_650_p3;
wire   [8:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_fu_664_p1;
wire   [8:0] p_27_cast_fu_661_p1;
wire   [8:0] empty_fu_672_p2;
wire   [9:0] zext_ln51_7_fu_678_p1;
wire   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_40_fu_668_p1;
wire   [9:0] add_ln51_fu_682_p2;
wire   [1:0] trunc_ln51_11_fu_703_p1;
wire   [11:0] shl_ln_fu_688_p3;
wire   [11:0] zext_ln42_fu_657_p1;
wire   [3:0] trunc_ln51_2_fu_707_p3;
wire   [3:0] trunc_ln51_1_fu_696_p3;
wire   [11:0] sum_fu_715_p2;
wire   [3:0] add_ln51_11_fu_721_p2;
wire   [0:0] tmp_fu_737_p3;
wire   [0:0] tmp_1287_fu_753_p3;
wire   [0:0] or_ln68_fu_769_p2;
wire   [0:0] tmp_1286_fu_745_p3;
wire   [0:0] and_ln68_fu_775_p2;
wire   [7:0] trunc_ln6_fu_727_p4;
wire   [7:0] zext_ln68_fu_781_p1;
wire   [7:0] add_ln68_fu_785_p2;
wire   [0:0] tmp_1289_fu_791_p3;
wire   [0:0] tmp_1288_fu_761_p3;
wire   [0:0] xor_ln68_fu_799_p2;
wire   [0:0] and_ln68_1_fu_805_p2;
wire   [9:0] pool_window_1_fu_819_p3;
wire   [8:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_fu_833_p1;
wire   [8:0] p_28_cast_fu_830_p1;
wire   [8:0] empty_87_fu_841_p2;
wire   [9:0] zext_ln51_8_fu_847_p1;
wire   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_41_fu_837_p1;
wire   [9:0] add_ln51_6_fu_851_p2;
wire   [1:0] trunc_ln51_12_fu_872_p1;
wire   [11:0] shl_ln51_1_fu_857_p3;
wire   [11:0] zext_ln42_1_fu_826_p1;
wire   [3:0] trunc_ln51_3_fu_876_p3;
wire   [3:0] trunc_ln7_fu_865_p3;
wire   [11:0] sum_1_fu_884_p2;
wire   [3:0] add_ln51_15_fu_890_p2;
wire   [0:0] tmp_1290_fu_906_p3;
wire   [0:0] tmp_1292_fu_922_p3;
wire   [0:0] or_ln68_1_fu_938_p2;
wire   [0:0] tmp_1291_fu_914_p3;
wire   [0:0] and_ln68_2_fu_944_p2;
wire   [7:0] trunc_ln68_1_fu_896_p4;
wire   [7:0] zext_ln68_1_fu_950_p1;
wire   [7:0] add_ln68_1_fu_954_p2;
wire   [0:0] tmp_1294_fu_960_p3;
wire   [0:0] tmp_1293_fu_930_p3;
wire   [0:0] xor_ln68_1_fu_968_p2;
wire   [0:0] and_ln68_3_fu_974_p2;
wire   [9:0] pool_window_2_fu_988_p3;
wire   [8:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_fu_1002_p1;
wire   [8:0] p_29_cast_fu_999_p1;
wire   [8:0] empty_88_fu_1010_p2;
wire   [9:0] zext_ln51_9_fu_1016_p1;
wire   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_42_fu_1006_p1;
wire   [9:0] add_ln51_8_fu_1020_p2;
wire   [1:0] trunc_ln51_13_fu_1041_p1;
wire   [11:0] shl_ln51_2_fu_1026_p3;
wire   [11:0] zext_ln42_2_fu_995_p1;
wire   [3:0] trunc_ln51_5_fu_1045_p3;
wire   [3:0] trunc_ln51_4_fu_1034_p3;
wire   [11:0] sum_2_fu_1053_p2;
wire   [3:0] add_ln51_17_fu_1059_p2;
wire   [0:0] tmp_1295_fu_1075_p3;
wire   [0:0] tmp_1297_fu_1091_p3;
wire   [0:0] or_ln68_2_fu_1107_p2;
wire   [0:0] tmp_1296_fu_1083_p3;
wire   [0:0] and_ln68_4_fu_1113_p2;
wire   [7:0] trunc_ln68_2_fu_1065_p4;
wire   [7:0] zext_ln68_2_fu_1119_p1;
wire   [7:0] add_ln68_2_fu_1123_p2;
wire   [0:0] tmp_1299_fu_1129_p3;
wire   [0:0] tmp_1298_fu_1099_p3;
wire   [0:0] xor_ln68_2_fu_1137_p2;
wire   [0:0] and_ln68_5_fu_1143_p2;
wire   [9:0] pool_window_3_fu_1157_p3;
wire   [8:0] void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_fu_1171_p1;
wire   [8:0] p_30_cast_fu_1168_p1;
wire   [8:0] empty_89_fu_1179_p2;
wire   [9:0] zext_ln51_10_fu_1185_p1;
wire   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_43_fu_1175_p1;
wire   [9:0] add_ln51_10_fu_1189_p2;
wire   [1:0] trunc_ln51_14_fu_1210_p1;
wire   [11:0] shl_ln51_3_fu_1195_p3;
wire   [11:0] zext_ln42_3_fu_1164_p1;
wire   [3:0] trunc_ln51_s_fu_1214_p3;
wire   [3:0] trunc_ln51_6_fu_1203_p3;
wire   [11:0] sum_3_fu_1222_p2;
wire   [3:0] add_ln51_19_fu_1228_p2;
wire   [0:0] tmp_1300_fu_1244_p3;
wire   [0:0] tmp_1302_fu_1260_p3;
wire   [0:0] or_ln68_3_fu_1276_p2;
wire   [0:0] tmp_1301_fu_1252_p3;
wire   [0:0] and_ln68_6_fu_1282_p2;
wire   [7:0] trunc_ln68_3_fu_1234_p4;
wire   [7:0] zext_ln68_3_fu_1288_p1;
wire   [7:0] add_ln68_3_fu_1292_p2;
wire   [0:0] tmp_1304_fu_1298_p3;
wire   [0:0] tmp_1303_fu_1268_p3;
wire   [0:0] xor_ln68_3_fu_1306_p2;
wire   [0:0] and_ln68_7_fu_1312_p2;
wire   [9:0] pool_window_4_fu_1326_p3;
wire   [8:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_44_fu_1340_p1;
wire   [8:0] p_31_cast_fu_1337_p1;
wire   [8:0] empty_90_fu_1348_p2;
wire   [9:0] zext_ln51_11_fu_1354_p1;
wire   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_45_fu_1344_p1;
wire   [9:0] add_ln51_12_fu_1358_p2;
wire   [1:0] trunc_ln51_15_fu_1379_p1;
wire   [11:0] shl_ln51_4_fu_1364_p3;
wire   [11:0] zext_ln42_4_fu_1333_p1;
wire   [3:0] trunc_ln51_8_fu_1383_p3;
wire   [3:0] trunc_ln51_7_fu_1372_p3;
wire   [11:0] sum_4_fu_1391_p2;
wire   [3:0] add_ln51_21_fu_1397_p2;
wire   [0:0] tmp_1305_fu_1413_p3;
wire   [0:0] tmp_1307_fu_1429_p3;
wire   [0:0] or_ln68_4_fu_1445_p2;
wire   [0:0] tmp_1306_fu_1421_p3;
wire   [0:0] and_ln68_8_fu_1451_p2;
wire   [7:0] trunc_ln68_4_fu_1403_p4;
wire   [7:0] zext_ln68_4_fu_1457_p1;
wire   [7:0] add_ln68_4_fu_1461_p2;
wire   [0:0] tmp_1309_fu_1467_p3;
wire   [0:0] tmp_1308_fu_1437_p3;
wire   [0:0] xor_ln68_4_fu_1475_p2;
wire   [0:0] and_ln68_9_fu_1481_p2;
wire   [9:0] pool_window_5_fu_1495_p3;
wire   [8:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_46_fu_1509_p1;
wire   [8:0] p_0_cast_fu_1506_p1;
wire   [8:0] empty_91_fu_1517_p2;
wire   [9:0] zext_ln51_12_fu_1523_p1;
wire   [9:0] p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_47_fu_1513_p1;
wire   [9:0] add_ln51_14_fu_1527_p2;
wire   [1:0] trunc_ln51_16_fu_1548_p1;
wire   [11:0] shl_ln51_5_fu_1533_p3;
wire   [11:0] zext_ln42_5_fu_1502_p1;
wire   [3:0] trunc_ln51_10_fu_1552_p3;
wire   [3:0] trunc_ln51_9_fu_1541_p3;
wire   [11:0] sum_5_fu_1560_p2;
wire   [3:0] add_ln51_23_fu_1566_p2;
wire   [0:0] tmp_1310_fu_1582_p3;
wire   [0:0] tmp_1312_fu_1598_p3;
wire   [0:0] or_ln68_5_fu_1614_p2;
wire   [0:0] tmp_1311_fu_1590_p3;
wire   [0:0] and_ln68_10_fu_1620_p2;
wire   [7:0] trunc_ln68_5_fu_1572_p4;
wire   [7:0] zext_ln68_5_fu_1626_p1;
wire   [7:0] add_ln68_5_fu_1630_p2;
wire   [0:0] tmp_1314_fu_1636_p3;
wire   [0:0] tmp_1313_fu_1606_p3;
wire   [0:0] xor_ln68_5_fu_1644_p2;
wire   [0:0] and_ln68_11_fu_1650_p2;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_290;
reg    ap_condition_288;
reg    ap_condition_358;
reg    ap_condition_314;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
#0 sY = 32'd0;
#0 pY = 32'd0;
#0 pX = 32'd0;
#0 sX = 32'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 = 8'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2 = 8'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1 = 8'd0;
#0 void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_7 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_6 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_5 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_4 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_3 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_2 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_1 = 8'd0;
#0 p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap = 8'd0;
end

myproject_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_s_void_pfYi #(
    .DataWidth( 8 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(5'd23),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_5_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_5_we0),
    .d0(trunc_ln115_fu_323_p1),
    .q0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_5_q0)
);

myproject_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_s_void_pfYi #(
    .DataWidth( 8 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(5'd23),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_4_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_4_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_4_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_4_q0)
);

myproject_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_s_void_pfYi #(
    .DataWidth( 8 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(5'd23),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_3_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_3_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_3_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_3_q0)
);

myproject_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_s_void_pfYi #(
    .DataWidth( 8 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(5'd23),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_2_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_2_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_2_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_2_q0)
);

myproject_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_s_void_pfYi #(
    .DataWidth( 8 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(5'd23),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_1_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_1_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_1_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_1_q0)
);

myproject_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_s_void_pfYi #(
    .DataWidth( 8 ),
    .AddressRange( 24 ),
    .AddressWidth( 5 ))
void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(5'd23),
    .ce0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_ce0),
    .we0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_we0),
    .d0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_d0),
    .q0(void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_q0)
);

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_288)) begin
        if ((1'b1 == ap_condition_290)) begin
            ap_phi_reg_pp0_iter1_storemerge_reg_179 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_storemerge_reg_179 <= ap_phi_reg_pp0_iter0_storemerge_reg_179;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_288)) begin
        if ((icmp_ln109_fu_198_p2 == 1'd0)) begin
            indvar_flatten_fu_162 <= add_ln109_fu_204_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_162 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_358)) begin
        if ((icmp_ln76_fu_246_p2 == 1'd1)) begin
            pX <= 32'd0;
        end else if ((icmp_ln76_fu_246_p2 == 1'd0)) begin
            pX <= add_ln76_fu_240_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_314)) begin
        if ((icmp_ln80_fu_300_p2 == 1'd1)) begin
            pY <= 32'd0;
        end else if ((icmp_ln80_fu_300_p2 == 1'd0)) begin
            pY <= add_ln80_fu_294_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_358)) begin
        if ((icmp_ln76_fu_246_p2 == 1'd1)) begin
            sX <= 32'd0;
        end else if ((icmp_ln76_fu_246_p2 == 1'd0)) begin
            sX <= add_ln91_fu_266_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln55_reg_1686 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln55_1_reg_1780 <= and_ln55_1_fu_451_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln55_1_reg_1780_pp0_iter2_reg <= and_ln55_1_reg_1780;
        icmp_ln55_reg_1686_pp0_iter2_reg <= icmp_ln55_reg_1686_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln109_reg_1682 <= icmp_ln109_fu_198_p2;
        icmp_ln55_reg_1686_pp0_iter1_reg <= icmp_ln55_reg_1686;
        p_0_reg_1774 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_q0;
        p_1_reg_1732 <= {{layer4_out_dout[23:16]}};
        p_2_reg_1738 <= {{layer4_out_dout[31:24]}};
        p_5_reg_1744 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_5_q0;
        p_6_reg_1750 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_4_q0;
        p_7_reg_1756 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_3_q0;
        p_8_reg_1762 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_2_q0;
        p_9_reg_1768 <= void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_1_q0;
        p_s_reg_1726 <= {{layer4_out_dout[15:8]}};
        trunc_ln115_4_reg_1714 <= {{layer4_out_dout[39:32]}};
        trunc_ln115_5_reg_1720 <= {{layer4_out_dout[47:40]}};
        trunc_ln115_reg_1708 <= trunc_ln115_fu_323_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_198_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln55_fu_214_p2 == 1'd1))) begin
        icmp_ln55_2_reg_1690 <= icmp_ln55_2_fu_228_p2;
        icmp_ln55_3_reg_1695 <= icmp_ln55_3_fu_234_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_198_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln55_reg_1686 <= icmp_ln55_fu_214_p2;
        icmp_ln76_reg_1700 <= icmp_ln76_fu_246_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln109_fu_198_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln76_fu_246_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln80_reg_1704 <= icmp_ln80_fu_300_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap <= trunc_ln115_5_reg_1720;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_1 <= trunc_ln115_4_reg_1714;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_2 <= p_2_reg_1738;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_3 <= p_1_reg_1732;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_4 <= p_s_reg_1726;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_5 <= trunc_ln115_reg_1708;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_6 <= p_0_reg_1774;
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_7 <= p_9_reg_1768;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel <= p_8_reg_1762;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1 <= p_7_reg_1756;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2 <= p_6_reg_1750;
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 <= p_5_reg_1744;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln55_1_reg_1780) & (icmp_ln55_reg_1686_pp0_iter1_reg == 1'd1))) begin
        res_pack_1_reg_1819 <= res_pack_1_fu_980_p3;
        res_pack_2_reg_1824 <= res_pack_2_fu_1149_p3;
        res_pack_3_reg_1829 <= res_pack_3_fu_1318_p3;
        res_pack_4_reg_1834 <= res_pack_4_fu_1487_p3;
        res_pack_5_reg_1839 <= res_pack_5_fu_1656_p3;
        res_pack_reg_1814 <= res_pack_fu_811_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln76_reg_1700 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sY <= ap_phi_mux_storemerge_phi_fu_183_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln55_1_fu_451_p2) & (icmp_ln55_reg_1686 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_506_reg_1794 <= {{layer4_out_dout[17:16]}};
        tmp_507_reg_1799 <= {{layer4_out_dout[25:24]}};
        tmp_508_reg_1804 <= {{layer4_out_dout[33:32]}};
        tmp_509_reg_1809 <= {{layer4_out_dout[41:40]}};
        tmp_s_reg_1789 <= {{layer4_out_dout[9:8]}};
        trunc_ln51_reg_1784 <= trunc_ln51_fu_457_p1;
    end
end

always @ (*) begin
    if (((icmp_ln109_fu_198_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln80_reg_1704 == 1'd0) & (icmp_ln76_reg_1700 == 1'd1) & (icmp_ln109_reg_1682 == 1'd0))) begin
        ap_phi_mux_storemerge_phi_fu_183_p4 = add_ln86_fu_529_p2;
    end else begin
        ap_phi_mux_storemerge_phi_fu_183_p4 = ap_phi_reg_pp0_iter1_storemerge_reg_179;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_162;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer4_out_blk_n = layer4_out_empty_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer4_out_read = 1'b1;
    end else begin
        layer4_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_predicate_op265_write_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer5_out_blk_n = layer5_out_full_n;
    end else begin
        layer5_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op265_write_state4 == 1'b1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        layer5_out_write = 1'b1;
    end else begin
        layer5_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_1_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_1_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_2_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_2_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_3_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_3_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_4_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_4_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_5_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_5_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_ce0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_we0 = 1'd1;
    end else begin
        void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln109_fu_204_p2 = (ap_sig_allocacmp_indvar_flatten_load + 10'd1);

assign add_ln51_10_fu_1189_p2 = (zext_ln51_10_fu_1185_p1 + p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_43_fu_1175_p1);

assign add_ln51_11_fu_721_p2 = (trunc_ln51_2_fu_707_p3 + trunc_ln51_1_fu_696_p3);

assign add_ln51_12_fu_1358_p2 = (zext_ln51_11_fu_1354_p1 + p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_45_fu_1344_p1);

assign add_ln51_14_fu_1527_p2 = (zext_ln51_12_fu_1523_p1 + p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_47_fu_1513_p1);

assign add_ln51_15_fu_890_p2 = (trunc_ln51_3_fu_876_p3 + trunc_ln7_fu_865_p3);

assign add_ln51_17_fu_1059_p2 = (trunc_ln51_5_fu_1045_p3 + trunc_ln51_4_fu_1034_p3);

assign add_ln51_19_fu_1228_p2 = (trunc_ln51_s_fu_1214_p3 + trunc_ln51_6_fu_1203_p3);

assign add_ln51_21_fu_1397_p2 = (trunc_ln51_8_fu_1383_p3 + trunc_ln51_7_fu_1372_p3);

assign add_ln51_23_fu_1566_p2 = (trunc_ln51_10_fu_1552_p3 + trunc_ln51_9_fu_1541_p3);

assign add_ln51_6_fu_851_p2 = (zext_ln51_8_fu_847_p1 + p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_41_fu_837_p1);

assign add_ln51_8_fu_1020_p2 = (zext_ln51_9_fu_1016_p1 + p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_42_fu_1006_p1);

assign add_ln51_fu_682_p2 = (zext_ln51_7_fu_678_p1 + p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_40_fu_668_p1);

assign add_ln68_1_fu_954_p2 = (trunc_ln68_1_fu_896_p4 + zext_ln68_1_fu_950_p1);

assign add_ln68_2_fu_1123_p2 = (trunc_ln68_2_fu_1065_p4 + zext_ln68_2_fu_1119_p1);

assign add_ln68_3_fu_1292_p2 = (trunc_ln68_3_fu_1234_p4 + zext_ln68_3_fu_1288_p1);

assign add_ln68_4_fu_1461_p2 = (trunc_ln68_4_fu_1403_p4 + zext_ln68_4_fu_1457_p1);

assign add_ln68_5_fu_1630_p2 = (trunc_ln68_5_fu_1572_p4 + zext_ln68_5_fu_1626_p1);

assign add_ln68_fu_785_p2 = (trunc_ln6_fu_727_p4 + zext_ln68_fu_781_p1);

assign add_ln76_fu_240_p2 = (pX + 32'd1);

assign add_ln80_fu_294_p2 = (pY + 32'd1);

assign add_ln86_fu_529_p2 = (sY + select_ln86_fu_521_p3);

assign add_ln91_fu_266_p2 = (sX + select_ln91_fu_258_p3);

assign and_ln55_1_fu_451_p2 = (icmp_ln55_1_fu_441_p2 & and_ln55_fu_447_p2);

assign and_ln55_fu_447_p2 = (icmp_ln55_3_reg_1695 & icmp_ln55_2_reg_1690);

assign and_ln68_10_fu_1620_p2 = (tmp_1311_fu_1590_p3 & or_ln68_5_fu_1614_p2);

assign and_ln68_11_fu_1650_p2 = (xor_ln68_5_fu_1644_p2 & tmp_1313_fu_1606_p3);

assign and_ln68_1_fu_805_p2 = (xor_ln68_fu_799_p2 & tmp_1288_fu_761_p3);

assign and_ln68_2_fu_944_p2 = (tmp_1291_fu_914_p3 & or_ln68_1_fu_938_p2);

assign and_ln68_3_fu_974_p2 = (xor_ln68_1_fu_968_p2 & tmp_1293_fu_930_p3);

assign and_ln68_4_fu_1113_p2 = (tmp_1296_fu_1083_p3 & or_ln68_2_fu_1107_p2);

assign and_ln68_5_fu_1143_p2 = (xor_ln68_2_fu_1137_p2 & tmp_1298_fu_1099_p3);

assign and_ln68_6_fu_1282_p2 = (tmp_1301_fu_1252_p3 & or_ln68_3_fu_1276_p2);

assign and_ln68_7_fu_1312_p2 = (xor_ln68_3_fu_1306_p2 & tmp_1303_fu_1268_p3);

assign and_ln68_8_fu_1451_p2 = (tmp_1306_fu_1421_p3 & or_ln68_4_fu_1445_p2);

assign and_ln68_9_fu_1481_p2 = (xor_ln68_4_fu_1475_p2 & tmp_1308_fu_1437_p3);

assign and_ln68_fu_775_p2 = (tmp_1286_fu_745_p3 & or_ln68_fu_769_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((ap_predicate_op265_write_state4 == 1'b1) & (layer5_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((layer4_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((ap_predicate_op265_write_state4 == 1'b1) & (layer5_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((layer4_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((ap_predicate_op265_write_state4 == 1'b1) & (layer5_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((layer4_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer4_out_empty_n == 1'b0);
end

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((ap_predicate_op265_write_state4 == 1'b1) & (layer5_out_full_n == 1'b0));
end

always @ (*) begin
    ap_condition_288 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_290 = ((icmp_ln109_fu_198_p2 == 1'd0) & (icmp_ln80_fu_300_p2 == 1'd1) & (icmp_ln76_fu_246_p2 == 1'd1));
end

always @ (*) begin
    ap_condition_314 = ((icmp_ln109_fu_198_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (icmp_ln76_fu_246_p2 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_358 = ((icmp_ln109_fu_198_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_storemerge_reg_179 = 'bx;

always @ (*) begin
    ap_predicate_op265_write_state4 = ((1'd1 == and_ln55_1_reg_1780_pp0_iter2_reg) & (icmp_ln55_reg_1686_pp0_iter2_reg == 1'd1));
end

assign ap_ready = internal_ap_ready;

assign empty_87_fu_841_p2 = (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_fu_833_p1 + p_28_cast_fu_830_p1);

assign empty_88_fu_1010_p2 = (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_fu_1002_p1 + p_29_cast_fu_999_p1);

assign empty_89_fu_1179_p2 = (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_fu_1171_p1 + p_30_cast_fu_1168_p1);

assign empty_90_fu_1348_p2 = (p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_44_fu_1340_p1 + p_31_cast_fu_1337_p1);

assign empty_91_fu_1517_p2 = (p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_46_fu_1509_p1 + p_0_cast_fu_1506_p1);

assign empty_fu_672_p2 = (void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_fu_664_p1 + p_27_cast_fu_661_p1);

assign icmp_ln109_fu_198_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 10'd576) ? 1'b1 : 1'b0);

assign icmp_ln55_1_fu_441_p2 = ((sY == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln55_2_fu_228_p2 = (($signed(pY) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_3_fu_234_p2 = (($signed(pX) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_214_p2 = ((sX == 32'd1) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_246_p2 = ((add_ln76_fu_240_p2 == 32'd24) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_300_p2 = ((add_ln80_fu_294_p2 == 32'd24) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_515_p2 = ((sY == 32'd1) ? 1'b1 : 1'b0);

assign layer5_out_din = {{{{{{res_pack_5_reg_1839}, {res_pack_4_reg_1834}}, {res_pack_3_reg_1829}}, {res_pack_2_reg_1824}}, {res_pack_1_reg_1819}}, {res_pack_reg_1814}};

assign or_ln68_1_fu_938_p2 = (tmp_1292_fu_922_p3 | tmp_1290_fu_906_p3);

assign or_ln68_2_fu_1107_p2 = (tmp_1297_fu_1091_p3 | tmp_1295_fu_1075_p3);

assign or_ln68_3_fu_1276_p2 = (tmp_1302_fu_1260_p3 | tmp_1300_fu_1244_p3);

assign or_ln68_4_fu_1445_p2 = (tmp_1307_fu_1429_p3 | tmp_1305_fu_1413_p3);

assign or_ln68_5_fu_1614_p2 = (tmp_1312_fu_1598_p3 | tmp_1310_fu_1582_p3);

assign or_ln68_fu_769_p2 = (tmp_fu_737_p3 | tmp_1287_fu_753_p3);

assign p_0_cast_fu_1506_p1 = p_0_reg_1774;

assign p_27_cast_fu_661_p1 = p_5_reg_1744;

assign p_28_cast_fu_830_p1 = p_6_reg_1750;

assign p_29_cast_fu_999_p1 = p_7_reg_1756;

assign p_30_cast_fu_1168_p1 = p_8_reg_1762;

assign p_31_cast_fu_1337_p1 = p_9_reg_1768;

assign p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_40_fu_668_p1 = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_5;

assign p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_41_fu_837_p1 = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_4;

assign p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_42_fu_1006_p1 = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_3;

assign p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_43_fu_1175_p1 = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_2;

assign p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_44_fu_1340_p1 = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_7;

assign p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_45_fu_1344_p1 = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_1;

assign p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_46_fu_1509_p1 = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_6;

assign p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap_47_fu_1513_p1 = p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI9ap_ufixedILi8ELi0EL9ap_q_mode4EL9ap;

assign pool_window_1_fu_819_p3 = {{p_s_reg_1726}, {2'd0}};

assign pool_window_2_fu_988_p3 = {{p_1_reg_1732}, {2'd0}};

assign pool_window_3_fu_1157_p3 = {{p_2_reg_1738}, {2'd0}};

assign pool_window_4_fu_1326_p3 = {{trunc_ln115_4_reg_1714}, {2'd0}};

assign pool_window_5_fu_1495_p3 = {{trunc_ln115_5_reg_1720}, {2'd0}};

assign pool_window_fu_650_p3 = {{trunc_ln115_reg_1708}, {2'd0}};

assign res_pack_1_fu_980_p3 = ((and_ln68_3_fu_974_p2[0:0] == 1'b1) ? 8'd255 : add_ln68_1_fu_954_p2);

assign res_pack_2_fu_1149_p3 = ((and_ln68_5_fu_1143_p2[0:0] == 1'b1) ? 8'd255 : add_ln68_2_fu_1123_p2);

assign res_pack_3_fu_1318_p3 = ((and_ln68_7_fu_1312_p2[0:0] == 1'b1) ? 8'd255 : add_ln68_3_fu_1292_p2);

assign res_pack_4_fu_1487_p3 = ((and_ln68_9_fu_1481_p2[0:0] == 1'b1) ? 8'd255 : add_ln68_4_fu_1461_p2);

assign res_pack_5_fu_1656_p3 = ((and_ln68_11_fu_1650_p2[0:0] == 1'b1) ? 8'd255 : add_ln68_5_fu_1630_p2);

assign res_pack_fu_811_p3 = ((and_ln68_1_fu_805_p2[0:0] == 1'b1) ? 8'd255 : add_ln68_fu_785_p2);

assign select_ln86_fu_521_p3 = ((icmp_ln86_fu_515_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd1);

assign select_ln91_fu_258_p3 = ((icmp_ln55_fu_214_p2[0:0] == 1'b1) ? 32'd4294967295 : 32'd1);

assign shl_ln51_1_fu_857_p3 = {{add_ln51_6_fu_851_p2}, {2'd0}};

assign shl_ln51_2_fu_1026_p3 = {{add_ln51_8_fu_1020_p2}, {2'd0}};

assign shl_ln51_3_fu_1195_p3 = {{add_ln51_10_fu_1189_p2}, {2'd0}};

assign shl_ln51_4_fu_1364_p3 = {{add_ln51_12_fu_1358_p2}, {2'd0}};

assign shl_ln51_5_fu_1533_p3 = {{add_ln51_14_fu_1527_p2}, {2'd0}};

assign shl_ln_fu_688_p3 = {{add_ln51_fu_682_p2}, {2'd0}};

assign start_out = real_start;

assign sum_1_fu_884_p2 = (shl_ln51_1_fu_857_p3 + zext_ln42_1_fu_826_p1);

assign sum_2_fu_1053_p2 = (shl_ln51_2_fu_1026_p3 + zext_ln42_2_fu_995_p1);

assign sum_3_fu_1222_p2 = (shl_ln51_3_fu_1195_p3 + zext_ln42_3_fu_1164_p1);

assign sum_4_fu_1391_p2 = (shl_ln51_4_fu_1364_p3 + zext_ln42_4_fu_1333_p1);

assign sum_5_fu_1560_p2 = (shl_ln51_5_fu_1533_p3 + zext_ln42_5_fu_1502_p1);

assign sum_fu_715_p2 = (shl_ln_fu_688_p3 + zext_ln42_fu_657_p1);

assign tmp_1286_fu_745_p3 = add_ln51_11_fu_721_p2[32'd3];

assign tmp_1287_fu_753_p3 = sum_fu_715_p2[32'd2];

assign tmp_1288_fu_761_p3 = sum_fu_715_p2[32'd11];

assign tmp_1289_fu_791_p3 = add_ln68_fu_785_p2[32'd7];

assign tmp_1290_fu_906_p3 = sum_1_fu_884_p2[32'd4];

assign tmp_1291_fu_914_p3 = add_ln51_15_fu_890_p2[32'd3];

assign tmp_1292_fu_922_p3 = sum_1_fu_884_p2[32'd2];

assign tmp_1293_fu_930_p3 = sum_1_fu_884_p2[32'd11];

assign tmp_1294_fu_960_p3 = add_ln68_1_fu_954_p2[32'd7];

assign tmp_1295_fu_1075_p3 = sum_2_fu_1053_p2[32'd4];

assign tmp_1296_fu_1083_p3 = add_ln51_17_fu_1059_p2[32'd3];

assign tmp_1297_fu_1091_p3 = sum_2_fu_1053_p2[32'd2];

assign tmp_1298_fu_1099_p3 = sum_2_fu_1053_p2[32'd11];

assign tmp_1299_fu_1129_p3 = add_ln68_2_fu_1123_p2[32'd7];

assign tmp_1300_fu_1244_p3 = sum_3_fu_1222_p2[32'd4];

assign tmp_1301_fu_1252_p3 = add_ln51_19_fu_1228_p2[32'd3];

assign tmp_1302_fu_1260_p3 = sum_3_fu_1222_p2[32'd2];

assign tmp_1303_fu_1268_p3 = sum_3_fu_1222_p2[32'd11];

assign tmp_1304_fu_1298_p3 = add_ln68_3_fu_1292_p2[32'd7];

assign tmp_1305_fu_1413_p3 = sum_4_fu_1391_p2[32'd4];

assign tmp_1306_fu_1421_p3 = add_ln51_21_fu_1397_p2[32'd3];

assign tmp_1307_fu_1429_p3 = sum_4_fu_1391_p2[32'd2];

assign tmp_1308_fu_1437_p3 = sum_4_fu_1391_p2[32'd11];

assign tmp_1309_fu_1467_p3 = add_ln68_4_fu_1461_p2[32'd7];

assign tmp_1310_fu_1582_p3 = sum_5_fu_1560_p2[32'd4];

assign tmp_1311_fu_1590_p3 = add_ln51_23_fu_1566_p2[32'd3];

assign tmp_1312_fu_1598_p3 = sum_5_fu_1560_p2[32'd2];

assign tmp_1313_fu_1606_p3 = sum_5_fu_1560_p2[32'd11];

assign tmp_1314_fu_1636_p3 = add_ln68_5_fu_1630_p2[32'd7];

assign tmp_fu_737_p3 = sum_fu_715_p2[32'd4];

assign trunc_ln115_fu_323_p1 = layer4_out_dout[7:0];

assign trunc_ln51_10_fu_1552_p3 = {{trunc_ln51_16_fu_1548_p1}, {2'd0}};

assign trunc_ln51_11_fu_703_p1 = add_ln51_fu_682_p2[1:0];

assign trunc_ln51_12_fu_872_p1 = add_ln51_6_fu_851_p2[1:0];

assign trunc_ln51_13_fu_1041_p1 = add_ln51_8_fu_1020_p2[1:0];

assign trunc_ln51_14_fu_1210_p1 = add_ln51_10_fu_1189_p2[1:0];

assign trunc_ln51_15_fu_1379_p1 = add_ln51_12_fu_1358_p2[1:0];

assign trunc_ln51_16_fu_1548_p1 = add_ln51_14_fu_1527_p2[1:0];

assign trunc_ln51_1_fu_696_p3 = {{trunc_ln51_reg_1784}, {2'd0}};

assign trunc_ln51_2_fu_707_p3 = {{trunc_ln51_11_fu_703_p1}, {2'd0}};

assign trunc_ln51_3_fu_876_p3 = {{trunc_ln51_12_fu_872_p1}, {2'd0}};

assign trunc_ln51_4_fu_1034_p3 = {{tmp_506_reg_1794}, {2'd0}};

assign trunc_ln51_5_fu_1045_p3 = {{trunc_ln51_13_fu_1041_p1}, {2'd0}};

assign trunc_ln51_6_fu_1203_p3 = {{tmp_507_reg_1799}, {2'd0}};

assign trunc_ln51_7_fu_1372_p3 = {{tmp_508_reg_1804}, {2'd0}};

assign trunc_ln51_8_fu_1383_p3 = {{trunc_ln51_15_fu_1379_p1}, {2'd0}};

assign trunc_ln51_9_fu_1541_p3 = {{tmp_509_reg_1809}, {2'd0}};

assign trunc_ln51_fu_457_p1 = layer4_out_dout[1:0];

assign trunc_ln51_s_fu_1214_p3 = {{trunc_ln51_14_fu_1210_p1}, {2'd0}};

assign trunc_ln68_1_fu_896_p4 = {{sum_1_fu_884_p2[11:4]}};

assign trunc_ln68_2_fu_1065_p4 = {{sum_2_fu_1053_p2[11:4]}};

assign trunc_ln68_3_fu_1234_p4 = {{sum_3_fu_1222_p2[11:4]}};

assign trunc_ln68_4_fu_1403_p4 = {{sum_4_fu_1391_p2[11:4]}};

assign trunc_ln68_5_fu_1572_p4 = {{sum_5_fu_1560_p2[11:4]}};

assign trunc_ln6_fu_727_p4 = {{sum_fu_715_p2[11:4]}};

assign trunc_ln7_fu_865_p3 = {{tmp_s_reg_1789}, {2'd0}};

assign void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_fu_664_p1 = void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3;

assign void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_fu_833_p1 = void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2;

assign void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_fu_1002_p1 = void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1;

assign void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_fu_1171_p1 = void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel;

assign void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_1_d0 = {{layer4_out_dout[39:32]}};

assign void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_2_d0 = {{layer4_out_dout[31:24]}};

assign void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_3_d0 = {{layer4_out_dout[23:16]}};

assign void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_4_d0 = {{layer4_out_dout[15:8]}};

assign void_pooling2d_cl_stream_stream_array_ap_ufixed_6u_0_line_buffer_d0 = {{layer4_out_dout[47:40]}};

assign xor_ln68_1_fu_968_p2 = (tmp_1294_fu_960_p3 ^ 1'd1);

assign xor_ln68_2_fu_1137_p2 = (tmp_1299_fu_1129_p3 ^ 1'd1);

assign xor_ln68_3_fu_1306_p2 = (tmp_1304_fu_1298_p3 ^ 1'd1);

assign xor_ln68_4_fu_1475_p2 = (tmp_1309_fu_1467_p3 ^ 1'd1);

assign xor_ln68_5_fu_1644_p2 = (tmp_1314_fu_1636_p3 ^ 1'd1);

assign xor_ln68_fu_799_p2 = (tmp_1289_fu_791_p3 ^ 1'd1);

assign zext_ln42_1_fu_826_p1 = pool_window_1_fu_819_p3;

assign zext_ln42_2_fu_995_p1 = pool_window_2_fu_988_p3;

assign zext_ln42_3_fu_1164_p1 = pool_window_3_fu_1157_p3;

assign zext_ln42_4_fu_1333_p1 = pool_window_4_fu_1326_p3;

assign zext_ln42_5_fu_1502_p1 = pool_window_5_fu_1495_p3;

assign zext_ln42_fu_657_p1 = pool_window_fu_650_p3;

assign zext_ln51_10_fu_1185_p1 = empty_89_fu_1179_p2;

assign zext_ln51_11_fu_1354_p1 = empty_90_fu_1348_p2;

assign zext_ln51_12_fu_1523_p1 = empty_91_fu_1517_p2;

assign zext_ln51_7_fu_678_p1 = empty_fu_672_p2;

assign zext_ln51_8_fu_847_p1 = empty_87_fu_841_p2;

assign zext_ln51_9_fu_1016_p1 = empty_88_fu_1010_p2;

assign zext_ln68_1_fu_950_p1 = and_ln68_2_fu_944_p2;

assign zext_ln68_2_fu_1119_p1 = and_ln68_4_fu_1113_p2;

assign zext_ln68_3_fu_1288_p1 = and_ln68_6_fu_1282_p2;

assign zext_ln68_4_fu_1457_p1 = and_ln68_8_fu_1451_p2;

assign zext_ln68_5_fu_1626_p1 = and_ln68_10_fu_1620_p2;

assign zext_ln68_fu_781_p1 = and_ln68_fu_775_p2;

endmodule //myproject_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_s
