// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer14_out_dout,
        layer14_out_num_data_valid,
        layer14_out_fifo_cap,
        layer14_out_empty_n,
        layer14_out_read,
        layer23_out_din,
        layer23_out_num_data_valid,
        layer23_out_fifo_cap,
        layer23_out_full_n,
        layer23_out_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [2015:0] layer14_out_dout;
input  [1:0] layer14_out_num_data_valid;
input  [1:0] layer14_out_fifo_cap;
input   layer14_out_empty_n;
output   layer14_out_read;
output  [1343:0] layer23_out_din;
input  [1:0] layer23_out_num_data_valid;
input  [1:0] layer23_out_fifo_cap;
input   layer23_out_full_n;
output   layer23_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer14_out_read;
reg layer23_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer14_out_blk_n;
reg    layer23_out_blk_n;
wire    ap_CS_fsm_state2;
reg   [15:0] trunc_ln_reg_2996;
reg    ap_block_state1;
reg   [15:0] trunc_ln41_4_reg_3001;
reg   [15:0] trunc_ln41_5_reg_3006;
reg   [15:0] trunc_ln41_6_reg_3011;
reg   [15:0] trunc_ln41_7_reg_3016;
reg   [15:0] trunc_ln41_8_reg_3021;
reg   [15:0] trunc_ln41_9_reg_3026;
reg   [15:0] trunc_ln41_s_reg_3031;
reg   [15:0] trunc_ln41_1_reg_3036;
reg   [15:0] trunc_ln41_2_reg_3041;
reg   [15:0] trunc_ln41_3_reg_3046;
reg   [15:0] trunc_ln41_10_reg_3051;
reg   [15:0] trunc_ln41_11_reg_3056;
reg   [15:0] trunc_ln46_s_reg_3061;
reg   [15:0] trunc_ln46_1_reg_3066;
reg   [15:0] trunc_ln46_2_reg_3071;
reg   [15:0] trunc_ln46_3_reg_3076;
reg   [15:0] trunc_ln46_4_reg_3081;
reg   [15:0] trunc_ln46_5_reg_3086;
reg   [15:0] trunc_ln46_6_reg_3091;
reg   [15:0] trunc_ln46_7_reg_3096;
reg   [15:0] trunc_ln46_8_reg_3101;
reg   [15:0] trunc_ln46_9_reg_3106;
reg   [15:0] trunc_ln46_10_reg_3111;
reg   [15:0] trunc_ln46_11_reg_3116;
reg   [15:0] trunc_ln46_12_reg_3121;
reg   [15:0] trunc_ln46_13_reg_3126;
reg   [15:0] trunc_ln46_14_reg_3131;
reg   [15:0] trunc_ln46_15_reg_3136;
reg   [15:0] trunc_ln46_16_reg_3141;
reg   [15:0] trunc_ln46_17_reg_3146;
reg   [15:0] trunc_ln46_18_reg_3151;
reg   [15:0] trunc_ln46_19_reg_3156;
reg   [15:0] trunc_ln46_20_reg_3161;
reg   [15:0] trunc_ln46_21_reg_3166;
reg   [15:0] trunc_ln46_22_reg_3171;
reg   [15:0] trunc_ln46_23_reg_3176;
reg   [15:0] trunc_ln46_24_reg_3181;
reg   [15:0] trunc_ln46_25_reg_3186;
reg   [15:0] trunc_ln46_26_reg_3191;
reg   [15:0] trunc_ln46_27_reg_3196;
reg   [15:0] trunc_ln46_28_reg_3201;
reg   [15:0] trunc_ln46_29_reg_3206;
reg   [15:0] trunc_ln46_30_reg_3211;
reg   [15:0] trunc_ln46_31_reg_3216;
reg   [15:0] trunc_ln46_32_reg_3221;
reg   [15:0] trunc_ln46_33_reg_3226;
reg   [15:0] trunc_ln46_34_reg_3231;
reg   [15:0] trunc_ln46_35_reg_3236;
reg   [15:0] trunc_ln46_36_reg_3241;
reg   [15:0] trunc_ln46_37_reg_3246;
reg   [15:0] trunc_ln46_38_reg_3251;
reg   [15:0] trunc_ln46_39_reg_3256;
reg   [15:0] trunc_ln46_40_reg_3261;
reg   [15:0] trunc_ln46_41_reg_3266;
reg   [15:0] trunc_ln46_42_reg_3271;
reg   [15:0] trunc_ln46_43_reg_3276;
reg   [15:0] trunc_ln46_44_reg_3281;
reg   [15:0] trunc_ln46_45_reg_3286;
reg   [15:0] trunc_ln46_46_reg_3291;
reg   [15:0] trunc_ln46_47_reg_3296;
reg   [15:0] trunc_ln46_48_reg_3301;
reg   [15:0] trunc_ln46_49_reg_3306;
reg   [15:0] trunc_ln46_50_reg_3311;
reg   [15:0] tmp_590_reg_3316;
reg   [15:0] tmp_591_reg_3321;
reg   [15:0] tmp_592_reg_3326;
reg   [15:0] tmp_593_reg_3331;
reg   [15:0] tmp_594_reg_3336;
reg   [15:0] tmp_595_reg_3341;
reg   [15:0] tmp_596_reg_3346;
reg   [15:0] tmp_597_reg_3351;
reg   [15:0] tmp_598_reg_3356;
reg   [15:0] tmp_599_reg_3361;
reg   [15:0] tmp_600_reg_3366;
reg   [15:0] tmp_601_reg_3371;
reg   [15:0] tmp_602_reg_3376;
reg   [15:0] tmp_603_reg_3381;
reg   [15:0] tmp_604_reg_3386;
reg   [15:0] tmp_605_reg_3391;
reg   [15:0] tmp_606_reg_3396;
reg   [15:0] tmp_607_reg_3401;
reg   [15:0] tmp_608_reg_3406;
reg   [15:0] tmp_609_reg_3411;
wire   [21:0] trunc_ln85_fu_409_p1;
wire   [34:0] y_fu_413_p3;
wire   [34:0] add_ln42_fu_421_p2;
wire   [22:0] tmp_s_fu_437_p4;
wire   [34:0] y_1_fu_447_p3;
wire   [34:0] add_ln42_1_fu_455_p2;
wire   [21:0] tmp_524_fu_471_p4;
wire   [34:0] y_2_fu_481_p3;
wire   [34:0] add_ln42_2_fu_489_p2;
wire   [21:0] tmp_525_fu_505_p4;
wire   [34:0] y_3_fu_515_p3;
wire   [34:0] add_ln42_3_fu_523_p2;
wire   [21:0] tmp_526_fu_539_p4;
wire   [34:0] y_4_fu_549_p3;
wire   [34:0] add_ln42_4_fu_557_p2;
wire   [21:0] tmp_527_fu_573_p4;
wire   [34:0] y_5_fu_583_p3;
wire   [34:0] add_ln42_5_fu_591_p2;
wire   [21:0] tmp_528_fu_607_p4;
wire   [34:0] y_6_fu_617_p3;
wire   [34:0] add_ln42_6_fu_625_p2;
wire   [21:0] tmp_529_fu_641_p4;
wire   [34:0] y_7_fu_651_p3;
wire   [34:0] add_ln42_7_fu_659_p2;
wire   [21:0] tmp_530_fu_675_p4;
wire   [34:0] y_8_fu_685_p3;
wire   [34:0] add_ln42_8_fu_693_p2;
wire   [22:0] tmp_531_fu_709_p4;
wire   [34:0] y_9_fu_719_p3;
wire   [34:0] add_ln42_9_fu_727_p2;
wire   [21:0] tmp_532_fu_743_p4;
wire   [34:0] y_10_fu_753_p3;
wire   [34:0] add_ln42_10_fu_761_p2;
wire   [21:0] tmp_533_fu_777_p4;
wire   [34:0] y_11_fu_787_p3;
wire   [34:0] add_ln42_11_fu_795_p2;
wire   [21:0] tmp_534_fu_811_p4;
wire   [34:0] y_12_fu_821_p3;
wire   [21:0] tmp_535_fu_835_p4;
wire   [34:0] y_13_fu_845_p3;
wire   [22:0] tmp_536_fu_869_p4;
wire   [34:0] y_14_fu_879_p3;
wire   [21:0] tmp_537_fu_893_p4;
wire   [34:0] y_15_fu_903_p3;
wire   [21:0] tmp_538_fu_917_p4;
wire   [34:0] y_16_fu_927_p3;
wire   [21:0] tmp_539_fu_941_p4;
wire   [34:0] y_17_fu_951_p3;
wire   [21:0] tmp_540_fu_965_p4;
wire   [34:0] y_18_fu_975_p3;
wire   [22:0] tmp_541_fu_989_p4;
wire   [34:0] y_19_fu_999_p3;
wire   [22:0] tmp_542_fu_1013_p4;
wire   [34:0] y_20_fu_1023_p3;
wire   [21:0] tmp_543_fu_1037_p4;
wire   [34:0] y_21_fu_1047_p3;
wire   [22:0] tmp_544_fu_1061_p4;
wire   [34:0] y_22_fu_1071_p3;
wire   [21:0] tmp_545_fu_1085_p4;
wire   [34:0] y_23_fu_1095_p3;
wire   [21:0] tmp_546_fu_1109_p4;
wire   [34:0] y_24_fu_1119_p3;
wire   [21:0] tmp_547_fu_1133_p4;
wire   [34:0] y_25_fu_1143_p3;
wire   [21:0] tmp_548_fu_1157_p4;
wire   [34:0] y_26_fu_1167_p3;
wire   [21:0] tmp_549_fu_1181_p4;
wire   [34:0] y_27_fu_1191_p3;
wire   [21:0] tmp_550_fu_1205_p4;
wire   [34:0] y_28_fu_1215_p3;
wire   [22:0] tmp_551_fu_1229_p4;
wire   [34:0] y_29_fu_1239_p3;
wire   [21:0] tmp_552_fu_1253_p4;
wire   [34:0] y_30_fu_1263_p3;
wire   [21:0] tmp_553_fu_1277_p4;
wire   [34:0] y_31_fu_1287_p3;
wire   [21:0] tmp_554_fu_1301_p4;
wire   [34:0] y_32_fu_1311_p3;
wire   [21:0] tmp_555_fu_1325_p4;
wire   [34:0] y_33_fu_1335_p3;
wire   [21:0] tmp_556_fu_1349_p4;
wire   [34:0] y_34_fu_1359_p3;
wire   [21:0] tmp_557_fu_1373_p4;
wire   [34:0] y_35_fu_1383_p3;
wire   [21:0] tmp_558_fu_1397_p4;
wire   [34:0] y_36_fu_1407_p3;
wire   [21:0] tmp_559_fu_1421_p4;
wire   [34:0] y_37_fu_1431_p3;
wire   [21:0] tmp_560_fu_1445_p4;
wire   [34:0] y_38_fu_1455_p3;
wire   [21:0] tmp_561_fu_1469_p4;
wire   [34:0] y_39_fu_1479_p3;
wire   [21:0] tmp_562_fu_1493_p4;
wire   [34:0] y_40_fu_1503_p3;
wire   [21:0] tmp_563_fu_1517_p4;
wire   [34:0] y_41_fu_1527_p3;
wire   [21:0] tmp_564_fu_1541_p4;
wire   [34:0] y_42_fu_1551_p3;
wire   [22:0] tmp_565_fu_1565_p4;
wire   [34:0] y_43_fu_1575_p3;
wire   [21:0] tmp_566_fu_1589_p4;
wire   [34:0] y_44_fu_1599_p3;
wire   [22:0] tmp_567_fu_1613_p4;
wire   [34:0] y_45_fu_1623_p3;
wire   [21:0] tmp_568_fu_1637_p4;
wire   [34:0] y_46_fu_1647_p3;
wire   [21:0] tmp_569_fu_1661_p4;
wire   [34:0] y_47_fu_1671_p3;
wire   [21:0] tmp_570_fu_1685_p4;
wire   [34:0] y_48_fu_1695_p3;
wire   [21:0] tmp_571_fu_1709_p4;
wire   [34:0] y_49_fu_1719_p3;
wire   [21:0] tmp_572_fu_1733_p4;
wire   [34:0] y_50_fu_1743_p3;
wire   [22:0] tmp_573_fu_1757_p4;
wire   [34:0] y_51_fu_1767_p3;
wire   [21:0] tmp_574_fu_1781_p4;
wire   [34:0] y_52_fu_1791_p3;
wire   [21:0] tmp_575_fu_1805_p4;
wire   [34:0] y_53_fu_1815_p3;
wire   [22:0] tmp_576_fu_1829_p4;
wire   [34:0] y_54_fu_1839_p3;
wire   [22:0] tmp_577_fu_1853_p4;
wire   [34:0] y_55_fu_1863_p3;
wire   [21:0] tmp_578_fu_1877_p4;
wire   [34:0] y_56_fu_1887_p3;
wire   [21:0] tmp_579_fu_1901_p4;
wire   [34:0] y_57_fu_1911_p3;
wire   [21:0] tmp_580_fu_1925_p4;
wire   [34:0] y_58_fu_1935_p3;
wire   [21:0] tmp_581_fu_1949_p4;
wire   [34:0] y_59_fu_1959_p3;
wire   [21:0] tmp_582_fu_1973_p4;
wire   [34:0] y_60_fu_1983_p3;
wire   [21:0] tmp_583_fu_1997_p4;
wire   [34:0] y_61_fu_2007_p3;
wire   [21:0] tmp_584_fu_2021_p4;
wire   [34:0] y_62_fu_2031_p3;
wire   [21:0] tmp_585_fu_2045_p4;
wire   [34:0] y_63_fu_2055_p3;
wire   [21:0] tmp_586_fu_2069_p4;
wire   [34:0] y_64_fu_2079_p3;
wire   [21:0] tmp_587_fu_2093_p4;
wire   [34:0] y_65_fu_2103_p3;
wire   [21:0] tmp_588_fu_2117_p4;
wire   [34:0] y_66_fu_2127_p3;
wire   [21:0] tmp_589_fu_2141_p4;
wire   [34:0] y_67_fu_2151_p3;
wire   [34:0] trunc_ln1_fu_2165_p4;
wire   [34:0] trunc_ln85_2_fu_2181_p4;
wire   [34:0] add_ln42_16_fu_935_p2;
wire   [34:0] add_ln42_17_fu_959_p2;
wire   [34:0] add_ln42_18_fu_983_p2;
wire   [34:0] add_ln42_22_fu_1079_p2;
wire   [34:0] add_ln42_23_fu_1103_p2;
wire   [34:0] add_ln42_24_fu_1127_p2;
wire   [34:0] add_ln42_25_fu_1151_p2;
wire   [34:0] add_ln42_28_fu_1223_p2;
wire   [34:0] add_ln42_29_fu_1247_p2;
wire   [34:0] add_ln42_30_fu_1271_p2;
wire   [34:0] add_ln42_33_fu_1343_p2;
wire   [34:0] add_ln42_34_fu_1367_p2;
wire   [34:0] add_ln42_35_fu_1391_p2;
wire   [34:0] add_ln42_36_fu_1415_p2;
wire   [34:0] add_ln42_37_fu_1439_p2;
wire   [34:0] add_ln42_40_fu_1511_p2;
wire   [34:0] add_ln42_41_fu_1535_p2;
wire   [34:0] add_ln42_42_fu_1559_p2;
wire   [34:0] add_ln42_45_fu_1631_p2;
wire   [34:0] add_ln42_46_fu_1655_p2;
wire   [34:0] add_ln42_47_fu_1679_p2;
wire   [34:0] add_ln42_48_fu_1703_p2;
wire   [34:0] add_ln42_49_fu_1727_p2;
wire   [34:0] add_ln42_50_fu_1751_p2;
wire   [34:0] add_ln42_51_fu_1775_p2;
wire   [34:0] add_ln42_52_fu_1799_p2;
wire   [34:0] add_ln42_53_fu_1823_p2;
wire   [34:0] add_ln42_54_fu_1847_p2;
wire   [34:0] add_ln42_55_fu_1871_p2;
wire   [34:0] add_ln42_56_fu_1895_p2;
wire   [34:0] add_ln42_57_fu_1919_p2;
wire   [34:0] add_ln42_58_fu_1943_p2;
wire   [34:0] add_ln42_59_fu_1967_p2;
wire   [34:0] add_ln42_62_fu_2039_p2;
wire   [34:0] add_ln42_63_fu_2063_p2;
wire   [34:0] add_ln42_66_fu_2135_p2;
wire   [34:0] add_ln42_67_fu_2159_p2;
wire   [34:0] add_ln42_68_fu_2175_p2;
wire   [34:0] add_ln42_69_fu_2191_p2;
wire   [34:0] add_ln42_14_fu_887_p2;
wire   [34:0] add_ln42_13_fu_853_p2;
wire   [34:0] add_ln42_65_fu_2111_p2;
wire   [34:0] add_ln42_64_fu_2087_p2;
wire   [34:0] add_ln42_61_fu_2015_p2;
wire   [34:0] add_ln42_60_fu_1991_p2;
wire   [34:0] add_ln42_44_fu_1607_p2;
wire   [34:0] add_ln42_43_fu_1583_p2;
wire   [34:0] add_ln42_39_fu_1487_p2;
wire   [34:0] add_ln42_38_fu_1463_p2;
wire   [34:0] add_ln42_32_fu_1319_p2;
wire   [34:0] add_ln42_31_fu_1295_p2;
wire   [34:0] add_ln42_27_fu_1199_p2;
wire   [34:0] add_ln42_26_fu_1175_p2;
wire   [34:0] add_ln42_21_fu_1055_p2;
wire   [34:0] add_ln42_20_fu_1031_p2;
wire   [34:0] add_ln42_19_fu_1007_p2;
wire   [34:0] add_ln42_15_fu_911_p2;
wire   [34:0] add_ln42_12_fu_829_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer23_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (layer14_out_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_590_reg_3316 <= {{add_ln42_14_fu_887_p2[34:19]}};
        tmp_591_reg_3321 <= {{add_ln42_13_fu_853_p2[34:19]}};
        tmp_592_reg_3326 <= {{add_ln42_65_fu_2111_p2[34:19]}};
        tmp_593_reg_3331 <= {{add_ln42_64_fu_2087_p2[34:19]}};
        tmp_594_reg_3336 <= {{add_ln42_61_fu_2015_p2[34:19]}};
        tmp_595_reg_3341 <= {{add_ln42_60_fu_1991_p2[34:19]}};
        tmp_596_reg_3346 <= {{add_ln42_44_fu_1607_p2[34:19]}};
        tmp_597_reg_3351 <= {{add_ln42_43_fu_1583_p2[34:19]}};
        tmp_598_reg_3356 <= {{add_ln42_39_fu_1487_p2[34:19]}};
        tmp_599_reg_3361 <= {{add_ln42_38_fu_1463_p2[34:19]}};
        tmp_600_reg_3366 <= {{add_ln42_32_fu_1319_p2[34:19]}};
        tmp_601_reg_3371 <= {{add_ln42_31_fu_1295_p2[34:19]}};
        tmp_602_reg_3376 <= {{add_ln42_27_fu_1199_p2[34:19]}};
        tmp_603_reg_3381 <= {{add_ln42_26_fu_1175_p2[34:19]}};
        tmp_604_reg_3386 <= {{add_ln42_21_fu_1055_p2[34:19]}};
        tmp_605_reg_3391 <= {{add_ln42_20_fu_1031_p2[34:19]}};
        tmp_606_reg_3396 <= {{add_ln42_19_fu_1007_p2[34:19]}};
        tmp_607_reg_3401 <= {{add_ln42_15_fu_911_p2[34:19]}};
        tmp_608_reg_3406 <= {{layer14_out_dout[381:366]}};
        tmp_609_reg_3411 <= {{add_ln42_12_fu_829_p2[34:19]}};
        trunc_ln41_10_reg_3051 <= {{add_ln42_11_fu_795_p2[34:19]}};
        trunc_ln41_11_reg_3056 <= {{layer14_out_dout[357:342]}};
        trunc_ln41_1_reg_3036 <= {{add_ln42_8_fu_693_p2[34:19]}};
        trunc_ln41_2_reg_3041 <= {{add_ln42_9_fu_727_p2[34:19]}};
        trunc_ln41_3_reg_3046 <= {{add_ln42_10_fu_761_p2[34:19]}};
        trunc_ln41_4_reg_3001 <= {{add_ln42_1_fu_455_p2[34:19]}};
        trunc_ln41_5_reg_3006 <= {{add_ln42_2_fu_489_p2[34:19]}};
        trunc_ln41_6_reg_3011 <= {{add_ln42_3_fu_523_p2[34:19]}};
        trunc_ln41_7_reg_3016 <= {{add_ln42_4_fu_557_p2[34:19]}};
        trunc_ln41_8_reg_3021 <= {{add_ln42_5_fu_591_p2[34:19]}};
        trunc_ln41_9_reg_3026 <= {{add_ln42_6_fu_625_p2[34:19]}};
        trunc_ln41_s_reg_3031 <= {{add_ln42_7_fu_659_p2[34:19]}};
        trunc_ln46_10_reg_3111 <= {{add_ln42_25_fu_1151_p2[34:19]}};
        trunc_ln46_11_reg_3116 <= {{layer14_out_dout[837:822]}};
        trunc_ln46_12_reg_3121 <= {{add_ln42_28_fu_1223_p2[34:19]}};
        trunc_ln46_13_reg_3126 <= {{add_ln42_29_fu_1247_p2[34:19]}};
        trunc_ln46_14_reg_3131 <= {{add_ln42_30_fu_1271_p2[34:19]}};
        trunc_ln46_15_reg_3136 <= {{layer14_out_dout[982:967]}};
        trunc_ln46_16_reg_3141 <= {{add_ln42_33_fu_1343_p2[34:19]}};
        trunc_ln46_17_reg_3146 <= {{add_ln42_34_fu_1367_p2[34:19]}};
        trunc_ln46_18_reg_3151 <= {{add_ln42_35_fu_1391_p2[34:19]}};
        trunc_ln46_19_reg_3156 <= {{add_ln42_36_fu_1415_p2[34:19]}};
        trunc_ln46_1_reg_3066 <= {{add_ln42_16_fu_935_p2[34:19]}};
        trunc_ln46_20_reg_3161 <= {{add_ln42_37_fu_1439_p2[34:19]}};
        trunc_ln46_21_reg_3166 <= {{layer14_out_dout[1174:1159]}};
        trunc_ln46_22_reg_3171 <= {{add_ln42_40_fu_1511_p2[34:19]}};
        trunc_ln46_23_reg_3176 <= {{add_ln42_41_fu_1535_p2[34:19]}};
        trunc_ln46_24_reg_3181 <= {{add_ln42_42_fu_1559_p2[34:19]}};
        trunc_ln46_25_reg_3186 <= {{layer14_out_dout[1317:1302]}};
        trunc_ln46_26_reg_3191 <= {{layer14_out_dout[1341:1326]}};
        trunc_ln46_27_reg_3196 <= {{add_ln42_45_fu_1631_p2[34:19]}};
        trunc_ln46_28_reg_3201 <= {{add_ln42_46_fu_1655_p2[34:19]}};
        trunc_ln46_29_reg_3206 <= {{add_ln42_47_fu_1679_p2[34:19]}};
        trunc_ln46_2_reg_3071 <= {{add_ln42_17_fu_959_p2[34:19]}};
        trunc_ln46_30_reg_3211 <= {{add_ln42_48_fu_1703_p2[34:19]}};
        trunc_ln46_31_reg_3216 <= {{add_ln42_49_fu_1727_p2[34:19]}};
        trunc_ln46_32_reg_3221 <= {{add_ln42_50_fu_1751_p2[34:19]}};
        trunc_ln46_33_reg_3226 <= {{add_ln42_51_fu_1775_p2[34:19]}};
        trunc_ln46_34_reg_3231 <= {{add_ln42_52_fu_1799_p2[34:19]}};
        trunc_ln46_35_reg_3236 <= {{add_ln42_53_fu_1823_p2[34:19]}};
        trunc_ln46_36_reg_3241 <= {{add_ln42_54_fu_1847_p2[34:19]}};
        trunc_ln46_37_reg_3246 <= {{add_ln42_55_fu_1871_p2[34:19]}};
        trunc_ln46_38_reg_3251 <= {{add_ln42_56_fu_1895_p2[34:19]}};
        trunc_ln46_39_reg_3256 <= {{add_ln42_57_fu_1919_p2[34:19]}};
        trunc_ln46_3_reg_3076 <= {{add_ln42_18_fu_983_p2[34:19]}};
        trunc_ln46_40_reg_3261 <= {{add_ln42_58_fu_1943_p2[34:19]}};
        trunc_ln46_41_reg_3266 <= {{add_ln42_59_fu_1967_p2[34:19]}};
        trunc_ln46_42_reg_3271 <= {{layer14_out_dout[1773:1758]}};
        trunc_ln46_43_reg_3276 <= {{layer14_out_dout[1797:1782]}};
        trunc_ln46_44_reg_3281 <= {{add_ln42_62_fu_2039_p2[34:19]}};
        trunc_ln46_45_reg_3286 <= {{add_ln42_63_fu_2063_p2[34:19]}};
        trunc_ln46_46_reg_3291 <= {{layer14_out_dout[1917:1902]}};
        trunc_ln46_47_reg_3296 <= {{add_ln42_66_fu_2135_p2[34:19]}};
        trunc_ln46_48_reg_3301 <= {{add_ln42_67_fu_2159_p2[34:19]}};
        trunc_ln46_49_reg_3306 <= {{add_ln42_68_fu_2175_p2[34:19]}};
        trunc_ln46_4_reg_3081 <= {{layer14_out_dout[597:582]}};
        trunc_ln46_50_reg_3311 <= {{add_ln42_69_fu_2191_p2[34:19]}};
        trunc_ln46_5_reg_3086 <= {{layer14_out_dout[645:630]}};
        trunc_ln46_6_reg_3091 <= {{layer14_out_dout[669:654]}};
        trunc_ln46_7_reg_3096 <= {{add_ln42_22_fu_1079_p2[34:19]}};
        trunc_ln46_8_reg_3101 <= {{add_ln42_23_fu_1103_p2[34:19]}};
        trunc_ln46_9_reg_3106 <= {{add_ln42_24_fu_1127_p2[34:19]}};
        trunc_ln46_s_reg_3061 <= {{layer14_out_dout[453:438]}};
        trunc_ln_reg_2996 <= {{add_ln42_fu_421_p2[34:19]}};
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (layer14_out_empty_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer23_out_full_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer23_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer23_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer14_out_blk_n = layer14_out_empty_n;
    end else begin
        layer14_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (layer14_out_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer14_out_read = 1'b1;
    end else begin
        layer14_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer23_out_blk_n = layer23_out_full_n;
    end else begin
        layer23_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer23_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        layer23_out_write = 1'b1;
    end else begin
        layer23_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (layer14_out_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((layer23_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln42_10_fu_761_p2 = ($signed(y_10_fu_753_p3) + $signed(35'd34342961152));

assign add_ln42_11_fu_795_p2 = ($signed(y_11_fu_787_p3) + $signed(35'd34326183936));

assign add_ln42_12_fu_829_p2 = (y_12_fu_821_p3 + 35'd67108864);

assign add_ln42_13_fu_853_p2 = ($signed(y_13_fu_845_p3) + $signed(35'd34342961152));

assign add_ln42_14_fu_887_p2 = (y_14_fu_879_p3 + 35'd33554432);

assign add_ln42_15_fu_911_p2 = (y_15_fu_903_p3 + 35'd33554432);

assign add_ln42_16_fu_935_p2 = (y_16_fu_927_p3 + 35'd50331648);

assign add_ln42_17_fu_959_p2 = (y_17_fu_951_p3 + 35'd33554432);

assign add_ln42_18_fu_983_p2 = (y_18_fu_975_p3 + 35'd83886080);

assign add_ln42_19_fu_1007_p2 = ($signed(y_19_fu_999_p3) + $signed(35'd34342961152));

assign add_ln42_1_fu_455_p2 = ($signed(y_1_fu_447_p3) + $signed(35'd34342961152));

assign add_ln42_20_fu_1031_p2 = (y_20_fu_1023_p3 + 35'd16777216);

assign add_ln42_21_fu_1055_p2 = (y_21_fu_1047_p3 + 35'd16777216);

assign add_ln42_22_fu_1079_p2 = ($signed(y_22_fu_1071_p3) + $signed(35'd34342961152));

assign add_ln42_23_fu_1103_p2 = ($signed(y_23_fu_1095_p3) + $signed(35'd34326183936));

assign add_ln42_24_fu_1127_p2 = (y_24_fu_1119_p3 + 35'd50331648);

assign add_ln42_25_fu_1151_p2 = (y_25_fu_1143_p3 + 35'd67108864);

assign add_ln42_26_fu_1175_p2 = (y_26_fu_1167_p3 + 35'd33554432);

assign add_ln42_27_fu_1199_p2 = (y_27_fu_1191_p3 + 35'd33554432);

assign add_ln42_28_fu_1223_p2 = (y_28_fu_1215_p3 + 35'd33554432);

assign add_ln42_29_fu_1247_p2 = (y_29_fu_1239_p3 + 35'd83886080);

assign add_ln42_2_fu_489_p2 = (y_2_fu_481_p3 + 35'd16777216);

assign add_ln42_30_fu_1271_p2 = (y_30_fu_1263_p3 + 35'd67108864);

assign add_ln42_31_fu_1295_p2 = ($signed(y_31_fu_1287_p3) + $signed(35'd34342961152));

assign add_ln42_32_fu_1319_p2 = ($signed(y_32_fu_1311_p3) + $signed(35'd34326183936));

assign add_ln42_33_fu_1343_p2 = (y_33_fu_1335_p3 + 35'd33554432);

assign add_ln42_34_fu_1367_p2 = ($signed(y_34_fu_1359_p3) + $signed(35'd34342961152));

assign add_ln42_35_fu_1391_p2 = (y_35_fu_1383_p3 + 35'd33554432);

assign add_ln42_36_fu_1415_p2 = (y_36_fu_1407_p3 + 35'd33554432);

assign add_ln42_37_fu_1439_p2 = (y_37_fu_1431_p3 + 35'd50331648);

assign add_ln42_38_fu_1463_p2 = (y_38_fu_1455_p3 + 35'd83886080);

assign add_ln42_39_fu_1487_p2 = ($signed(y_39_fu_1479_p3) + $signed(35'd34309406720));

assign add_ln42_3_fu_523_p2 = (y_3_fu_515_p3 + 35'd16777216);

assign add_ln42_40_fu_1511_p2 = (y_40_fu_1503_p3 + 35'd16777216);

assign add_ln42_41_fu_1535_p2 = ($signed(y_41_fu_1527_p3) + $signed(35'd34342961152));

assign add_ln42_42_fu_1559_p2 = (y_42_fu_1551_p3 + 35'd50331648);

assign add_ln42_43_fu_1583_p2 = (y_43_fu_1575_p3 + 35'd16777216);

assign add_ln42_44_fu_1607_p2 = ($signed(y_44_fu_1599_p3) + $signed(35'd34342961152));

assign add_ln42_45_fu_1631_p2 = ($signed(y_45_fu_1623_p3) + $signed(35'd34342961152));

assign add_ln42_46_fu_1655_p2 = (y_46_fu_1647_p3 + 35'd50331648);

assign add_ln42_47_fu_1679_p2 = (y_47_fu_1671_p3 + 35'd50331648);

assign add_ln42_48_fu_1703_p2 = (y_48_fu_1695_p3 + 35'd33554432);

assign add_ln42_49_fu_1727_p2 = (y_49_fu_1719_p3 + 35'd16777216);

assign add_ln42_4_fu_557_p2 = ($signed(y_4_fu_549_p3) + $signed(35'd34342961152));

assign add_ln42_50_fu_1751_p2 = (y_50_fu_1743_p3 + 35'd33554432);

assign add_ln42_51_fu_1775_p2 = (y_51_fu_1767_p3 + 35'd50331648);

assign add_ln42_52_fu_1799_p2 = (y_52_fu_1791_p3 + 35'd16777216);

assign add_ln42_53_fu_1823_p2 = (y_53_fu_1815_p3 + 35'd16777216);

assign add_ln42_54_fu_1847_p2 = ($signed(y_54_fu_1839_p3) + $signed(35'd34342961152));

assign add_ln42_55_fu_1871_p2 = (y_55_fu_1863_p3 + 35'd33554432);

assign add_ln42_56_fu_1895_p2 = ($signed(y_56_fu_1887_p3) + $signed(35'd34309406720));

assign add_ln42_57_fu_1919_p2 = (y_57_fu_1911_p3 + 35'd33554432);

assign add_ln42_58_fu_1943_p2 = (y_58_fu_1935_p3 + 35'd50331648);

assign add_ln42_59_fu_1967_p2 = (y_59_fu_1959_p3 + 35'd67108864);

assign add_ln42_5_fu_591_p2 = (y_5_fu_583_p3 + 35'd33554432);

assign add_ln42_60_fu_1991_p2 = (y_60_fu_1983_p3 + 35'd67108864);

assign add_ln42_61_fu_2015_p2 = (y_61_fu_2007_p3 + 35'd33554432);

assign add_ln42_62_fu_2039_p2 = (y_62_fu_2031_p3 + 35'd16777216);

assign add_ln42_63_fu_2063_p2 = ($signed(y_63_fu_2055_p3) + $signed(35'd34342961152));

assign add_ln42_64_fu_2087_p2 = (y_64_fu_2079_p3 + 35'd33554432);

assign add_ln42_65_fu_2111_p2 = (y_65_fu_2103_p3 + 35'd16777216);

assign add_ln42_66_fu_2135_p2 = ($signed(y_66_fu_2127_p3) + $signed(35'd34326183936));

assign add_ln42_67_fu_2159_p2 = (y_67_fu_2151_p3 + 35'd16777216);

assign add_ln42_68_fu_2175_p2 = (trunc_ln1_fu_2165_p4 + 35'd33554432);

assign add_ln42_69_fu_2191_p2 = (trunc_ln85_2_fu_2181_p4 + 35'd50331648);

assign add_ln42_6_fu_625_p2 = ($signed(y_6_fu_617_p3) + $signed(35'd34342961152));

assign add_ln42_7_fu_659_p2 = (y_7_fu_651_p3 + 35'd83886080);

assign add_ln42_8_fu_693_p2 = ($signed(y_8_fu_685_p3) + $signed(35'd34342961152));

assign add_ln42_9_fu_727_p2 = ($signed(y_9_fu_719_p3) + $signed(35'd34342961152));

assign add_ln42_fu_421_p2 = (y_fu_413_p3 + 35'd16777216);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer14_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign layer23_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{trunc_ln46_50_reg_3311}, {trunc_ln46_49_reg_3306}}, {trunc_ln46_48_reg_3301}}, {trunc_ln46_47_reg_3296}}, {trunc_ln46_46_reg_3291}}, {tmp_592_reg_3326}}, {tmp_593_reg_3331}}, {trunc_ln46_45_reg_3286}}, {trunc_ln46_44_reg_3281}}, {trunc_ln46_43_reg_3276}}, {trunc_ln46_42_reg_3271}}, {tmp_594_reg_3336}}, {tmp_595_reg_3341}}, {trunc_ln46_41_reg_3266}}, {trunc_ln46_40_reg_3261}}, {trunc_ln46_39_reg_3256}}, {trunc_ln46_38_reg_3251}}, {trunc_ln46_37_reg_3246}}, {trunc_ln46_36_reg_3241}}, {trunc_ln46_35_reg_3236}}, {trunc_ln46_34_reg_3231}}, {trunc_ln46_33_reg_3226}}, {trunc_ln46_32_reg_3221}}, {trunc_ln46_31_reg_3216}}, {trunc_ln46_30_reg_3211}}, {trunc_ln46_29_reg_3206}}, {trunc_ln46_28_reg_3201}}, {trunc_ln46_27_reg_3196}}, {trunc_ln46_26_reg_3191}}, {trunc_ln46_25_reg_3186}}, {tmp_596_reg_3346}}, {tmp_597_reg_3351}}, {trunc_ln46_24_reg_3181}}, {trunc_ln46_23_reg_3176}}, {trunc_ln46_22_reg_3171}}, {trunc_ln46_21_reg_3166}}, {tmp_598_reg_3356}}, 
    {tmp_599_reg_3361}}, {trunc_ln46_20_reg_3161}}, {trunc_ln46_19_reg_3156}}, {trunc_ln46_18_reg_3151}}, {trunc_ln46_17_reg_3146}}, {trunc_ln46_16_reg_3141}}, {trunc_ln46_15_reg_3136}}, {tmp_600_reg_3366}}, {tmp_601_reg_3371}}, {trunc_ln46_14_reg_3131}}, {trunc_ln46_13_reg_3126}}, {trunc_ln46_12_reg_3121}}, {trunc_ln46_11_reg_3116}}, {tmp_602_reg_3376}}, {tmp_603_reg_3381}}, {trunc_ln46_10_reg_3111}}, {trunc_ln46_9_reg_3106}}, {trunc_ln46_8_reg_3101}}, {trunc_ln46_7_reg_3096}}, {trunc_ln46_6_reg_3091}}, {trunc_ln46_5_reg_3086}}, {tmp_604_reg_3386}}, {trunc_ln46_4_reg_3081}}, {tmp_605_reg_3391}}, {tmp_606_reg_3396}}, {trunc_ln46_3_reg_3076}}, {trunc_ln46_2_reg_3071}}, {trunc_ln46_1_reg_3066}}, {trunc_ln46_s_reg_3061}}, {tmp_607_reg_3401}}, {tmp_590_reg_3316}}, {tmp_608_reg_3406}}, {trunc_ln41_11_reg_3056}}, {tmp_591_reg_3321}}, {tmp_609_reg_3411}}, {trunc_ln41_10_reg_3051}}, {trunc_ln41_3_reg_3046}}, {trunc_ln41_2_reg_3041}}, {trunc_ln41_1_reg_3036}}, {trunc_ln41_s_reg_3031}}, {trunc_ln41_9_reg_3026}}, {trunc_ln41_8_reg_3021}}, 
    {trunc_ln41_7_reg_3016}}, {trunc_ln41_6_reg_3011}}, {trunc_ln41_5_reg_3006}}, {trunc_ln41_4_reg_3001}}, {trunc_ln_reg_2996}};

assign start_out = real_start;

assign tmp_524_fu_471_p4 = {{layer14_out_dout[69:48]}};

assign tmp_525_fu_505_p4 = {{layer14_out_dout[93:72]}};

assign tmp_526_fu_539_p4 = {{layer14_out_dout[117:96]}};

assign tmp_527_fu_573_p4 = {{layer14_out_dout[141:120]}};

assign tmp_528_fu_607_p4 = {{layer14_out_dout[165:144]}};

assign tmp_529_fu_641_p4 = {{layer14_out_dout[189:168]}};

assign tmp_530_fu_675_p4 = {{layer14_out_dout[213:192]}};

assign tmp_531_fu_709_p4 = {{layer14_out_dout[238:216]}};

assign tmp_532_fu_743_p4 = {{layer14_out_dout[261:240]}};

assign tmp_533_fu_777_p4 = {{layer14_out_dout[285:264]}};

assign tmp_534_fu_811_p4 = {{layer14_out_dout[309:288]}};

assign tmp_535_fu_835_p4 = {{layer14_out_dout[333:312]}};

assign tmp_536_fu_869_p4 = {{layer14_out_dout[406:384]}};

assign tmp_537_fu_893_p4 = {{layer14_out_dout[429:408]}};

assign tmp_538_fu_917_p4 = {{layer14_out_dout[477:456]}};

assign tmp_539_fu_941_p4 = {{layer14_out_dout[501:480]}};

assign tmp_540_fu_965_p4 = {{layer14_out_dout[525:504]}};

assign tmp_541_fu_989_p4 = {{layer14_out_dout[550:528]}};

assign tmp_542_fu_1013_p4 = {{layer14_out_dout[574:552]}};

assign tmp_543_fu_1037_p4 = {{layer14_out_dout[621:600]}};

assign tmp_544_fu_1061_p4 = {{layer14_out_dout[694:672]}};

assign tmp_545_fu_1085_p4 = {{layer14_out_dout[717:696]}};

assign tmp_546_fu_1109_p4 = {{layer14_out_dout[741:720]}};

assign tmp_547_fu_1133_p4 = {{layer14_out_dout[765:744]}};

assign tmp_548_fu_1157_p4 = {{layer14_out_dout[789:768]}};

assign tmp_549_fu_1181_p4 = {{layer14_out_dout[813:792]}};

assign tmp_550_fu_1205_p4 = {{layer14_out_dout[861:840]}};

assign tmp_551_fu_1229_p4 = {{layer14_out_dout[886:864]}};

assign tmp_552_fu_1253_p4 = {{layer14_out_dout[909:888]}};

assign tmp_553_fu_1277_p4 = {{layer14_out_dout[933:912]}};

assign tmp_554_fu_1301_p4 = {{layer14_out_dout[957:936]}};

assign tmp_555_fu_1325_p4 = {{layer14_out_dout[1005:984]}};

assign tmp_556_fu_1349_p4 = {{layer14_out_dout[1029:1008]}};

assign tmp_557_fu_1373_p4 = {{layer14_out_dout[1053:1032]}};

assign tmp_558_fu_1397_p4 = {{layer14_out_dout[1077:1056]}};

assign tmp_559_fu_1421_p4 = {{layer14_out_dout[1101:1080]}};

assign tmp_560_fu_1445_p4 = {{layer14_out_dout[1125:1104]}};

assign tmp_561_fu_1469_p4 = {{layer14_out_dout[1149:1128]}};

assign tmp_562_fu_1493_p4 = {{layer14_out_dout[1197:1176]}};

assign tmp_563_fu_1517_p4 = {{layer14_out_dout[1221:1200]}};

assign tmp_564_fu_1541_p4 = {{layer14_out_dout[1245:1224]}};

assign tmp_565_fu_1565_p4 = {{layer14_out_dout[1270:1248]}};

assign tmp_566_fu_1589_p4 = {{layer14_out_dout[1293:1272]}};

assign tmp_567_fu_1613_p4 = {{layer14_out_dout[1366:1344]}};

assign tmp_568_fu_1637_p4 = {{layer14_out_dout[1389:1368]}};

assign tmp_569_fu_1661_p4 = {{layer14_out_dout[1413:1392]}};

assign tmp_570_fu_1685_p4 = {{layer14_out_dout[1437:1416]}};

assign tmp_571_fu_1709_p4 = {{layer14_out_dout[1461:1440]}};

assign tmp_572_fu_1733_p4 = {{layer14_out_dout[1485:1464]}};

assign tmp_573_fu_1757_p4 = {{layer14_out_dout[1510:1488]}};

assign tmp_574_fu_1781_p4 = {{layer14_out_dout[1533:1512]}};

assign tmp_575_fu_1805_p4 = {{layer14_out_dout[1557:1536]}};

assign tmp_576_fu_1829_p4 = {{layer14_out_dout[1582:1560]}};

assign tmp_577_fu_1853_p4 = {{layer14_out_dout[1606:1584]}};

assign tmp_578_fu_1877_p4 = {{layer14_out_dout[1629:1608]}};

assign tmp_579_fu_1901_p4 = {{layer14_out_dout[1653:1632]}};

assign tmp_580_fu_1925_p4 = {{layer14_out_dout[1677:1656]}};

assign tmp_581_fu_1949_p4 = {{layer14_out_dout[1701:1680]}};

assign tmp_582_fu_1973_p4 = {{layer14_out_dout[1725:1704]}};

assign tmp_583_fu_1997_p4 = {{layer14_out_dout[1749:1728]}};

assign tmp_584_fu_2021_p4 = {{layer14_out_dout[1821:1800]}};

assign tmp_585_fu_2045_p4 = {{layer14_out_dout[1845:1824]}};

assign tmp_586_fu_2069_p4 = {{layer14_out_dout[1869:1848]}};

assign tmp_587_fu_2093_p4 = {{layer14_out_dout[1893:1872]}};

assign tmp_588_fu_2117_p4 = {{layer14_out_dout[1941:1920]}};

assign tmp_589_fu_2141_p4 = {{layer14_out_dout[1965:1944]}};

assign tmp_s_fu_437_p4 = {{layer14_out_dout[46:24]}};

assign trunc_ln1_fu_2165_p4 = {{layer14_out_dout[1989:1955]}};

assign trunc_ln85_2_fu_2181_p4 = {{layer14_out_dout[2013:1979]}};

assign trunc_ln85_fu_409_p1 = layer14_out_dout[21:0];

assign y_10_fu_753_p3 = {{tmp_532_fu_743_p4}, {13'd0}};

assign y_11_fu_787_p3 = {{tmp_533_fu_777_p4}, {13'd0}};

assign y_12_fu_821_p3 = {{tmp_534_fu_811_p4}, {13'd0}};

assign y_13_fu_845_p3 = {{tmp_535_fu_835_p4}, {13'd0}};

assign y_14_fu_879_p3 = {{tmp_536_fu_869_p4}, {12'd0}};

assign y_15_fu_903_p3 = {{tmp_537_fu_893_p4}, {13'd0}};

assign y_16_fu_927_p3 = {{tmp_538_fu_917_p4}, {13'd0}};

assign y_17_fu_951_p3 = {{tmp_539_fu_941_p4}, {13'd0}};

assign y_18_fu_975_p3 = {{tmp_540_fu_965_p4}, {13'd0}};

assign y_19_fu_999_p3 = {{tmp_541_fu_989_p4}, {12'd0}};

assign y_1_fu_447_p3 = {{tmp_s_fu_437_p4}, {12'd0}};

assign y_20_fu_1023_p3 = {{tmp_542_fu_1013_p4}, {12'd0}};

assign y_21_fu_1047_p3 = {{tmp_543_fu_1037_p4}, {13'd0}};

assign y_22_fu_1071_p3 = {{tmp_544_fu_1061_p4}, {12'd0}};

assign y_23_fu_1095_p3 = {{tmp_545_fu_1085_p4}, {13'd0}};

assign y_24_fu_1119_p3 = {{tmp_546_fu_1109_p4}, {13'd0}};

assign y_25_fu_1143_p3 = {{tmp_547_fu_1133_p4}, {13'd0}};

assign y_26_fu_1167_p3 = {{tmp_548_fu_1157_p4}, {13'd0}};

assign y_27_fu_1191_p3 = {{tmp_549_fu_1181_p4}, {13'd0}};

assign y_28_fu_1215_p3 = {{tmp_550_fu_1205_p4}, {13'd0}};

assign y_29_fu_1239_p3 = {{tmp_551_fu_1229_p4}, {12'd0}};

assign y_2_fu_481_p3 = {{tmp_524_fu_471_p4}, {13'd0}};

assign y_30_fu_1263_p3 = {{tmp_552_fu_1253_p4}, {13'd0}};

assign y_31_fu_1287_p3 = {{tmp_553_fu_1277_p4}, {13'd0}};

assign y_32_fu_1311_p3 = {{tmp_554_fu_1301_p4}, {13'd0}};

assign y_33_fu_1335_p3 = {{tmp_555_fu_1325_p4}, {13'd0}};

assign y_34_fu_1359_p3 = {{tmp_556_fu_1349_p4}, {13'd0}};

assign y_35_fu_1383_p3 = {{tmp_557_fu_1373_p4}, {13'd0}};

assign y_36_fu_1407_p3 = {{tmp_558_fu_1397_p4}, {13'd0}};

assign y_37_fu_1431_p3 = {{tmp_559_fu_1421_p4}, {13'd0}};

assign y_38_fu_1455_p3 = {{tmp_560_fu_1445_p4}, {13'd0}};

assign y_39_fu_1479_p3 = {{tmp_561_fu_1469_p4}, {13'd0}};

assign y_3_fu_515_p3 = {{tmp_525_fu_505_p4}, {13'd0}};

assign y_40_fu_1503_p3 = {{tmp_562_fu_1493_p4}, {13'd0}};

assign y_41_fu_1527_p3 = {{tmp_563_fu_1517_p4}, {13'd0}};

assign y_42_fu_1551_p3 = {{tmp_564_fu_1541_p4}, {13'd0}};

assign y_43_fu_1575_p3 = {{tmp_565_fu_1565_p4}, {12'd0}};

assign y_44_fu_1599_p3 = {{tmp_566_fu_1589_p4}, {13'd0}};

assign y_45_fu_1623_p3 = {{tmp_567_fu_1613_p4}, {12'd0}};

assign y_46_fu_1647_p3 = {{tmp_568_fu_1637_p4}, {13'd0}};

assign y_47_fu_1671_p3 = {{tmp_569_fu_1661_p4}, {13'd0}};

assign y_48_fu_1695_p3 = {{tmp_570_fu_1685_p4}, {13'd0}};

assign y_49_fu_1719_p3 = {{tmp_571_fu_1709_p4}, {13'd0}};

assign y_4_fu_549_p3 = {{tmp_526_fu_539_p4}, {13'd0}};

assign y_50_fu_1743_p3 = {{tmp_572_fu_1733_p4}, {13'd0}};

assign y_51_fu_1767_p3 = {{tmp_573_fu_1757_p4}, {12'd0}};

assign y_52_fu_1791_p3 = {{tmp_574_fu_1781_p4}, {13'd0}};

assign y_53_fu_1815_p3 = {{tmp_575_fu_1805_p4}, {13'd0}};

assign y_54_fu_1839_p3 = {{tmp_576_fu_1829_p4}, {12'd0}};

assign y_55_fu_1863_p3 = {{tmp_577_fu_1853_p4}, {12'd0}};

assign y_56_fu_1887_p3 = {{tmp_578_fu_1877_p4}, {13'd0}};

assign y_57_fu_1911_p3 = {{tmp_579_fu_1901_p4}, {13'd0}};

assign y_58_fu_1935_p3 = {{tmp_580_fu_1925_p4}, {13'd0}};

assign y_59_fu_1959_p3 = {{tmp_581_fu_1949_p4}, {13'd0}};

assign y_5_fu_583_p3 = {{tmp_527_fu_573_p4}, {13'd0}};

assign y_60_fu_1983_p3 = {{tmp_582_fu_1973_p4}, {13'd0}};

assign y_61_fu_2007_p3 = {{tmp_583_fu_1997_p4}, {13'd0}};

assign y_62_fu_2031_p3 = {{tmp_584_fu_2021_p4}, {13'd0}};

assign y_63_fu_2055_p3 = {{tmp_585_fu_2045_p4}, {13'd0}};

assign y_64_fu_2079_p3 = {{tmp_586_fu_2069_p4}, {13'd0}};

assign y_65_fu_2103_p3 = {{tmp_587_fu_2093_p4}, {13'd0}};

assign y_66_fu_2127_p3 = {{tmp_588_fu_2117_p4}, {13'd0}};

assign y_67_fu_2151_p3 = {{tmp_589_fu_2141_p4}, {13'd0}};

assign y_6_fu_617_p3 = {{tmp_528_fu_607_p4}, {13'd0}};

assign y_7_fu_651_p3 = {{tmp_529_fu_641_p4}, {13'd0}};

assign y_8_fu_685_p3 = {{tmp_530_fu_675_p4}, {13'd0}};

assign y_9_fu_719_p3 = {{tmp_531_fu_709_p4}, {12'd0}};

assign y_fu_413_p3 = {{trunc_ln85_fu_409_p1}, {13'd0}};

endmodule //myproject_normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_s
