// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject_myproject,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.723062,HLS_SYN_LAT=5516,HLS_SYN_TPT=5492,HLS_SYN_MEM=227,HLS_SYN_DSP=0,HLS_SYN_FF=77205,HLS_SYN_LUT=171890,HLS_VERSION=2023_1}" *)

module myproject (
        q_conv2d_input_TDATA,
        layer19_out_TDATA,
        ap_clk,
        ap_rst_n,
        q_conv2d_input_TVALID,
        q_conv2d_input_TREADY,
        ap_start,
        layer19_out_TVALID,
        layer19_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [15:0] q_conv2d_input_TDATA;
output  [159:0] layer19_out_TDATA;
input   ap_clk;
input   ap_rst_n;
input   q_conv2d_input_TVALID;
output   q_conv2d_input_TREADY;
input   ap_start;
output   layer19_out_TVALID;
input   layer19_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_ap_start;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_ap_done;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_ap_continue;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_ap_idle;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_ap_ready;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_start_out;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_start_write;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_q_conv2d_input_TREADY;
wire   [179:0] conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_layer2_out_din;
wire    conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_layer2_out_write;
wire    normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_ap_start;
wire    normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_ap_done;
wire    normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_ap_continue;
wire    normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_ap_idle;
wire    normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_ap_ready;
wire    normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_layer2_out_read;
wire   [95:0] normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_layer20_out_din;
wire    normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_layer20_out_write;
wire    normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_start_out;
wire    normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_start_write;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_ap_start;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_ap_done;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_ap_continue;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_ap_idle;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_ap_ready;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_layer20_out_read;
wire   [47:0] relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_layer4_out_din;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_layer4_out_write;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_start_out;
wire    relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_start_write;
wire    pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_ap_start;
wire    pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_ap_done;
wire    pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_ap_continue;
wire    pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_ap_idle;
wire    pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_ap_ready;
wire    pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_layer4_out_read;
wire   [47:0] pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_layer5_out_din;
wire    pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_layer5_out_write;
wire    pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_start_out;
wire    pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_start_write;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_ap_start;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_ap_done;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_ap_continue;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_ap_idle;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_ap_ready;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_start_out;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_start_write;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_layer5_out_read;
wire   [399:0] conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_layer6_out_din;
wire    conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_layer6_out_write;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_ap_start;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_ap_done;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_ap_continue;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_ap_idle;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_ap_ready;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_layer6_out_read;
wire   [255:0] normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_layer21_out_din;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_layer21_out_write;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_start_out;
wire    normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_start_write;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_ap_start;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_ap_done;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_ap_continue;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_ap_idle;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_ap_ready;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_layer21_out_read;
wire   [127:0] relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_layer8_out_din;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_layer8_out_write;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_start_out;
wire    relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_start_write;
wire    pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_ap_start;
wire    pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_ap_done;
wire    pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_ap_continue;
wire    pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_ap_idle;
wire    pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_ap_ready;
wire    pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_layer8_out_read;
wire   [127:0] pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_layer9_out_din;
wire    pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_layer9_out_write;
wire    pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_start_out;
wire    pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_start_write;
wire    dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_ap_start;
wire    dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_ap_done;
wire    dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_ap_continue;
wire    dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_ap_idle;
wire    dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_ap_ready;
wire    dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_start_out;
wire    dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_start_write;
wire    dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_layer9_out_read;
wire   [2999:0] dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_layer11_out_din;
wire    dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_layer11_out_write;
wire    normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_ap_start;
wire    normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_ap_done;
wire    normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_ap_continue;
wire    normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_ap_idle;
wire    normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_ap_ready;
wire    normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_start_out;
wire    normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_start_write;
wire    normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_layer11_out_read;
wire   [1919:0] normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_layer22_out_din;
wire    normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_layer22_out_write;
wire    relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_ap_start;
wire    relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_ap_done;
wire    relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_ap_continue;
wire    relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_ap_idle;
wire    relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_ap_ready;
wire    relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_start_out;
wire    relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_start_write;
wire    relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_layer22_out_read;
wire   [959:0] relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_layer13_out_din;
wire    relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_layer13_out_write;
wire    dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_ap_start;
wire    dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_ap_done;
wire    dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_ap_continue;
wire    dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_ap_idle;
wire    dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_ap_ready;
wire    dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_layer13_out_read;
wire   [2015:0] dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_layer14_out_din;
wire    dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_layer14_out_write;
wire    dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_start_out;
wire    dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_start_write;
wire    normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_ap_start;
wire    normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_ap_done;
wire    normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_ap_continue;
wire    normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_ap_idle;
wire    normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_ap_ready;
wire    normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_start_out;
wire    normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_start_write;
wire    normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_layer14_out_read;
wire   [1343:0] normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_layer23_out_din;
wire    normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_layer23_out_write;
wire    relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_ap_start;
wire    relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_ap_done;
wire    relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_ap_continue;
wire    relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_ap_idle;
wire    relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_ap_ready;
wire    relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_start_out;
wire    relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_start_write;
wire    relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_layer23_out_read;
wire   [671:0] relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_layer16_out_din;
wire    relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_layer16_out_write;
wire    dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_ap_start;
wire    dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_ap_done;
wire    dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_ap_continue;
wire    dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_ap_idle;
wire    dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_ap_ready;
wire    dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_start_out;
wire    dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_start_write;
wire    dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_layer16_out_read;
wire   [159:0] dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_layer17_out_din;
wire    dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_layer17_out_write;
wire    normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_ap_start;
wire    normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_ap_done;
wire    normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_ap_continue;
wire    normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_ap_idle;
wire    normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_ap_ready;
wire    normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_start_out;
wire    normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_start_write;
wire    normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_layer17_out_read;
wire   [159:0] normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_layer24_out_din;
wire    normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_layer24_out_write;
wire    softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_ap_start;
wire    softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_ap_done;
wire    softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_ap_continue;
wire    softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_ap_idle;
wire    softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_ap_ready;
wire    softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_layer24_out_read;
wire   [159:0] softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_layer19_out_TDATA;
wire    softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_layer19_out_TVALID;
wire    layer2_out_full_n;
wire   [179:0] layer2_out_dout;
wire   [10:0] layer2_out_num_data_valid;
wire   [10:0] layer2_out_fifo_cap;
wire    layer2_out_empty_n;
wire    layer20_out_full_n;
wire   [95:0] layer20_out_dout;
wire   [10:0] layer20_out_num_data_valid;
wire   [10:0] layer20_out_fifo_cap;
wire    layer20_out_empty_n;
wire    layer4_out_full_n;
wire   [47:0] layer4_out_dout;
wire   [10:0] layer4_out_num_data_valid;
wire   [10:0] layer4_out_fifo_cap;
wire    layer4_out_empty_n;
wire    layer5_out_full_n;
wire   [47:0] layer5_out_dout;
wire   [8:0] layer5_out_num_data_valid;
wire   [8:0] layer5_out_fifo_cap;
wire    layer5_out_empty_n;
wire    layer6_out_full_n;
wire   [399:0] layer6_out_dout;
wire   [6:0] layer6_out_num_data_valid;
wire   [6:0] layer6_out_fifo_cap;
wire    layer6_out_empty_n;
wire    layer21_out_full_n;
wire   [255:0] layer21_out_dout;
wire   [6:0] layer21_out_num_data_valid;
wire   [6:0] layer21_out_fifo_cap;
wire    layer21_out_empty_n;
wire    layer8_out_full_n;
wire   [127:0] layer8_out_dout;
wire   [6:0] layer8_out_num_data_valid;
wire   [6:0] layer8_out_fifo_cap;
wire    layer8_out_empty_n;
wire    layer9_out_full_n;
wire   [127:0] layer9_out_dout;
wire   [4:0] layer9_out_num_data_valid;
wire   [4:0] layer9_out_fifo_cap;
wire    layer9_out_empty_n;
wire    layer11_out_full_n;
wire   [2999:0] layer11_out_dout;
wire   [1:0] layer11_out_num_data_valid;
wire   [1:0] layer11_out_fifo_cap;
wire    layer11_out_empty_n;
wire    layer22_out_full_n;
wire   [1919:0] layer22_out_dout;
wire   [1:0] layer22_out_num_data_valid;
wire   [1:0] layer22_out_fifo_cap;
wire    layer22_out_empty_n;
wire    layer13_out_full_n;
wire   [959:0] layer13_out_dout;
wire   [1:0] layer13_out_num_data_valid;
wire   [1:0] layer13_out_fifo_cap;
wire    layer13_out_empty_n;
wire    layer14_out_full_n;
wire   [2015:0] layer14_out_dout;
wire   [1:0] layer14_out_num_data_valid;
wire   [1:0] layer14_out_fifo_cap;
wire    layer14_out_empty_n;
wire    layer23_out_full_n;
wire   [1343:0] layer23_out_dout;
wire   [1:0] layer23_out_num_data_valid;
wire   [1:0] layer23_out_fifo_cap;
wire    layer23_out_empty_n;
wire    layer16_out_full_n;
wire   [671:0] layer16_out_dout;
wire   [1:0] layer16_out_num_data_valid;
wire   [1:0] layer16_out_fifo_cap;
wire    layer16_out_empty_n;
wire    layer17_out_full_n;
wire   [159:0] layer17_out_dout;
wire   [1:0] layer17_out_num_data_valid;
wire   [1:0] layer17_out_fifo_cap;
wire    layer17_out_empty_n;
wire    layer24_out_full_n;
wire   [159:0] layer24_out_dout;
wire   [1:0] layer24_out_num_data_valid;
wire   [1:0] layer24_out_fifo_cap;
wire    layer24_out_empty_n;
wire   [0:0] start_for_normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_din;
wire    start_for_normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_full_n;
wire   [0:0] start_for_normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_dout;
wire    start_for_normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_din;
wire    start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_dout;
wire    start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_empty_n;
wire   [0:0] start_for_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_din;
wire    start_for_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_full_n;
wire   [0:0] start_for_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_dout;
wire    start_for_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_empty_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_din;
wire    start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_full_n;
wire   [0:0] start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_dout;
wire    start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_empty_n;
wire   [0:0] start_for_normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_din;
wire    start_for_normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_full_n;
wire   [0:0] start_for_normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_dout;
wire    start_for_normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_din;
wire    start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_dout;
wire    start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_empty_n;
wire   [0:0] start_for_pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_din;
wire    start_for_pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_full_n;
wire   [0:0] start_for_pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_dout;
wire    start_for_pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_din;
wire    start_for_dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_full_n;
wire   [0:0] start_for_dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_dout;
wire    start_for_dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_empty_n;
wire   [0:0] start_for_normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_din;
wire    start_for_normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_full_n;
wire   [0:0] start_for_normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_dout;
wire    start_for_normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_empty_n;
wire   [0:0] start_for_relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_din;
wire    start_for_relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_full_n;
wire   [0:0] start_for_relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_dout;
wire    start_for_relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_din;
wire    start_for_dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_full_n;
wire   [0:0] start_for_dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_dout;
wire    start_for_dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_empty_n;
wire   [0:0] start_for_normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_din;
wire    start_for_normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_full_n;
wire   [0:0] start_for_normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_dout;
wire    start_for_normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_empty_n;
wire   [0:0] start_for_relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_din;
wire    start_for_relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_full_n;
wire   [0:0] start_for_relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_dout;
wire    start_for_relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_empty_n;
wire   [0:0] start_for_dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_din;
wire    start_for_dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_full_n;
wire   [0:0] start_for_dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_dout;
wire    start_for_dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_empty_n;
wire   [0:0] start_for_normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_din;
wire    start_for_normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_full_n;
wire   [0:0] start_for_normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_dout;
wire    start_for_normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_empty_n;
wire   [0:0] start_for_softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_din;
wire    start_for_softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_full_n;
wire   [0:0] start_for_softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_dout;
wire    start_for_softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_empty_n;

myproject_conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_s conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_ap_start),
    .start_full_n(start_for_normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_ap_ready),
    .q_conv2d_input_TVALID(q_conv2d_input_TVALID),
    .start_out(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_start_out),
    .start_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_start_write),
    .q_conv2d_input_TDATA(q_conv2d_input_TDATA),
    .q_conv2d_input_TREADY(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_q_conv2d_input_TREADY),
    .layer2_out_din(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_layer2_out_din),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_full_n(layer2_out_full_n),
    .layer2_out_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_layer2_out_write)
);

myproject_normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_s normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_full_n),
    .ap_done(normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_ap_done),
    .ap_continue(normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_ap_continue),
    .ap_idle(normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_ap_idle),
    .ap_ready(normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_ap_ready),
    .layer2_out_dout(layer2_out_dout),
    .layer2_out_num_data_valid(layer2_out_num_data_valid),
    .layer2_out_fifo_cap(layer2_out_fifo_cap),
    .layer2_out_empty_n(layer2_out_empty_n),
    .layer2_out_read(normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_layer2_out_read),
    .layer20_out_din(normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_layer20_out_din),
    .layer20_out_num_data_valid(layer20_out_num_data_valid),
    .layer20_out_fifo_cap(layer20_out_fifo_cap),
    .layer20_out_full_n(layer20_out_full_n),
    .layer20_out_write(normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_layer20_out_write),
    .start_out(normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_start_out),
    .start_write(normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_start_write)
);

myproject_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_s relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_ap_start),
    .start_full_n(start_for_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_full_n),
    .ap_done(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_ap_ready),
    .layer20_out_dout(layer20_out_dout),
    .layer20_out_num_data_valid(layer20_out_num_data_valid),
    .layer20_out_fifo_cap(layer20_out_fifo_cap),
    .layer20_out_empty_n(layer20_out_empty_n),
    .layer20_out_read(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_layer20_out_read),
    .layer4_out_din(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_layer4_out_din),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_full_n(layer4_out_full_n),
    .layer4_out_write(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_layer4_out_write),
    .start_out(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_start_out),
    .start_write(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_start_write)
);

myproject_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_s pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_ap_start),
    .start_full_n(start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_full_n),
    .ap_done(pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_ap_done),
    .ap_continue(pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_ap_continue),
    .ap_idle(pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_ap_idle),
    .ap_ready(pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_ap_ready),
    .layer4_out_dout(layer4_out_dout),
    .layer4_out_num_data_valid(layer4_out_num_data_valid),
    .layer4_out_fifo_cap(layer4_out_fifo_cap),
    .layer4_out_empty_n(layer4_out_empty_n),
    .layer4_out_read(pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_layer4_out_read),
    .layer5_out_din(pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_layer5_out_din),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_full_n(layer5_out_full_n),
    .layer5_out_write(pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_layer5_out_write),
    .start_out(pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_start_out),
    .start_write(pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_start_write)
);

myproject_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_s conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_ap_start),
    .start_full_n(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_full_n),
    .ap_done(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_ap_done),
    .ap_continue(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_ap_continue),
    .ap_idle(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_ap_idle),
    .ap_ready(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_ap_ready),
    .start_out(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_start_out),
    .start_write(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_start_write),
    .layer5_out_dout(layer5_out_dout),
    .layer5_out_num_data_valid(layer5_out_num_data_valid),
    .layer5_out_fifo_cap(layer5_out_fifo_cap),
    .layer5_out_empty_n(layer5_out_empty_n),
    .layer5_out_read(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_layer5_out_read),
    .layer6_out_din(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_layer6_out_din),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap),
    .layer6_out_full_n(layer6_out_full_n),
    .layer6_out_write(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_layer6_out_write)
);

myproject_normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_s normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_full_n),
    .ap_done(normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_ap_done),
    .ap_continue(normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_ap_continue),
    .ap_idle(normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_ap_idle),
    .ap_ready(normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_ap_ready),
    .layer6_out_dout(layer6_out_dout),
    .layer6_out_num_data_valid(layer6_out_num_data_valid),
    .layer6_out_fifo_cap(layer6_out_fifo_cap),
    .layer6_out_empty_n(layer6_out_empty_n),
    .layer6_out_read(normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_layer6_out_read),
    .layer21_out_din(normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_layer21_out_din),
    .layer21_out_num_data_valid(layer21_out_num_data_valid),
    .layer21_out_fifo_cap(layer21_out_fifo_cap),
    .layer21_out_full_n(layer21_out_full_n),
    .layer21_out_write(normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_layer21_out_write),
    .start_out(normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_start_out),
    .start_write(normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_start_write)
);

myproject_relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_s relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_ap_start),
    .start_full_n(start_for_pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_full_n),
    .ap_done(relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_ap_ready),
    .layer21_out_dout(layer21_out_dout),
    .layer21_out_num_data_valid(layer21_out_num_data_valid),
    .layer21_out_fifo_cap(layer21_out_fifo_cap),
    .layer21_out_empty_n(layer21_out_empty_n),
    .layer21_out_read(relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_layer21_out_read),
    .layer8_out_din(relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_layer8_out_din),
    .layer8_out_num_data_valid(layer8_out_num_data_valid),
    .layer8_out_fifo_cap(layer8_out_fifo_cap),
    .layer8_out_full_n(layer8_out_full_n),
    .layer8_out_write(relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_layer8_out_write),
    .start_out(relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_start_out),
    .start_write(relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_start_write)
);

myproject_pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_s pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_full_n),
    .ap_done(pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_ap_done),
    .ap_continue(pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_ap_continue),
    .ap_idle(pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_ap_idle),
    .ap_ready(pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_ap_ready),
    .layer8_out_dout(layer8_out_dout),
    .layer8_out_num_data_valid(layer8_out_num_data_valid),
    .layer8_out_fifo_cap(layer8_out_fifo_cap),
    .layer8_out_empty_n(layer8_out_empty_n),
    .layer8_out_read(pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_layer8_out_read),
    .layer9_out_din(pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_layer9_out_din),
    .layer9_out_num_data_valid(layer9_out_num_data_valid),
    .layer9_out_fifo_cap(layer9_out_fifo_cap),
    .layer9_out_full_n(layer9_out_full_n),
    .layer9_out_write(pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_layer9_out_write),
    .start_out(pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_start_out),
    .start_write(pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_start_write)
);

myproject_dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_s dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_ap_start),
    .start_full_n(start_for_normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_full_n),
    .ap_done(dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_ap_done),
    .ap_continue(dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_ap_continue),
    .ap_idle(dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_ap_idle),
    .ap_ready(dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_ap_ready),
    .start_out(dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_start_out),
    .start_write(dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_start_write),
    .layer9_out_dout(layer9_out_dout),
    .layer9_out_num_data_valid(layer9_out_num_data_valid),
    .layer9_out_fifo_cap(layer9_out_fifo_cap),
    .layer9_out_empty_n(layer9_out_empty_n),
    .layer9_out_read(dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_layer9_out_read),
    .layer11_out_din(dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_layer11_out_din),
    .layer11_out_num_data_valid(layer11_out_num_data_valid),
    .layer11_out_fifo_cap(layer11_out_fifo_cap),
    .layer11_out_full_n(layer11_out_full_n),
    .layer11_out_write(dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_layer11_out_write)
);

myproject_normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_s normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_ap_start),
    .start_full_n(start_for_relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_full_n),
    .ap_done(normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_ap_done),
    .ap_continue(normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_ap_continue),
    .ap_idle(normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_ap_idle),
    .ap_ready(normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_ap_ready),
    .start_out(normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_start_out),
    .start_write(normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_start_write),
    .layer11_out_dout(layer11_out_dout),
    .layer11_out_num_data_valid(layer11_out_num_data_valid),
    .layer11_out_fifo_cap(layer11_out_fifo_cap),
    .layer11_out_empty_n(layer11_out_empty_n),
    .layer11_out_read(normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_layer11_out_read),
    .layer22_out_din(normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_layer22_out_din),
    .layer22_out_num_data_valid(layer22_out_num_data_valid),
    .layer22_out_fifo_cap(layer22_out_fifo_cap),
    .layer22_out_full_n(layer22_out_full_n),
    .layer22_out_write(normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_layer22_out_write)
);

myproject_relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_s relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_full_n),
    .ap_done(relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_ap_done),
    .ap_continue(relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_ap_continue),
    .ap_idle(relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_ap_idle),
    .ap_ready(relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_ap_ready),
    .start_out(relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_start_out),
    .start_write(relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_start_write),
    .layer22_out_dout(layer22_out_dout),
    .layer22_out_num_data_valid(layer22_out_num_data_valid),
    .layer22_out_fifo_cap(layer22_out_fifo_cap),
    .layer22_out_empty_n(layer22_out_empty_n),
    .layer22_out_read(relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_layer22_out_read),
    .layer13_out_din(relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_layer13_out_din),
    .layer13_out_num_data_valid(layer13_out_num_data_valid),
    .layer13_out_fifo_cap(layer13_out_fifo_cap),
    .layer13_out_full_n(layer13_out_full_n),
    .layer13_out_write(relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_layer13_out_write)
);

myproject_dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_s dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_ap_start),
    .start_full_n(start_for_normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_full_n),
    .ap_done(dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_ap_done),
    .ap_continue(dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_ap_continue),
    .ap_idle(dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_ap_idle),
    .ap_ready(dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_ap_ready),
    .layer13_out_dout(layer13_out_dout),
    .layer13_out_num_data_valid(layer13_out_num_data_valid),
    .layer13_out_fifo_cap(layer13_out_fifo_cap),
    .layer13_out_empty_n(layer13_out_empty_n),
    .layer13_out_read(dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_layer13_out_read),
    .layer14_out_din(dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_layer14_out_din),
    .layer14_out_num_data_valid(layer14_out_num_data_valid),
    .layer14_out_fifo_cap(layer14_out_fifo_cap),
    .layer14_out_full_n(layer14_out_full_n),
    .layer14_out_write(dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_layer14_out_write),
    .start_out(dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_start_out),
    .start_write(dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_start_write)
);

myproject_normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_s normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_ap_start),
    .start_full_n(start_for_relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_full_n),
    .ap_done(normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_ap_done),
    .ap_continue(normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_ap_continue),
    .ap_idle(normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_ap_idle),
    .ap_ready(normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_ap_ready),
    .start_out(normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_start_out),
    .start_write(normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_start_write),
    .layer14_out_dout(layer14_out_dout),
    .layer14_out_num_data_valid(layer14_out_num_data_valid),
    .layer14_out_fifo_cap(layer14_out_fifo_cap),
    .layer14_out_empty_n(layer14_out_empty_n),
    .layer14_out_read(normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_layer14_out_read),
    .layer23_out_din(normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_layer23_out_din),
    .layer23_out_num_data_valid(layer23_out_num_data_valid),
    .layer23_out_fifo_cap(layer23_out_fifo_cap),
    .layer23_out_full_n(layer23_out_full_n),
    .layer23_out_write(normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_layer23_out_write)
);

myproject_relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_s relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_ap_start),
    .start_full_n(start_for_dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_full_n),
    .ap_done(relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_ap_ready),
    .start_out(relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_start_out),
    .start_write(relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_start_write),
    .layer23_out_dout(layer23_out_dout),
    .layer23_out_num_data_valid(layer23_out_num_data_valid),
    .layer23_out_fifo_cap(layer23_out_fifo_cap),
    .layer23_out_empty_n(layer23_out_empty_n),
    .layer23_out_read(relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_layer23_out_read),
    .layer16_out_din(relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_layer16_out_din),
    .layer16_out_num_data_valid(layer16_out_num_data_valid),
    .layer16_out_fifo_cap(layer16_out_fifo_cap),
    .layer16_out_full_n(layer16_out_full_n),
    .layer16_out_write(relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_layer16_out_write)
);

myproject_dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_s dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_ap_start),
    .start_full_n(start_for_normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_full_n),
    .ap_done(dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_ap_done),
    .ap_continue(dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_ap_continue),
    .ap_idle(dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_ap_idle),
    .ap_ready(dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_ap_ready),
    .start_out(dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_start_out),
    .start_write(dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_start_write),
    .layer16_out_dout(layer16_out_dout),
    .layer16_out_num_data_valid(layer16_out_num_data_valid),
    .layer16_out_fifo_cap(layer16_out_fifo_cap),
    .layer16_out_empty_n(layer16_out_empty_n),
    .layer16_out_read(dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_layer16_out_read),
    .layer17_out_din(dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_layer17_out_din),
    .layer17_out_num_data_valid(layer17_out_num_data_valid),
    .layer17_out_fifo_cap(layer17_out_fifo_cap),
    .layer17_out_full_n(layer17_out_full_n),
    .layer17_out_write(dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_layer17_out_write)
);

myproject_normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_s normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_ap_start),
    .start_full_n(start_for_softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_full_n),
    .ap_done(normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_ap_done),
    .ap_continue(normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_ap_continue),
    .ap_idle(normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_ap_idle),
    .ap_ready(normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_ap_ready),
    .start_out(normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_start_out),
    .start_write(normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_start_write),
    .layer17_out_dout(layer17_out_dout),
    .layer17_out_num_data_valid(layer17_out_num_data_valid),
    .layer17_out_fifo_cap(layer17_out_fifo_cap),
    .layer17_out_empty_n(layer17_out_empty_n),
    .layer17_out_read(normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_layer17_out_read),
    .layer24_out_din(normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_layer24_out_din),
    .layer24_out_num_data_valid(layer24_out_num_data_valid),
    .layer24_out_fifo_cap(layer24_out_fifo_cap),
    .layer24_out_full_n(layer24_out_full_n),
    .layer24_out_write(normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_layer24_out_write)
);

myproject_softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_s softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_ap_start),
    .ap_done(softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_ap_done),
    .ap_continue(softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_ap_continue),
    .ap_idle(softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_ap_idle),
    .ap_ready(softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_ap_ready),
    .layer24_out_dout(layer24_out_dout),
    .layer24_out_num_data_valid(layer24_out_num_data_valid),
    .layer24_out_fifo_cap(layer24_out_fifo_cap),
    .layer24_out_empty_n(layer24_out_empty_n),
    .layer24_out_read(softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_layer24_out_read),
    .layer19_out_TDATA(softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_layer19_out_TDATA),
    .layer19_out_TVALID(softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_layer19_out_TVALID),
    .layer19_out_TREADY(layer19_out_TREADY)
);

myproject_fifo_w180_d576_A layer2_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_layer2_out_din),
    .if_full_n(layer2_out_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_layer2_out_write),
    .if_dout(layer2_out_dout),
    .if_num_data_valid(layer2_out_num_data_valid),
    .if_fifo_cap(layer2_out_fifo_cap),
    .if_empty_n(layer2_out_empty_n),
    .if_read(normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_layer2_out_read)
);

myproject_fifo_w96_d576_A layer20_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_layer20_out_din),
    .if_full_n(layer20_out_full_n),
    .if_write(normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_layer20_out_write),
    .if_dout(layer20_out_dout),
    .if_num_data_valid(layer20_out_num_data_valid),
    .if_fifo_cap(layer20_out_fifo_cap),
    .if_empty_n(layer20_out_empty_n),
    .if_read(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_layer20_out_read)
);

myproject_fifo_w48_d576_A layer4_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_layer4_out_din),
    .if_full_n(layer4_out_full_n),
    .if_write(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_layer4_out_write),
    .if_dout(layer4_out_dout),
    .if_num_data_valid(layer4_out_num_data_valid),
    .if_fifo_cap(layer4_out_fifo_cap),
    .if_empty_n(layer4_out_empty_n),
    .if_read(pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_layer4_out_read)
);

myproject_fifo_w48_d144_A layer5_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_layer5_out_din),
    .if_full_n(layer5_out_full_n),
    .if_write(pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_layer5_out_write),
    .if_dout(layer5_out_dout),
    .if_num_data_valid(layer5_out_num_data_valid),
    .if_fifo_cap(layer5_out_fifo_cap),
    .if_empty_n(layer5_out_empty_n),
    .if_read(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_layer5_out_read)
);

myproject_fifo_w400_d64_A layer6_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_layer6_out_din),
    .if_full_n(layer6_out_full_n),
    .if_write(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_layer6_out_write),
    .if_dout(layer6_out_dout),
    .if_num_data_valid(layer6_out_num_data_valid),
    .if_fifo_cap(layer6_out_fifo_cap),
    .if_empty_n(layer6_out_empty_n),
    .if_read(normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_layer6_out_read)
);

myproject_fifo_w256_d64_A layer21_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_layer21_out_din),
    .if_full_n(layer21_out_full_n),
    .if_write(normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_layer21_out_write),
    .if_dout(layer21_out_dout),
    .if_num_data_valid(layer21_out_num_data_valid),
    .if_fifo_cap(layer21_out_fifo_cap),
    .if_empty_n(layer21_out_empty_n),
    .if_read(relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_layer21_out_read)
);

myproject_fifo_w128_d64_A layer8_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_layer8_out_din),
    .if_full_n(layer8_out_full_n),
    .if_write(relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_layer8_out_write),
    .if_dout(layer8_out_dout),
    .if_num_data_valid(layer8_out_num_data_valid),
    .if_fifo_cap(layer8_out_fifo_cap),
    .if_empty_n(layer8_out_empty_n),
    .if_read(pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_layer8_out_read)
);

myproject_fifo_w128_d16_A layer9_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_layer9_out_din),
    .if_full_n(layer9_out_full_n),
    .if_write(pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_layer9_out_write),
    .if_dout(layer9_out_dout),
    .if_num_data_valid(layer9_out_num_data_valid),
    .if_fifo_cap(layer9_out_fifo_cap),
    .if_empty_n(layer9_out_empty_n),
    .if_read(dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_layer9_out_read)
);

myproject_fifo_w3000_d1_S layer11_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_layer11_out_din),
    .if_full_n(layer11_out_full_n),
    .if_write(dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_layer11_out_write),
    .if_dout(layer11_out_dout),
    .if_num_data_valid(layer11_out_num_data_valid),
    .if_fifo_cap(layer11_out_fifo_cap),
    .if_empty_n(layer11_out_empty_n),
    .if_read(normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_layer11_out_read)
);

myproject_fifo_w1920_d1_S layer22_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_layer22_out_din),
    .if_full_n(layer22_out_full_n),
    .if_write(normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_layer22_out_write),
    .if_dout(layer22_out_dout),
    .if_num_data_valid(layer22_out_num_data_valid),
    .if_fifo_cap(layer22_out_fifo_cap),
    .if_empty_n(layer22_out_empty_n),
    .if_read(relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_layer22_out_read)
);

myproject_fifo_w960_d1_S layer13_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_layer13_out_din),
    .if_full_n(layer13_out_full_n),
    .if_write(relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_layer13_out_write),
    .if_dout(layer13_out_dout),
    .if_num_data_valid(layer13_out_num_data_valid),
    .if_fifo_cap(layer13_out_fifo_cap),
    .if_empty_n(layer13_out_empty_n),
    .if_read(dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_layer13_out_read)
);

myproject_fifo_w2016_d1_S layer14_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_layer14_out_din),
    .if_full_n(layer14_out_full_n),
    .if_write(dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_layer14_out_write),
    .if_dout(layer14_out_dout),
    .if_num_data_valid(layer14_out_num_data_valid),
    .if_fifo_cap(layer14_out_fifo_cap),
    .if_empty_n(layer14_out_empty_n),
    .if_read(normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_layer14_out_read)
);

myproject_fifo_w1344_d1_S layer23_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_layer23_out_din),
    .if_full_n(layer23_out_full_n),
    .if_write(normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_layer23_out_write),
    .if_dout(layer23_out_dout),
    .if_num_data_valid(layer23_out_num_data_valid),
    .if_fifo_cap(layer23_out_fifo_cap),
    .if_empty_n(layer23_out_empty_n),
    .if_read(relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_layer23_out_read)
);

myproject_fifo_w672_d1_S layer16_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_layer16_out_din),
    .if_full_n(layer16_out_full_n),
    .if_write(relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_layer16_out_write),
    .if_dout(layer16_out_dout),
    .if_num_data_valid(layer16_out_num_data_valid),
    .if_fifo_cap(layer16_out_fifo_cap),
    .if_empty_n(layer16_out_empty_n),
    .if_read(dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_layer16_out_read)
);

myproject_fifo_w160_d1_S layer17_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_layer17_out_din),
    .if_full_n(layer17_out_full_n),
    .if_write(dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_layer17_out_write),
    .if_dout(layer17_out_dout),
    .if_num_data_valid(layer17_out_num_data_valid),
    .if_fifo_cap(layer17_out_fifo_cap),
    .if_empty_n(layer17_out_empty_n),
    .if_read(normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_layer17_out_read)
);

myproject_fifo_w160_d1_S layer24_out_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_layer24_out_din),
    .if_full_n(layer24_out_full_n),
    .if_write(normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_layer24_out_write),
    .if_dout(layer24_out_dout),
    .if_num_data_valid(layer24_out_num_data_valid),
    .if_fifo_cap(layer24_out_fifo_cap),
    .if_empty_n(layer24_out_empty_n),
    .if_read(softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_layer24_out_read)
);

myproject_start_for_normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0 start_for_normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_din),
    .if_full_n(start_for_normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_full_n),
    .if_write(conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_start_write),
    .if_dout(start_for_normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_dout),
    .if_empty_n(start_for_normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_empty_n),
    .if_read(normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_ap_ready)
);

myproject_start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0 start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_full_n),
    .if_write(normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_empty_n),
    .if_read(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_ap_ready)
);

myproject_start_for_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config3i2 start_for_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config3i2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_din),
    .if_full_n(start_for_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_full_n),
    .if_write(relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_start_write),
    .if_dout(start_for_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_dout),
    .if_empty_n(start_for_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_empty_n),
    .if_read(pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_ap_ready)
);

myproject_start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config4jc start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config4jc_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_din),
    .if_full_n(start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_full_n),
    .if_write(pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_start_write),
    .if_dout(start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_dout),
    .if_empty_n(start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_empty_n),
    .if_read(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_ap_ready)
);

myproject_start_for_normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config215jm start_for_normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config215jm_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_din),
    .if_full_n(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_full_n),
    .if_write(conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_start_write),
    .if_dout(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_dout),
    .if_empty_n(start_for_normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_empty_n),
    .if_read(normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_ap_ready)
);

myproject_start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0 start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_full_n),
    .if_write(normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_empty_n),
    .if_read(relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_ap_ready)
);

myproject_start_for_pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0 start_for_pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_din),
    .if_full_n(start_for_pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_full_n),
    .if_write(relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_start_write),
    .if_dout(start_for_pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_dout),
    .if_empty_n(start_for_pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_empty_n),
    .if_read(pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_ap_ready)
);

myproject_start_for_dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0 start_for_dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_din),
    .if_full_n(start_for_dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_full_n),
    .if_write(pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_start_write),
    .if_dout(start_for_dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_dout),
    .if_empty_n(start_for_dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_empty_n),
    .if_read(dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_ap_ready)
);

myproject_start_for_normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0 start_for_normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_din),
    .if_full_n(start_for_normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_full_n),
    .if_write(dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_start_write),
    .if_dout(start_for_normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_dout),
    .if_empty_n(start_for_normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_empty_n),
    .if_read(normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_ap_ready)
);

myproject_start_for_relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0 start_for_relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_din),
    .if_full_n(start_for_relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_full_n),
    .if_write(normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_start_write),
    .if_dout(start_for_relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_dout),
    .if_empty_n(start_for_relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_empty_n),
    .if_read(relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_ap_ready)
);

myproject_start_for_dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0 start_for_dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_din),
    .if_full_n(start_for_dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_full_n),
    .if_write(relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_start_write),
    .if_dout(start_for_dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_dout),
    .if_empty_n(start_for_dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_empty_n),
    .if_read(dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_ap_ready)
);

myproject_start_for_normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config236jw start_for_normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config236jw_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_din),
    .if_full_n(start_for_normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_full_n),
    .if_write(dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_start_write),
    .if_dout(start_for_normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_dout),
    .if_empty_n(start_for_normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_empty_n),
    .if_read(normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_ap_ready)
);

myproject_start_for_relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config167jG start_for_relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config167jG_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_din),
    .if_full_n(start_for_relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_full_n),
    .if_write(normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_start_write),
    .if_dout(start_for_relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_dout),
    .if_empty_n(start_for_relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_empty_n),
    .if_read(relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_ap_ready)
);

myproject_start_for_dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0 start_for_dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_din),
    .if_full_n(start_for_dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_full_n),
    .if_write(relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_start_write),
    .if_dout(start_for_dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_dout),
    .if_empty_n(start_for_dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_empty_n),
    .if_read(dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_ap_ready)
);

myproject_start_for_normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config248jQ start_for_normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config248jQ_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_din),
    .if_full_n(start_for_normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_full_n),
    .if_write(dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_start_write),
    .if_dout(start_for_normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_dout),
    .if_empty_n(start_for_normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_empty_n),
    .if_read(normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_ap_ready)
);

myproject_start_for_softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0 start_for_softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_din),
    .if_full_n(start_for_softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_full_n),
    .if_write(normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_start_write),
    .if_dout(start_for_softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_dout),
    .if_empty_n(start_for_softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_empty_n),
    .if_read(softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_ap_ready)
);

assign ap_done = softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_ap_done;

assign ap_idle = (softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_ap_idle & relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_ap_idle & relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_ap_idle & relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_ap_idle & relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_ap_idle & pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_ap_idle & pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_ap_idle & normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_ap_idle & normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_ap_idle & normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_ap_idle & normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_ap_idle & normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_ap_idle & dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_ap_idle & dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_ap_idle 
    & dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_ap_idle & conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_ap_idle & conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_ap_idle);

assign ap_ready = conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_ap_start = ap_start;

assign conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_ap_continue = 1'b1;

assign conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_ap_start = start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_empty_n;

assign dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_ap_continue = 1'b1;

assign dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_ap_start = start_for_dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_empty_n;

assign dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_ap_continue = 1'b1;

assign dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_ap_start = start_for_dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_empty_n;

assign dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_ap_continue = 1'b1;

assign dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_ap_start = start_for_dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_empty_n;

assign layer19_out_TDATA = softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_layer19_out_TDATA;

assign layer19_out_TVALID = softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_layer19_out_TVALID;

assign normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_ap_continue = 1'b1;

assign normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_ap_start = start_for_normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_empty_n;

assign normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_ap_continue = 1'b1;

assign normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_ap_start = start_for_normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_empty_n;

assign normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_ap_continue = 1'b1;

assign normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_ap_start = start_for_normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_empty_n;

assign normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_ap_continue = 1'b1;

assign normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_ap_start = start_for_normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_empty_n;

assign normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_ap_continue = 1'b1;

assign normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_ap_start = start_for_normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_empty_n;

assign pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_ap_continue = 1'b1;

assign pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_ap_start = start_for_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_empty_n;

assign pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_ap_continue = 1'b1;

assign pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_ap_start = start_for_pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_empty_n;

assign q_conv2d_input_TREADY = conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_30_15_5_3_0_6u_config2_U0_q_conv2d_input_TREADY;

assign relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_ap_start = start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_empty_n;

assign relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_ap_start = start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_empty_n;

assign relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_ap_start = start_for_relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_empty_n;

assign relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_ap_continue = 1'b1;

assign relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_ap_start = start_for_relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_empty_n;

assign softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_ap_continue = 1'b1;

assign softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_ap_start = start_for_softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_empty_n;

assign start_for_conv_2d_cl_array_ap_ufixed_6u_array_ap_fixed_25_12_5_3_0_16u_config6_U0_din = 1'b1;

assign start_for_dense_array_ap_ufixed_120u_array_ap_fixed_24_11_5_3_0_84u_config14_U0_din = 1'b1;

assign start_for_dense_array_ap_ufixed_16u_array_ap_fixed_25_12_5_3_0_120u_config11_U0_din = 1'b1;

assign start_for_dense_array_ap_ufixed_84u_array_ap_fixed_16_6_0_0_0_10u_config17_U0_din = 1'b1;

assign start_for_normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_U0_din = 1'b1;

assign start_for_normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_U0_din = 1'b1;

assign start_for_normalize_array_ap_fixed_6u_array_ap_fixed_16_6_5_3_0_6u_config20_U0_din = 1'b1;

assign start_for_normalize_array_ap_fixed_84u_array_ap_fixed_16_6_5_3_0_84u_config23_U0_din = 1'b1;

assign start_for_normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_U0_din = 1'b1;

assign start_for_pooling2d_cl_array_ap_ufixed_6u_array_ap_ufixed_8_0_4_0_0_6u_config5_U0_din = 1'b1;

assign start_for_pooling2d_cl_array_array_ap_ufixed_8_0_4_0_0_16u_config9_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_16u_array_ap_ufixed_8_0_4_0_0_16u_relu_config8_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_U0_din = 1'b1;

assign start_for_relu_array_ap_fixed_84u_array_ap_ufixed_8_0_4_0_0_84u_relu_config16_U0_din = 1'b1;

assign start_for_relu_array_array_ap_ufixed_8_0_4_0_0_120u_relu_config13_U0_din = 1'b1;

assign start_for_softmax_array_array_ap_fixed_16_6_5_3_0_10u_softmax_config19_U0_din = 1'b1;

endmodule //myproject
