// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer20_out_dout,
        layer20_out_num_data_valid,
        layer20_out_fifo_cap,
        layer20_out_empty_n,
        layer20_out_read,
        layer4_out_din,
        layer4_out_num_data_valid,
        layer4_out_fifo_cap,
        layer4_out_full_n,
        layer4_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [95:0] layer20_out_dout;
input  [10:0] layer20_out_num_data_valid;
input  [10:0] layer20_out_fifo_cap;
input   layer20_out_empty_n;
output   layer20_out_read;
output  [47:0] layer4_out_din;
input  [10:0] layer4_out_num_data_valid;
input  [10:0] layer4_out_fifo_cap;
input   layer4_out_full_n;
output   layer4_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer20_out_read;
reg layer4_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln41_fu_153_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer20_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer4_out_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] out_data_8_fu_356_p3;
reg   [7:0] out_data_8_reg_1010;
wire   [7:0] out_data_10_fu_484_p3;
reg   [7:0] out_data_10_reg_1015;
wire   [7:0] out_data_12_fu_604_p3;
reg   [7:0] out_data_12_reg_1020;
wire   [7:0] out_data_14_fu_724_p3;
reg   [7:0] out_data_14_reg_1025;
wire   [7:0] out_data_16_fu_852_p3;
reg   [7:0] out_data_16_reg_1030;
wire   [7:0] out_data_18_fu_980_p3;
reg   [7:0] out_data_18_reg_1035;
reg   [9:0] i_fu_128;
wire   [9:0] i_2_fu_159_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i_1;
reg    ap_block_pp0_stage0_01001;
wire   [15:0] in_data_fu_170_p1;
wire   [0:0] tmp_581_fu_256_p3;
wire   [0:0] trunc_ln52_fu_272_p1;
wire   [0:0] or_ln52_fu_276_p2;
wire   [0:0] tmp_582_fu_264_p3;
wire   [0:0] and_ln52_fu_282_p2;
wire   [7:0] trunc_ln3_fu_246_p4;
wire   [7:0] zext_ln52_fu_288_p1;
wire   [5:0] tmp_s_fu_298_p4;
wire   [7:0] add_ln52_fu_292_p2;
wire   [0:0] tmp_584_fu_322_p3;
wire   [0:0] tmp_583_fu_314_p3;
wire   [0:0] xor_ln52_fu_330_p2;
wire   [0:0] icmp_ln52_fu_308_p2;
wire   [0:0] or_ln52_168_fu_336_p2;
wire   [0:0] and_ln52_168_fu_342_p2;
wire   [0:0] icmp_ln51_fu_240_p2;
wire   [7:0] out_data_fu_348_p3;
wire   [15:0] in_data_4_fu_210_p4;
wire   [0:0] tmp_585_fu_380_p3;
wire   [0:0] tmp_587_fu_396_p3;
wire   [0:0] or_ln52_84_fu_404_p2;
wire   [0:0] tmp_586_fu_388_p3;
wire   [0:0] and_ln52_169_fu_410_p2;
wire   [7:0] trunc_ln52_s_fu_370_p4;
wire   [7:0] zext_ln52_84_fu_416_p1;
wire   [5:0] tmp_245_fu_426_p4;
wire   [7:0] add_ln52_84_fu_420_p2;
wire   [0:0] tmp_589_fu_450_p3;
wire   [0:0] tmp_588_fu_442_p3;
wire   [0:0] xor_ln52_84_fu_458_p2;
wire   [0:0] icmp_ln52_84_fu_436_p2;
wire   [0:0] or_ln52_169_fu_464_p2;
wire   [0:0] and_ln52_170_fu_470_p2;
wire   [0:0] icmp_ln51_84_fu_364_p2;
wire   [7:0] out_data_9_fu_476_p3;
wire   [15:0] in_data_5_fu_220_p4;
wire   [0:0] tmp_590_fu_508_p3;
wire   [0:0] tmp_fu_194_p3;
wire   [0:0] or_ln52_85_fu_524_p2;
wire   [0:0] tmp_591_fu_516_p3;
wire   [0:0] and_ln52_171_fu_530_p2;
wire   [7:0] trunc_ln52_83_fu_498_p4;
wire   [7:0] zext_ln52_85_fu_536_p1;
wire   [5:0] tmp_246_fu_546_p4;
wire   [7:0] add_ln52_85_fu_540_p2;
wire   [0:0] tmp_593_fu_570_p3;
wire   [0:0] tmp_592_fu_562_p3;
wire   [0:0] xor_ln52_85_fu_578_p2;
wire   [0:0] icmp_ln52_85_fu_556_p2;
wire   [0:0] or_ln52_170_fu_584_p2;
wire   [0:0] and_ln52_172_fu_590_p2;
wire   [0:0] icmp_ln51_85_fu_492_p2;
wire   [7:0] out_data_11_fu_596_p3;
wire   [15:0] in_data_6_fu_230_p4;
wire   [0:0] tmp_594_fu_628_p3;
wire   [0:0] tmp_580_fu_202_p3;
wire   [0:0] or_ln52_86_fu_644_p2;
wire   [0:0] tmp_595_fu_636_p3;
wire   [0:0] and_ln52_173_fu_650_p2;
wire   [7:0] trunc_ln52_84_fu_618_p4;
wire   [7:0] zext_ln52_86_fu_656_p1;
wire   [5:0] tmp_247_fu_666_p4;
wire   [7:0] add_ln52_86_fu_660_p2;
wire   [0:0] tmp_597_fu_690_p3;
wire   [0:0] tmp_596_fu_682_p3;
wire   [0:0] xor_ln52_86_fu_698_p2;
wire   [0:0] icmp_ln52_86_fu_676_p2;
wire   [0:0] or_ln52_171_fu_704_p2;
wire   [0:0] and_ln52_174_fu_710_p2;
wire   [0:0] icmp_ln51_86_fu_612_p2;
wire   [7:0] out_data_13_fu_716_p3;
wire   [15:0] trunc_ln44_s_fu_174_p4;
wire   [0:0] tmp_598_fu_748_p3;
wire   [0:0] tmp_600_fu_764_p3;
wire   [0:0] or_ln52_87_fu_772_p2;
wire   [0:0] tmp_599_fu_756_p3;
wire   [0:0] and_ln52_175_fu_778_p2;
wire   [7:0] trunc_ln52_85_fu_738_p4;
wire   [7:0] zext_ln52_87_fu_784_p1;
wire   [5:0] tmp_248_fu_794_p4;
wire   [7:0] add_ln52_87_fu_788_p2;
wire   [0:0] tmp_602_fu_818_p3;
wire   [0:0] tmp_601_fu_810_p3;
wire   [0:0] xor_ln52_87_fu_826_p2;
wire   [0:0] icmp_ln52_87_fu_804_p2;
wire   [0:0] or_ln52_172_fu_832_p2;
wire   [0:0] and_ln52_176_fu_838_p2;
wire   [0:0] icmp_ln51_87_fu_732_p2;
wire   [7:0] out_data_15_fu_844_p3;
wire   [15:0] trunc_ln44_1_fu_184_p4;
wire   [0:0] tmp_603_fu_876_p3;
wire   [0:0] tmp_605_fu_892_p3;
wire   [0:0] or_ln52_88_fu_900_p2;
wire   [0:0] tmp_604_fu_884_p3;
wire   [0:0] and_ln52_177_fu_906_p2;
wire   [7:0] trunc_ln52_86_fu_866_p4;
wire   [7:0] zext_ln52_88_fu_912_p1;
wire   [5:0] tmp_249_fu_922_p4;
wire   [7:0] add_ln52_88_fu_916_p2;
wire   [0:0] tmp_607_fu_946_p3;
wire   [0:0] tmp_606_fu_938_p3;
wire   [0:0] xor_ln52_88_fu_954_p2;
wire   [0:0] icmp_ln52_88_fu_932_p2;
wire   [0:0] or_ln52_173_fu_960_p2;
wire   [0:0] and_ln52_178_fu_966_p2;
wire   [0:0] icmp_ln51_88_fu_860_p2;
wire   [7:0] out_data_17_fu_972_p3;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_122;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_122)) begin
        if ((icmp_ln41_fu_153_p2 == 1'd0)) begin
            i_fu_128 <= i_2_fu_159_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_128 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        out_data_10_reg_1015 <= out_data_10_fu_484_p3;
        out_data_12_reg_1020 <= out_data_12_fu_604_p3;
        out_data_14_reg_1025 <= out_data_14_fu_724_p3;
        out_data_16_reg_1030 <= out_data_16_fu_852_p3;
        out_data_18_reg_1035 <= out_data_18_fu_980_p3;
        out_data_8_reg_1010 <= out_data_8_fu_356_p3;
    end
end

always @ (*) begin
    if (((icmp_ln41_fu_153_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 10'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_128;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer20_out_blk_n = layer20_out_empty_n;
    end else begin
        layer20_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer20_out_read = 1'b1;
    end else begin
        layer20_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer4_out_blk_n = layer4_out_full_n;
    end else begin
        layer4_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer4_out_write = 1'b1;
    end else begin
        layer4_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln52_84_fu_420_p2 = (trunc_ln52_s_fu_370_p4 + zext_ln52_84_fu_416_p1);

assign add_ln52_85_fu_540_p2 = (trunc_ln52_83_fu_498_p4 + zext_ln52_85_fu_536_p1);

assign add_ln52_86_fu_660_p2 = (trunc_ln52_84_fu_618_p4 + zext_ln52_86_fu_656_p1);

assign add_ln52_87_fu_788_p2 = (trunc_ln52_85_fu_738_p4 + zext_ln52_87_fu_784_p1);

assign add_ln52_88_fu_916_p2 = (trunc_ln52_86_fu_866_p4 + zext_ln52_88_fu_912_p1);

assign add_ln52_fu_292_p2 = (trunc_ln3_fu_246_p4 + zext_ln52_fu_288_p1);

assign and_ln52_168_fu_342_p2 = (or_ln52_168_fu_336_p2 & icmp_ln52_fu_308_p2);

assign and_ln52_169_fu_410_p2 = (tmp_586_fu_388_p3 & or_ln52_84_fu_404_p2);

assign and_ln52_170_fu_470_p2 = (or_ln52_169_fu_464_p2 & icmp_ln52_84_fu_436_p2);

assign and_ln52_171_fu_530_p2 = (tmp_591_fu_516_p3 & or_ln52_85_fu_524_p2);

assign and_ln52_172_fu_590_p2 = (or_ln52_170_fu_584_p2 & icmp_ln52_85_fu_556_p2);

assign and_ln52_173_fu_650_p2 = (tmp_595_fu_636_p3 & or_ln52_86_fu_644_p2);

assign and_ln52_174_fu_710_p2 = (or_ln52_171_fu_704_p2 & icmp_ln52_86_fu_676_p2);

assign and_ln52_175_fu_778_p2 = (tmp_599_fu_756_p3 & or_ln52_87_fu_772_p2);

assign and_ln52_176_fu_838_p2 = (or_ln52_172_fu_832_p2 & icmp_ln52_87_fu_804_p2);

assign and_ln52_177_fu_906_p2 = (tmp_604_fu_884_p3 & or_ln52_88_fu_900_p2);

assign and_ln52_178_fu_966_p2 = (or_ln52_173_fu_960_p2 & icmp_ln52_88_fu_932_p2);

assign and_ln52_fu_282_p2 = (tmp_582_fu_264_p3 & or_ln52_fu_276_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((layer4_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer20_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((layer4_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer20_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((layer4_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer20_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer20_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (layer4_out_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_122 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_2_fu_159_p2 = (ap_sig_allocacmp_i_1 + 10'd1);

assign icmp_ln41_fu_153_p2 = ((ap_sig_allocacmp_i_1 == 10'd576) ? 1'b1 : 1'b0);

assign icmp_ln51_84_fu_364_p2 = (($signed(in_data_4_fu_210_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_85_fu_492_p2 = (($signed(in_data_5_fu_220_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_86_fu_612_p2 = (($signed(in_data_6_fu_230_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_87_fu_732_p2 = (($signed(trunc_ln44_s_fu_174_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_88_fu_860_p2 = (($signed(trunc_ln44_1_fu_184_p4) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_240_p2 = (($signed(in_data_fu_170_p1) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln52_84_fu_436_p2 = ((tmp_245_fu_426_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_85_fu_556_p2 = ((tmp_246_fu_546_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_86_fu_676_p2 = ((tmp_247_fu_666_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_87_fu_804_p2 = ((tmp_248_fu_794_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_88_fu_932_p2 = ((tmp_249_fu_922_p4 == 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_308_p2 = ((tmp_s_fu_298_p4 == 6'd0) ? 1'b1 : 1'b0);

assign in_data_4_fu_210_p4 = {{layer20_out_dout[31:16]}};

assign in_data_5_fu_220_p4 = {{layer20_out_dout[47:32]}};

assign in_data_6_fu_230_p4 = {{layer20_out_dout[63:48]}};

assign in_data_fu_170_p1 = layer20_out_dout[15:0];

assign layer4_out_din = {{{{{{out_data_18_reg_1035}, {out_data_16_reg_1030}}, {out_data_14_reg_1025}}, {out_data_12_reg_1020}}, {out_data_10_reg_1015}}, {out_data_8_reg_1010}};

assign or_ln52_168_fu_336_p2 = (xor_ln52_fu_330_p2 | tmp_583_fu_314_p3);

assign or_ln52_169_fu_464_p2 = (xor_ln52_84_fu_458_p2 | tmp_588_fu_442_p3);

assign or_ln52_170_fu_584_p2 = (xor_ln52_85_fu_578_p2 | tmp_592_fu_562_p3);

assign or_ln52_171_fu_704_p2 = (xor_ln52_86_fu_698_p2 | tmp_596_fu_682_p3);

assign or_ln52_172_fu_832_p2 = (xor_ln52_87_fu_826_p2 | tmp_601_fu_810_p3);

assign or_ln52_173_fu_960_p2 = (xor_ln52_88_fu_954_p2 | tmp_606_fu_938_p3);

assign or_ln52_84_fu_404_p2 = (tmp_587_fu_396_p3 | tmp_585_fu_380_p3);

assign or_ln52_85_fu_524_p2 = (tmp_fu_194_p3 | tmp_590_fu_508_p3);

assign or_ln52_86_fu_644_p2 = (tmp_594_fu_628_p3 | tmp_580_fu_202_p3);

assign or_ln52_87_fu_772_p2 = (tmp_600_fu_764_p3 | tmp_598_fu_748_p3);

assign or_ln52_88_fu_900_p2 = (tmp_605_fu_892_p3 | tmp_603_fu_876_p3);

assign or_ln52_fu_276_p2 = (trunc_ln52_fu_272_p1 | tmp_581_fu_256_p3);

assign out_data_10_fu_484_p3 = ((icmp_ln51_84_fu_364_p2[0:0] == 1'b1) ? out_data_9_fu_476_p3 : 8'd0);

assign out_data_11_fu_596_p3 = ((and_ln52_172_fu_590_p2[0:0] == 1'b1) ? add_ln52_85_fu_540_p2 : 8'd255);

assign out_data_12_fu_604_p3 = ((icmp_ln51_85_fu_492_p2[0:0] == 1'b1) ? out_data_11_fu_596_p3 : 8'd0);

assign out_data_13_fu_716_p3 = ((and_ln52_174_fu_710_p2[0:0] == 1'b1) ? add_ln52_86_fu_660_p2 : 8'd255);

assign out_data_14_fu_724_p3 = ((icmp_ln51_86_fu_612_p2[0:0] == 1'b1) ? out_data_13_fu_716_p3 : 8'd0);

assign out_data_15_fu_844_p3 = ((and_ln52_176_fu_838_p2[0:0] == 1'b1) ? add_ln52_87_fu_788_p2 : 8'd255);

assign out_data_16_fu_852_p3 = ((icmp_ln51_87_fu_732_p2[0:0] == 1'b1) ? out_data_15_fu_844_p3 : 8'd0);

assign out_data_17_fu_972_p3 = ((and_ln52_178_fu_966_p2[0:0] == 1'b1) ? add_ln52_88_fu_916_p2 : 8'd255);

assign out_data_18_fu_980_p3 = ((icmp_ln51_88_fu_860_p2[0:0] == 1'b1) ? out_data_17_fu_972_p3 : 8'd0);

assign out_data_8_fu_356_p3 = ((icmp_ln51_fu_240_p2[0:0] == 1'b1) ? out_data_fu_348_p3 : 8'd0);

assign out_data_9_fu_476_p3 = ((and_ln52_170_fu_470_p2[0:0] == 1'b1) ? add_ln52_84_fu_420_p2 : 8'd255);

assign out_data_fu_348_p3 = ((and_ln52_168_fu_342_p2[0:0] == 1'b1) ? add_ln52_fu_292_p2 : 8'd255);

assign start_out = real_start;

assign tmp_245_fu_426_p4 = {{layer20_out_dout[31:26]}};

assign tmp_246_fu_546_p4 = {{layer20_out_dout[47:42]}};

assign tmp_247_fu_666_p4 = {{layer20_out_dout[63:58]}};

assign tmp_248_fu_794_p4 = {{layer20_out_dout[79:74]}};

assign tmp_249_fu_922_p4 = {{layer20_out_dout[95:90]}};

assign tmp_580_fu_202_p3 = layer20_out_dout[32'd48];

assign tmp_581_fu_256_p3 = layer20_out_dout[32'd2];

assign tmp_582_fu_264_p3 = layer20_out_dout[32'd1];

assign tmp_583_fu_314_p3 = add_ln52_fu_292_p2[32'd7];

assign tmp_584_fu_322_p3 = layer20_out_dout[32'd9];

assign tmp_585_fu_380_p3 = layer20_out_dout[32'd18];

assign tmp_586_fu_388_p3 = layer20_out_dout[32'd17];

assign tmp_587_fu_396_p3 = layer20_out_dout[32'd16];

assign tmp_588_fu_442_p3 = add_ln52_84_fu_420_p2[32'd7];

assign tmp_589_fu_450_p3 = layer20_out_dout[32'd25];

assign tmp_590_fu_508_p3 = layer20_out_dout[32'd34];

assign tmp_591_fu_516_p3 = layer20_out_dout[32'd33];

assign tmp_592_fu_562_p3 = add_ln52_85_fu_540_p2[32'd7];

assign tmp_593_fu_570_p3 = layer20_out_dout[32'd41];

assign tmp_594_fu_628_p3 = layer20_out_dout[32'd50];

assign tmp_595_fu_636_p3 = layer20_out_dout[32'd49];

assign tmp_596_fu_682_p3 = add_ln52_86_fu_660_p2[32'd7];

assign tmp_597_fu_690_p3 = layer20_out_dout[32'd57];

assign tmp_598_fu_748_p3 = layer20_out_dout[32'd66];

assign tmp_599_fu_756_p3 = layer20_out_dout[32'd65];

assign tmp_600_fu_764_p3 = layer20_out_dout[32'd64];

assign tmp_601_fu_810_p3 = add_ln52_87_fu_788_p2[32'd7];

assign tmp_602_fu_818_p3 = layer20_out_dout[32'd73];

assign tmp_603_fu_876_p3 = layer20_out_dout[32'd82];

assign tmp_604_fu_884_p3 = layer20_out_dout[32'd81];

assign tmp_605_fu_892_p3 = layer20_out_dout[32'd80];

assign tmp_606_fu_938_p3 = add_ln52_88_fu_916_p2[32'd7];

assign tmp_607_fu_946_p3 = layer20_out_dout[32'd89];

assign tmp_fu_194_p3 = layer20_out_dout[32'd32];

assign tmp_s_fu_298_p4 = {{layer20_out_dout[15:10]}};

assign trunc_ln3_fu_246_p4 = {{layer20_out_dout[9:2]}};

assign trunc_ln44_1_fu_184_p4 = {{layer20_out_dout[95:80]}};

assign trunc_ln44_s_fu_174_p4 = {{layer20_out_dout[79:64]}};

assign trunc_ln52_83_fu_498_p4 = {{layer20_out_dout[41:34]}};

assign trunc_ln52_84_fu_618_p4 = {{layer20_out_dout[57:50]}};

assign trunc_ln52_85_fu_738_p4 = {{layer20_out_dout[73:66]}};

assign trunc_ln52_86_fu_866_p4 = {{layer20_out_dout[89:82]}};

assign trunc_ln52_fu_272_p1 = layer20_out_dout[0:0];

assign trunc_ln52_s_fu_370_p4 = {{layer20_out_dout[25:18]}};

assign xor_ln52_84_fu_458_p2 = (tmp_589_fu_450_p3 ^ 1'd1);

assign xor_ln52_85_fu_578_p2 = (tmp_593_fu_570_p3 ^ 1'd1);

assign xor_ln52_86_fu_698_p2 = (tmp_597_fu_690_p3 ^ 1'd1);

assign xor_ln52_87_fu_826_p2 = (tmp_602_fu_818_p3 ^ 1'd1);

assign xor_ln52_88_fu_954_p2 = (tmp_607_fu_946_p3 ^ 1'd1);

assign xor_ln52_fu_330_p2 = (tmp_584_fu_322_p3 ^ 1'd1);

assign zext_ln52_84_fu_416_p1 = and_ln52_169_fu_410_p2;

assign zext_ln52_85_fu_536_p1 = and_ln52_171_fu_530_p2;

assign zext_ln52_86_fu_656_p1 = and_ln52_173_fu_650_p2;

assign zext_ln52_87_fu_784_p1 = and_ln52_175_fu_778_p2;

assign zext_ln52_88_fu_912_p1 = and_ln52_177_fu_906_p2;

assign zext_ln52_fu_288_p1 = and_ln52_fu_282_p2;

endmodule //myproject_relu_array_ap_fixed_6u_array_ap_ufixed_8_0_4_0_0_6u_relu_config4_s
