// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        layer6_out_dout,
        layer6_out_num_data_valid,
        layer6_out_fifo_cap,
        layer6_out_empty_n,
        layer6_out_read,
        layer21_out_din,
        layer21_out_num_data_valid,
        layer21_out_fifo_cap,
        layer21_out_full_n,
        layer21_out_write,
        start_out,
        start_write
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [399:0] layer6_out_dout;
input  [6:0] layer6_out_num_data_valid;
input  [6:0] layer6_out_fifo_cap;
input   layer6_out_empty_n;
output   layer6_out_read;
output  [255:0] layer21_out_din;
input  [6:0] layer21_out_num_data_valid;
input  [6:0] layer21_out_fifo_cap;
input   layer21_out_full_n;
output   layer21_out_write;
output   start_out;
output   start_write;

reg ap_idle;
reg layer6_out_read;
reg layer21_out_write;
reg start_write;

reg    real_start;
reg    start_once_reg;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    internal_ap_ready;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln25_fu_161_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    layer6_out_blk_n;
wire    ap_block_pp0_stage0;
reg    layer21_out_blk_n;
reg    ap_block_pp0_stage0_11001;
reg   [15:0] trunc_ln_reg_644;
reg   [15:0] trunc_ln4_reg_649;
reg   [15:0] trunc_ln46_2_reg_654;
reg   [15:0] tmp_624_reg_659;
reg   [15:0] trunc_ln46_7_reg_664;
reg   [15:0] tmp_625_reg_669;
reg   [15:0] trunc_ln46_13_reg_674;
reg   [15:0] tmp_s_reg_679;
reg   [15:0] tmp_626_reg_684;
reg   [15:0] tmp_627_reg_689;
reg   [15:0] tmp_628_reg_694;
reg   [15:0] tmp_629_reg_699;
reg   [15:0] tmp_630_reg_704;
reg   [15:0] tmp_631_reg_709;
reg   [15:0] tmp_632_reg_714;
reg   [15:0] tmp_633_reg_719;
reg   [6:0] i_03_fu_136;
wire   [6:0] i_7_fu_167_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i;
reg    ap_block_pp0_stage0_01001;
wire   [21:0] trunc_ln85_fu_178_p1;
wire   [36:0] y_fu_182_p3;
wire   [36:0] add_ln42_fu_190_p2;
wire   [23:0] tmp_614_fu_206_p4;
wire   [36:0] y_3_fu_216_p3;
wire   [21:0] tmp_615_fu_230_p4;
wire   [36:0] y_4_fu_240_p3;
wire   [21:0] tmp_616_fu_254_p4;
wire   [36:0] y_5_fu_264_p3;
wire   [21:0] tmp_617_fu_278_p4;
wire   [36:0] y_6_fu_288_p3;
wire   [21:0] tmp_618_fu_302_p4;
wire   [36:0] y_7_fu_312_p3;
wire   [21:0] tmp_619_fu_326_p4;
wire   [36:0] y_8_fu_336_p3;
wire   [21:0] tmp_620_fu_350_p4;
wire   [36:0] y_9_fu_360_p3;
wire   [21:0] tmp_621_fu_374_p4;
wire   [36:0] y_68_fu_384_p3;
wire   [21:0] tmp_622_fu_398_p4;
wire   [36:0] y_69_fu_408_p3;
wire   [21:0] tmp_623_fu_422_p4;
wire   [36:0] y_70_fu_432_p3;
wire   [36:0] trunc_ln3_fu_446_p4;
wire   [36:0] add_ln42_4_fu_224_p2;
wire   [36:0] add_ln42_8_fu_320_p2;
wire   [36:0] add_ln42_13_fu_440_p2;
wire   [36:0] add_ln42_6_fu_272_p2;
wire   [36:0] add_ln42_14_fu_456_p2;
wire   [36:0] add_ln42_12_fu_416_p2;
wire   [36:0] add_ln42_11_fu_392_p2;
wire   [36:0] add_ln42_10_fu_368_p2;
wire   [36:0] add_ln42_9_fu_344_p2;
wire   [36:0] add_ln42_7_fu_296_p2;
wire   [36:0] add_ln42_5_fu_248_p2;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_142;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

myproject_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(real_start),
    .ap_ready(internal_ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_142)) begin
        if ((icmp_ln25_fu_161_p2 == 1'd0)) begin
            i_03_fu_136 <= i_7_fu_167_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_03_fu_136 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        tmp_624_reg_659 <= {{add_ln42_8_fu_320_p2[36:21]}};
        tmp_625_reg_669 <= {{add_ln42_13_fu_440_p2[36:21]}};
        tmp_626_reg_684 <= {{add_ln42_6_fu_272_p2[36:21]}};
        tmp_627_reg_689 <= {{add_ln42_14_fu_456_p2[36:21]}};
        tmp_628_reg_694 <= {{add_ln42_12_fu_416_p2[36:21]}};
        tmp_629_reg_699 <= {{add_ln42_11_fu_392_p2[36:21]}};
        tmp_630_reg_704 <= {{add_ln42_10_fu_368_p2[36:21]}};
        tmp_631_reg_709 <= {{add_ln42_9_fu_344_p2[36:21]}};
        tmp_632_reg_714 <= {{add_ln42_7_fu_296_p2[36:21]}};
        tmp_633_reg_719 <= {{add_ln42_5_fu_248_p2[36:21]}};
        tmp_s_reg_679 <= {{layer6_out_dout[46:31]}};
        trunc_ln46_13_reg_674 <= {{layer6_out_dout[371:356]}};
        trunc_ln46_2_reg_654 <= {{add_ln42_4_fu_224_p2[36:21]}};
        trunc_ln46_7_reg_664 <= {{layer6_out_dout[221:206]}};
        trunc_ln4_reg_649 <= {{layer6_out_dout[71:56]}};
        trunc_ln_reg_644 <= {{add_ln42_fu_190_p2[36:21]}};
    end
end

always @ (*) begin
    if (((icmp_ln25_fu_161_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i = 7'd0;
    end else begin
        ap_sig_allocacmp_i = i_03_fu_136;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer21_out_blk_n = layer21_out_full_n;
    end else begin
        layer21_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer21_out_write = 1'b1;
    end else begin
        layer21_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer6_out_blk_n = layer6_out_empty_n;
    end else begin
        layer6_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer6_out_read = 1'b1;
    end else begin
        layer6_out_read = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln42_10_fu_368_p2 = ($signed(y_9_fu_360_p3) + $signed(37'd137371844608));

assign add_ln42_11_fu_392_p2 = (y_68_fu_384_p3 + 37'd134217728);

assign add_ln42_12_fu_416_p2 = (y_69_fu_408_p3 + 37'd134217728);

assign add_ln42_13_fu_440_p2 = ($signed(y_70_fu_432_p3) + $signed(37'd137304735744));

assign add_ln42_14_fu_456_p2 = ($signed(trunc_ln3_fu_446_p4) + $signed(37'd137371844608));

assign add_ln42_4_fu_224_p2 = ($signed(y_3_fu_216_p3) + $signed(37'd137371844608));

assign add_ln42_5_fu_248_p2 = ($signed(y_4_fu_240_p3) + $signed(37'd137304735744));

assign add_ln42_6_fu_272_p2 = ($signed(y_5_fu_264_p3) + $signed(37'd137371844608));

assign add_ln42_7_fu_296_p2 = (y_6_fu_288_p3 + 37'd67108864);

assign add_ln42_8_fu_320_p2 = (y_7_fu_312_p3 + 37'd201326592);

assign add_ln42_9_fu_344_p2 = (y_8_fu_336_p3 + 37'd201326592);

assign add_ln42_fu_190_p2 = (y_fu_182_p3 + 37'd201326592);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_done_reg == 1'b1) | ((layer21_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer6_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_done_reg == 1'b1) | ((layer21_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer6_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_done_reg == 1'b1) | ((layer21_out_full_n == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((layer6_out_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_done_reg == 1'b1) & (ap_start_int == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_done_reg == 1'b1);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (layer6_out_empty_n == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (layer21_out_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_142 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start_int == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = internal_ap_ready;

assign i_7_fu_167_p2 = (ap_sig_allocacmp_i + 7'd1);

assign icmp_ln25_fu_161_p2 = ((ap_sig_allocacmp_i == 7'd64) ? 1'b1 : 1'b0);

assign layer21_out_din = {{{{{{{{{{{{{{{{tmp_627_reg_689}, {trunc_ln46_13_reg_674}}, {tmp_625_reg_669}}, {tmp_628_reg_694}}, {tmp_629_reg_699}}, {tmp_630_reg_704}}, {tmp_631_reg_709}}, {trunc_ln46_7_reg_664}}, {tmp_624_reg_659}}, {tmp_632_reg_714}}, {tmp_626_reg_684}}, {tmp_633_reg_719}}, {trunc_ln46_2_reg_654}}, {trunc_ln4_reg_649}}, {tmp_s_reg_679}}, {trunc_ln_reg_644}};

assign start_out = real_start;

assign tmp_614_fu_206_p4 = {{layer6_out_dout[98:75]}};

assign tmp_615_fu_230_p4 = {{layer6_out_dout[121:100]}};

assign tmp_616_fu_254_p4 = {{layer6_out_dout[146:125]}};

assign tmp_617_fu_278_p4 = {{layer6_out_dout[171:150]}};

assign tmp_618_fu_302_p4 = {{layer6_out_dout[196:175]}};

assign tmp_619_fu_326_p4 = {{layer6_out_dout[246:225]}};

assign tmp_620_fu_350_p4 = {{layer6_out_dout[271:250]}};

assign tmp_621_fu_374_p4 = {{layer6_out_dout[296:275]}};

assign tmp_622_fu_398_p4 = {{layer6_out_dout[321:300]}};

assign tmp_623_fu_422_p4 = {{layer6_out_dout[346:325]}};

assign trunc_ln3_fu_446_p4 = {{layer6_out_dout[395:359]}};

assign trunc_ln85_fu_178_p1 = layer6_out_dout[21:0];

assign y_3_fu_216_p3 = {{tmp_614_fu_206_p4}, {13'd0}};

assign y_4_fu_240_p3 = {{tmp_615_fu_230_p4}, {15'd0}};

assign y_5_fu_264_p3 = {{tmp_616_fu_254_p4}, {15'd0}};

assign y_68_fu_384_p3 = {{tmp_621_fu_374_p4}, {15'd0}};

assign y_69_fu_408_p3 = {{tmp_622_fu_398_p4}, {15'd0}};

assign y_6_fu_288_p3 = {{tmp_617_fu_278_p4}, {15'd0}};

assign y_70_fu_432_p3 = {{tmp_623_fu_422_p4}, {15'd0}};

assign y_7_fu_312_p3 = {{tmp_618_fu_302_p4}, {15'd0}};

assign y_8_fu_336_p3 = {{tmp_619_fu_326_p4}, {15'd0}};

assign y_9_fu_360_p3 = {{tmp_620_fu_350_p4}, {15'd0}};

assign y_fu_182_p3 = {{trunc_ln85_fu_178_p1}, {15'd0}};

endmodule //myproject_normalize_array_ap_fixed_16u_array_ap_fixed_16_6_5_3_0_16u_config21_s
