// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer17_out_dout,
        layer17_out_num_data_valid,
        layer17_out_fifo_cap,
        layer17_out_empty_n,
        layer17_out_read,
        layer24_out_din,
        layer24_out_num_data_valid,
        layer24_out_fifo_cap,
        layer24_out_full_n,
        layer24_out_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [159:0] layer17_out_dout;
input  [1:0] layer17_out_num_data_valid;
input  [1:0] layer17_out_fifo_cap;
input   layer17_out_empty_n;
output   layer17_out_read;
output  [159:0] layer24_out_din;
input  [1:0] layer24_out_num_data_valid;
input  [1:0] layer24_out_fifo_cap;
input   layer24_out_full_n;
output   layer24_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer17_out_read;
reg layer24_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer17_out_blk_n;
reg    layer24_out_blk_n;
wire    ap_CS_fsm_state2;
reg   [14:0] trunc_ln_reg_451;
reg    ap_block_state1;
reg   [14:0] trunc_ln41_s_reg_456;
reg   [13:0] trunc_ln41_12_reg_461;
reg   [12:0] trunc_ln41_13_reg_466;
reg   [13:0] trunc_ln41_14_reg_471;
reg   [14:0] trunc_ln41_15_reg_476;
reg   [13:0] trunc_ln41_16_reg_481;
reg   [14:0] trunc_ln41_17_reg_486;
reg   [13:0] trunc_ln41_18_reg_491;
reg   [0:0] tmp_reg_496;
reg   [13:0] tmp_s_reg_501;
wire   [15:0] trunc_ln85_fu_119_p1;
wire   [23:0] y_fu_123_p3;
wire  signed [24:0] sext_ln85_fu_131_p1;
wire   [24:0] add_ln42_fu_135_p2;
wire   [15:0] tmp_634_fu_151_p4;
wire   [23:0] y_71_fu_161_p3;
wire  signed [24:0] sext_ln85_1_fu_169_p1;
wire   [24:0] add_ln42_70_fu_173_p2;
wire   [15:0] tmp_635_fu_219_p4;
wire   [23:0] y_72_fu_229_p3;
wire  signed [24:0] sext_ln85_2_fu_237_p1;
wire   [15:0] tmp_636_fu_247_p4;
wire   [23:0] y_73_fu_257_p3;
wire  signed [24:0] sext_ln85_3_fu_265_p1;
wire   [24:0] add_ln42_72_fu_269_p2;
wire   [15:0] tmp_637_fu_285_p4;
wire   [22:0] y_74_fu_295_p3;
wire  signed [23:0] sext_ln85_4_fu_303_p1;
wire   [23:0] add_ln42_73_fu_307_p2;
wire   [15:0] tmp_638_fu_323_p4;
wire   [23:0] y_75_fu_333_p3;
wire  signed [24:0] sext_ln85_5_fu_341_p1;
wire   [24:0] add_ln42_74_fu_345_p2;
wire   [24:0] add_ln42_71_fu_241_p2;
wire  signed [15:0] sext_ln46_1_fu_395_p1;
wire   [28:0] tmp_639_fu_410_p3;
wire  signed [15:0] sext_ln46_5_fu_407_p1;
wire  signed [15:0] sext_ln46_4_fu_404_p1;
wire  signed [15:0] sext_ln46_3_fu_401_p1;
wire  signed [14:0] sext_ln46_7_fu_421_p1;
wire  signed [15:0] sext_ln46_2_fu_398_p1;
wire  signed [31:0] sext_ln46_6_fu_417_p1;
wire  signed [15:0] sext_ln46_fu_392_p1;
wire  signed [15:0] sext_ln41_fu_389_p1;
wire   [157:0] tmp_618_fu_424_p11;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer24_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (layer17_out_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_reg_496 <= add_ln42_71_fu_241_p2[32'd10];
        tmp_s_reg_501 <= {{add_ln42_71_fu_241_p2[24:11]}};
        trunc_ln41_12_reg_461 <= {{layer17_out_dout[47:34]}};
        trunc_ln41_13_reg_466 <= {{layer17_out_dout[63:51]}};
        trunc_ln41_14_reg_471 <= {{layer17_out_dout[79:66]}};
        trunc_ln41_15_reg_476 <= {{add_ln42_72_fu_269_p2[24:10]}};
        trunc_ln41_16_reg_481 <= {{add_ln42_73_fu_307_p2[23:10]}};
        trunc_ln41_17_reg_486 <= {{add_ln42_74_fu_345_p2[24:10]}};
        trunc_ln41_18_reg_491 <= {{layer17_out_dout[159:146]}};
        trunc_ln41_s_reg_456 <= {{add_ln42_70_fu_173_p2[24:10]}};
        trunc_ln_reg_451 <= {{add_ln42_fu_135_p2[24:10]}};
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (layer17_out_empty_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer24_out_full_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer24_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer24_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer17_out_blk_n = layer17_out_empty_n;
    end else begin
        layer17_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (layer17_out_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer17_out_read = 1'b1;
    end else begin
        layer17_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer24_out_blk_n = layer24_out_full_n;
    end else begin
        layer24_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer24_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        layer24_out_write = 1'b1;
    end else begin
        layer24_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (layer17_out_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((layer24_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln42_70_fu_173_p2 = ($signed(sext_ln85_1_fu_169_p1) + $signed(25'd33488896));

assign add_ln42_71_fu_241_p2 = ($signed(sext_ln85_2_fu_237_p1) + $signed(25'd33456128));

assign add_ln42_72_fu_269_p2 = ($signed(sext_ln85_3_fu_265_p1) + $signed(25'd32768));

assign add_ln42_73_fu_307_p2 = ($signed(sext_ln85_4_fu_303_p1) + $signed(24'd16711680));

assign add_ln42_74_fu_345_p2 = ($signed(sext_ln85_5_fu_341_p1) + $signed(25'd196608));

assign add_ln42_fu_135_p2 = ($signed(sext_ln85_fu_131_p1) + $signed(25'd33521664));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer17_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign layer24_out_din = $signed(tmp_618_fu_424_p11);

assign sext_ln41_fu_389_p1 = $signed(trunc_ln_reg_451);

assign sext_ln46_1_fu_395_p1 = $signed(trunc_ln41_12_reg_461);

assign sext_ln46_2_fu_398_p1 = $signed(trunc_ln41_14_reg_471);

assign sext_ln46_3_fu_401_p1 = $signed(trunc_ln41_15_reg_476);

assign sext_ln46_4_fu_404_p1 = $signed(trunc_ln41_16_reg_481);

assign sext_ln46_5_fu_407_p1 = $signed(trunc_ln41_17_reg_486);

assign sext_ln46_6_fu_417_p1 = $signed(tmp_639_fu_410_p3);

assign sext_ln46_7_fu_421_p1 = $signed(tmp_s_reg_501);

assign sext_ln46_fu_392_p1 = $signed(trunc_ln41_s_reg_456);

assign sext_ln85_1_fu_169_p1 = $signed(y_71_fu_161_p3);

assign sext_ln85_2_fu_237_p1 = $signed(y_72_fu_229_p3);

assign sext_ln85_3_fu_265_p1 = $signed(y_73_fu_257_p3);

assign sext_ln85_4_fu_303_p1 = $signed(y_74_fu_295_p3);

assign sext_ln85_5_fu_341_p1 = $signed(y_75_fu_333_p3);

assign sext_ln85_fu_131_p1 = $signed(y_fu_123_p3);

assign start_out = real_start;

assign tmp_618_fu_424_p11 = {{{{{{{{{{trunc_ln41_18_reg_491}, {sext_ln46_5_fu_407_p1}}, {sext_ln46_4_fu_404_p1}}, {sext_ln46_3_fu_401_p1}}, {sext_ln46_7_fu_421_p1}}, {tmp_reg_496}}, {sext_ln46_2_fu_398_p1}}, {sext_ln46_6_fu_417_p1}}, {sext_ln46_fu_392_p1}}, {sext_ln41_fu_389_p1}};

assign tmp_634_fu_151_p4 = {{layer17_out_dout[31:16]}};

assign tmp_635_fu_219_p4 = {{layer17_out_dout[95:80]}};

assign tmp_636_fu_247_p4 = {{layer17_out_dout[111:96]}};

assign tmp_637_fu_285_p4 = {{layer17_out_dout[127:112]}};

assign tmp_638_fu_323_p4 = {{layer17_out_dout[143:128]}};

assign tmp_639_fu_410_p3 = {{trunc_ln41_13_reg_466}, {sext_ln46_1_fu_395_p1}};

assign trunc_ln85_fu_119_p1 = layer17_out_dout[15:0];

assign y_71_fu_161_p3 = {{tmp_634_fu_151_p4}, {8'd0}};

assign y_72_fu_229_p3 = {{tmp_635_fu_219_p4}, {8'd0}};

assign y_73_fu_257_p3 = {{tmp_636_fu_247_p4}, {8'd0}};

assign y_74_fu_295_p3 = {{tmp_637_fu_285_p4}, {7'd0}};

assign y_75_fu_333_p3 = {{tmp_638_fu_323_p4}, {8'd0}};

assign y_fu_123_p3 = {{trunc_ln85_fu_119_p1}, {8'd0}};

endmodule //myproject_normalize_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_config24_s
