// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        layer11_out_dout,
        layer11_out_num_data_valid,
        layer11_out_fifo_cap,
        layer11_out_empty_n,
        layer11_out_read,
        layer22_out_din,
        layer22_out_num_data_valid,
        layer22_out_fifo_cap,
        layer22_out_full_n,
        layer22_out_write
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [2999:0] layer11_out_dout;
input  [1:0] layer11_out_num_data_valid;
input  [1:0] layer11_out_fifo_cap;
input   layer11_out_empty_n;
output   layer11_out_read;
output  [1919:0] layer22_out_din;
input  [1:0] layer22_out_num_data_valid;
input  [1:0] layer22_out_fifo_cap;
input   layer22_out_full_n;
output   layer22_out_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg layer11_out_read;
reg layer22_out_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    layer11_out_blk_n;
reg    layer22_out_blk_n;
wire    ap_CS_fsm_state2;
reg   [15:0] trunc_ln_reg_4185;
reg    ap_block_state1;
reg   [15:0] trunc_ln41_3_reg_4190;
reg   [0:0] tmp_reg_4195;
reg   [15:0] trunc_ln46_17_reg_4200;
reg   [15:0] trunc_ln46_18_reg_4205;
reg   [15:0] trunc_ln46_21_reg_4210;
reg   [15:0] trunc_ln46_22_reg_4215;
reg   [15:0] trunc_ln46_23_reg_4220;
reg   [15:0] trunc_ln46_24_reg_4225;
reg   [15:0] trunc_ln46_25_reg_4230;
reg   [15:0] trunc_ln46_26_reg_4235;
reg   [15:0] trunc_ln46_27_reg_4240;
reg   [15:0] trunc_ln46_28_reg_4245;
reg   [15:0] trunc_ln46_31_reg_4250;
reg   [15:0] trunc_ln46_32_reg_4255;
reg   [15:0] trunc_ln46_35_reg_4260;
reg   [15:0] trunc_ln46_36_reg_4265;
reg   [15:0] trunc_ln46_39_reg_4270;
reg   [15:0] trunc_ln46_42_reg_4275;
reg   [15:0] trunc_ln46_45_reg_4280;
reg   [15:0] trunc_ln46_46_reg_4285;
reg   [15:0] trunc_ln46_47_reg_4290;
reg   [15:0] trunc_ln46_50_reg_4295;
reg   [15:0] trunc_ln46_s_reg_4300;
reg   [15:0] trunc_ln46_51_reg_4305;
reg   [15:0] trunc_ln46_52_reg_4310;
reg   [15:0] trunc_ln46_53_reg_4315;
reg   [15:0] trunc_ln46_54_reg_4320;
reg   [15:0] trunc_ln46_55_reg_4325;
reg   [15:0] trunc_ln46_56_reg_4330;
reg   [15:0] trunc_ln46_57_reg_4335;
reg   [15:0] trunc_ln46_58_reg_4340;
reg   [15:0] trunc_ln46_59_reg_4345;
reg   [15:0] trunc_ln46_60_reg_4350;
reg   [15:0] trunc_ln46_61_reg_4355;
reg   [15:0] trunc_ln46_62_reg_4360;
reg   [15:0] trunc_ln46_63_reg_4365;
reg   [15:0] trunc_ln46_64_reg_4370;
reg   [15:0] trunc_ln46_65_reg_4375;
reg   [15:0] trunc_ln46_66_reg_4380;
reg   [15:0] trunc_ln46_67_reg_4385;
reg   [15:0] trunc_ln46_68_reg_4390;
reg   [15:0] trunc_ln46_69_reg_4395;
reg   [15:0] trunc_ln46_70_reg_4400;
reg   [15:0] trunc_ln46_71_reg_4405;
reg   [15:0] trunc_ln46_72_reg_4410;
reg   [15:0] trunc_ln46_73_reg_4415;
reg   [15:0] trunc_ln46_74_reg_4420;
reg   [15:0] trunc_ln46_75_reg_4425;
reg   [15:0] trunc_ln46_76_reg_4430;
reg   [15:0] trunc_ln46_77_reg_4435;
reg   [15:0] trunc_ln46_78_reg_4440;
reg   [15:0] trunc_ln46_79_reg_4445;
reg   [15:0] trunc_ln46_80_reg_4450;
reg   [15:0] trunc_ln46_81_reg_4455;
reg   [15:0] trunc_ln46_82_reg_4460;
reg   [15:0] trunc_ln46_83_reg_4465;
reg   [15:0] trunc_ln46_84_reg_4470;
reg   [15:0] trunc_ln46_85_reg_4475;
reg   [15:0] trunc_ln46_86_reg_4480;
reg   [15:0] trunc_ln46_87_reg_4485;
reg   [15:0] trunc_ln46_88_reg_4490;
reg   [15:0] trunc_ln46_89_reg_4495;
reg   [15:0] trunc_ln46_90_reg_4500;
reg   [15:0] trunc_ln46_91_reg_4505;
reg   [15:0] trunc_ln46_92_reg_4510;
reg   [15:0] trunc_ln46_93_reg_4515;
reg   [15:0] trunc_ln46_94_reg_4520;
reg   [15:0] trunc_ln46_95_reg_4525;
reg   [15:0] trunc_ln46_96_reg_4530;
reg   [15:0] trunc_ln46_97_reg_4535;
reg   [15:0] trunc_ln46_98_reg_4540;
reg   [15:0] trunc_ln46_99_reg_4545;
reg   [15:0] trunc_ln46_100_reg_4550;
reg   [15:0] trunc_ln46_101_reg_4555;
reg   [15:0] trunc_ln46_102_reg_4560;
reg   [15:0] trunc_ln46_103_reg_4565;
reg   [15:0] trunc_ln46_104_reg_4570;
reg   [15:0] trunc_ln46_105_reg_4575;
reg   [15:0] tmp_733_reg_4580;
reg   [14:0] tmp_s_reg_4585;
reg   [15:0] tmp_734_reg_4590;
reg   [15:0] tmp_735_reg_4595;
reg   [15:0] tmp_736_reg_4600;
reg   [15:0] tmp_737_reg_4605;
reg   [15:0] tmp_738_reg_4610;
reg   [15:0] tmp_739_reg_4615;
reg   [15:0] tmp_740_reg_4620;
reg   [15:0] tmp_741_reg_4625;
reg   [15:0] tmp_742_reg_4630;
reg   [15:0] tmp_743_reg_4635;
reg   [15:0] tmp_744_reg_4640;
reg   [15:0] tmp_745_reg_4645;
reg   [15:0] tmp_746_reg_4650;
reg   [15:0] tmp_747_reg_4655;
reg   [15:0] tmp_748_reg_4660;
reg   [15:0] tmp_749_reg_4665;
reg   [15:0] tmp_750_reg_4670;
reg   [15:0] tmp_751_reg_4675;
reg   [15:0] tmp_752_reg_4680;
reg   [15:0] tmp_753_reg_4685;
reg   [15:0] tmp_754_reg_4690;
reg   [15:0] tmp_755_reg_4695;
reg   [15:0] tmp_756_reg_4700;
reg   [15:0] tmp_757_reg_4705;
reg   [15:0] tmp_758_reg_4710;
reg   [15:0] tmp_759_reg_4715;
reg   [15:0] tmp_760_reg_4720;
reg   [15:0] tmp_761_reg_4725;
reg   [15:0] tmp_762_reg_4730;
reg   [15:0] tmp_763_reg_4735;
reg   [15:0] tmp_764_reg_4740;
reg   [15:0] tmp_765_reg_4745;
reg   [15:0] tmp_766_reg_4750;
reg   [15:0] tmp_767_reg_4755;
reg   [15:0] tmp_768_reg_4760;
reg   [15:0] tmp_769_reg_4765;
reg   [15:0] tmp_770_reg_4770;
reg   [15:0] tmp_771_reg_4775;
reg   [15:0] tmp_772_reg_4780;
reg   [15:0] tmp_773_reg_4785;
wire   [21:0] trunc_ln85_fu_569_p1;
wire   [36:0] y_fu_573_p3;
wire   [36:0] add_ln42_fu_581_p2;
wire   [22:0] tmp_640_fu_597_p4;
wire   [36:0] y_76_fu_607_p3;
wire   [22:0] tmp_641_fu_621_p4;
wire   [36:0] y_77_fu_631_p3;
wire   [21:0] tmp_642_fu_655_p4;
wire   [36:0] y_78_fu_665_p3;
wire   [21:0] tmp_643_fu_679_p4;
wire   [36:0] y_79_fu_689_p3;
wire   [23:0] tmp_644_fu_703_p4;
wire   [36:0] y_80_fu_713_p3;
wire   [21:0] tmp_645_fu_727_p4;
wire   [36:0] y_81_fu_737_p3;
wire   [21:0] tmp_646_fu_751_p4;
wire   [36:0] y_82_fu_761_p3;
wire   [21:0] tmp_647_fu_775_p4;
wire   [36:0] y_83_fu_785_p3;
wire   [22:0] tmp_648_fu_799_p4;
wire   [36:0] y_84_fu_809_p3;
wire   [21:0] tmp_649_fu_823_p4;
wire   [36:0] y_85_fu_833_p3;
wire   [21:0] tmp_650_fu_847_p4;
wire   [36:0] y_86_fu_857_p3;
wire   [22:0] tmp_651_fu_871_p4;
wire   [36:0] y_87_fu_881_p3;
wire   [21:0] tmp_652_fu_895_p4;
wire   [36:0] y_88_fu_905_p3;
wire   [21:0] tmp_653_fu_919_p4;
wire   [36:0] y_89_fu_929_p3;
wire   [21:0] tmp_654_fu_943_p4;
wire   [36:0] y_90_fu_953_p3;
wire   [21:0] tmp_655_fu_967_p4;
wire   [36:0] y_91_fu_977_p3;
wire   [21:0] tmp_656_fu_991_p4;
wire   [36:0] y_92_fu_1001_p3;
wire   [21:0] tmp_657_fu_1015_p4;
wire   [36:0] y_93_fu_1025_p3;
wire   [21:0] tmp_658_fu_1039_p4;
wire   [36:0] y_94_fu_1049_p3;
wire   [21:0] tmp_659_fu_1063_p4;
wire   [36:0] y_95_fu_1073_p3;
wire   [21:0] tmp_660_fu_1087_p4;
wire   [36:0] y_96_fu_1097_p3;
wire   [21:0] tmp_661_fu_1111_p4;
wire   [36:0] y_97_fu_1121_p3;
wire   [21:0] tmp_662_fu_1135_p4;
wire   [36:0] y_98_fu_1145_p3;
wire   [21:0] tmp_663_fu_1159_p4;
wire   [36:0] y_99_fu_1169_p3;
wire   [22:0] tmp_664_fu_1183_p4;
wire   [36:0] y_100_fu_1193_p3;
wire   [21:0] tmp_665_fu_1207_p4;
wire   [36:0] y_101_fu_1217_p3;
wire   [21:0] tmp_666_fu_1231_p4;
wire   [36:0] y_102_fu_1241_p3;
wire   [21:0] tmp_667_fu_1255_p4;
wire   [36:0] y_103_fu_1265_p3;
wire   [21:0] tmp_668_fu_1279_p4;
wire   [36:0] y_104_fu_1289_p3;
wire   [22:0] tmp_669_fu_1303_p4;
wire   [36:0] y_105_fu_1313_p3;
wire   [21:0] tmp_670_fu_1327_p4;
wire   [36:0] y_106_fu_1337_p3;
wire   [21:0] tmp_671_fu_1351_p4;
wire   [36:0] y_107_fu_1361_p3;
wire   [21:0] tmp_672_fu_1375_p4;
wire   [36:0] y_108_fu_1385_p3;
wire   [21:0] tmp_673_fu_1399_p4;
wire   [36:0] y_109_fu_1409_p3;
wire   [21:0] tmp_674_fu_1423_p4;
wire   [36:0] y_110_fu_1433_p3;
wire   [21:0] tmp_675_fu_1447_p4;
wire   [36:0] y_111_fu_1457_p3;
wire   [22:0] tmp_676_fu_1471_p4;
wire   [36:0] y_112_fu_1481_p3;
wire   [21:0] tmp_677_fu_1495_p4;
wire   [36:0] y_113_fu_1505_p3;
wire   [21:0] tmp_678_fu_1519_p4;
wire   [36:0] y_114_fu_1529_p3;
wire   [21:0] tmp_679_fu_1543_p4;
wire   [36:0] y_115_fu_1553_p3;
wire   [21:0] tmp_680_fu_1567_p4;
wire   [36:0] y_116_fu_1577_p3;
wire   [22:0] tmp_681_fu_1591_p4;
wire   [36:0] y_117_fu_1601_p3;
wire   [22:0] tmp_682_fu_1615_p4;
wire   [36:0] y_118_fu_1625_p3;
wire   [21:0] tmp_683_fu_1639_p4;
wire   [36:0] y_119_fu_1649_p3;
wire   [22:0] tmp_684_fu_1663_p4;
wire   [36:0] y_120_fu_1673_p3;
wire   [21:0] tmp_685_fu_1687_p4;
wire   [36:0] y_121_fu_1697_p3;
wire   [21:0] tmp_686_fu_1711_p4;
wire   [36:0] y_122_fu_1721_p3;
wire   [21:0] tmp_687_fu_1735_p4;
wire   [36:0] y_123_fu_1745_p3;
wire   [21:0] tmp_688_fu_1759_p4;
wire   [36:0] y_124_fu_1769_p3;
wire   [21:0] tmp_689_fu_1783_p4;
wire   [36:0] y_125_fu_1793_p3;
wire   [21:0] tmp_690_fu_1807_p4;
wire   [36:0] y_126_fu_1817_p3;
wire   [21:0] tmp_691_fu_1831_p4;
wire   [36:0] y_127_fu_1841_p3;
wire   [22:0] tmp_692_fu_1855_p4;
wire   [36:0] y_128_fu_1865_p3;
wire   [22:0] tmp_693_fu_1879_p4;
wire   [36:0] y_129_fu_1889_p3;
wire   [21:0] tmp_694_fu_1903_p4;
wire   [36:0] y_130_fu_1913_p3;
wire   [21:0] tmp_695_fu_1927_p4;
wire   [36:0] y_131_fu_1937_p3;
wire   [23:0] tmp_696_fu_1951_p4;
wire   [36:0] y_132_fu_1961_p3;
wire   [22:0] tmp_697_fu_1975_p4;
wire   [36:0] y_133_fu_1985_p3;
wire   [22:0] tmp_698_fu_1999_p4;
wire   [36:0] y_134_fu_2009_p3;
wire   [21:0] tmp_699_fu_2023_p4;
wire   [36:0] y_135_fu_2033_p3;
wire   [22:0] tmp_700_fu_2047_p4;
wire   [36:0] y_136_fu_2057_p3;
wire   [21:0] tmp_701_fu_2071_p4;
wire   [36:0] y_137_fu_2081_p3;
wire   [21:0] tmp_702_fu_2095_p4;
wire   [36:0] y_138_fu_2105_p3;
wire   [21:0] tmp_703_fu_2119_p4;
wire   [36:0] y_139_fu_2129_p3;
wire   [23:0] tmp_704_fu_2143_p4;
wire   [36:0] y_140_fu_2153_p3;
wire   [21:0] tmp_705_fu_2167_p4;
wire   [36:0] y_141_fu_2177_p3;
wire   [21:0] tmp_706_fu_2191_p4;
wire   [36:0] y_142_fu_2201_p3;
wire   [21:0] tmp_707_fu_2215_p4;
wire   [36:0] y_143_fu_2225_p3;
wire   [23:0] tmp_708_fu_2239_p4;
wire   [36:0] y_144_fu_2249_p3;
wire   [23:0] tmp_709_fu_2263_p4;
wire   [36:0] y_145_fu_2273_p3;
wire   [21:0] tmp_710_fu_2287_p4;
wire   [36:0] y_146_fu_2297_p3;
wire   [22:0] tmp_711_fu_2311_p4;
wire   [36:0] y_147_fu_2321_p3;
wire   [22:0] tmp_712_fu_2335_p4;
wire   [36:0] y_148_fu_2345_p3;
wire   [21:0] tmp_713_fu_2359_p4;
wire   [36:0] y_149_fu_2369_p3;
wire   [21:0] tmp_714_fu_2383_p4;
wire   [36:0] y_150_fu_2393_p3;
wire   [21:0] tmp_715_fu_2407_p4;
wire   [36:0] y_151_fu_2417_p3;
wire   [21:0] tmp_716_fu_2431_p4;
wire   [36:0] y_152_fu_2441_p3;
wire   [21:0] tmp_717_fu_2455_p4;
wire   [36:0] y_153_fu_2465_p3;
wire   [22:0] tmp_718_fu_2479_p4;
wire   [36:0] y_154_fu_2489_p3;
wire   [21:0] tmp_719_fu_2503_p4;
wire   [36:0] y_155_fu_2513_p3;
wire   [21:0] tmp_720_fu_2527_p4;
wire   [36:0] y_156_fu_2537_p3;
wire   [21:0] tmp_721_fu_2551_p4;
wire   [36:0] y_157_fu_2561_p3;
wire   [22:0] tmp_722_fu_2575_p4;
wire   [36:0] y_158_fu_2585_p3;
wire   [21:0] tmp_723_fu_2599_p4;
wire   [36:0] y_159_fu_2609_p3;
wire   [22:0] tmp_724_fu_2623_p4;
wire   [36:0] y_160_fu_2633_p3;
wire   [21:0] tmp_725_fu_2647_p4;
wire   [36:0] y_161_fu_2657_p3;
wire   [21:0] tmp_726_fu_2671_p4;
wire   [36:0] y_162_fu_2681_p3;
wire   [23:0] tmp_727_fu_2695_p4;
wire   [36:0] y_163_fu_2705_p3;
wire   [21:0] tmp_728_fu_2719_p4;
wire   [36:0] y_164_fu_2729_p3;
wire   [21:0] tmp_729_fu_2743_p4;
wire   [36:0] y_165_fu_2753_p3;
wire   [22:0] tmp_730_fu_2767_p4;
wire   [36:0] y_166_fu_2777_p3;
wire   [21:0] tmp_731_fu_2791_p4;
wire   [36:0] y_167_fu_2801_p3;
wire   [21:0] tmp_732_fu_2815_p4;
wire   [36:0] y_168_fu_2825_p3;
wire   [36:0] trunc_ln5_fu_2839_p4;
wire   [36:0] trunc_ln85_1_fu_2855_p4;
wire   [36:0] add_ln42_18_fu_697_p2;
wire   [36:0] add_ln42_19_fu_721_p2;
wire   [36:0] add_ln42_22_fu_793_p2;
wire   [36:0] add_ln42_23_fu_817_p2;
wire   [36:0] add_ln42_24_fu_841_p2;
wire   [36:0] add_ln42_25_fu_865_p2;
wire   [36:0] add_ln42_26_fu_889_p2;
wire   [36:0] add_ln42_27_fu_913_p2;
wire   [36:0] add_ln42_28_fu_937_p2;
wire   [36:0] add_ln42_31_fu_1009_p2;
wire   [36:0] add_ln42_34_fu_1081_p2;
wire   [36:0] add_ln42_41_fu_1249_p2;
wire   [36:0] add_ln42_42_fu_1273_p2;
wire   [36:0] add_ln42_45_fu_1345_p2;
wire   [36:0] add_ln42_46_fu_1369_p2;
wire   [36:0] add_ln42_49_fu_1441_p2;
wire   [36:0] add_ln42_50_fu_1465_p2;
wire   [36:0] add_ln42_51_fu_1489_p2;
wire   [36:0] add_ln42_52_fu_1513_p2;
wire   [36:0] add_ln42_53_fu_1537_p2;
wire   [36:0] add_ln42_54_fu_1561_p2;
wire   [36:0] add_ln42_55_fu_1585_p2;
wire   [36:0] add_ln42_58_fu_1657_p2;
wire   [36:0] add_ln42_59_fu_1681_p2;
wire   [36:0] add_ln42_60_fu_1705_p2;
wire   [36:0] add_ln42_61_fu_1729_p2;
wire   [36:0] add_ln42_62_fu_1753_p2;
wire   [36:0] add_ln42_63_fu_1777_p2;
wire   [36:0] add_ln42_64_fu_1801_p2;
wire   [36:0] add_ln42_65_fu_1825_p2;
wire   [36:0] add_ln42_68_fu_1897_p2;
wire   [36:0] add_ln42_69_fu_1921_p2;
wire   [36:0] add_ln42_70_fu_1945_p2;
wire   [36:0] add_ln42_71_fu_1969_p2;
wire   [36:0] add_ln42_72_fu_1993_p2;
wire   [36:0] add_ln42_73_fu_2017_p2;
wire   [36:0] add_ln42_74_fu_2041_p2;
wire   [36:0] add_ln42_77_fu_2113_p2;
wire   [36:0] add_ln42_80_fu_2185_p2;
wire   [36:0] add_ln42_81_fu_2209_p2;
wire   [36:0] add_ln42_82_fu_2233_p2;
wire   [36:0] add_ln42_83_fu_2257_p2;
wire   [36:0] add_ln42_84_fu_2281_p2;
wire   [36:0] add_ln42_85_fu_2305_p2;
wire   [36:0] add_ln42_86_fu_2329_p2;
wire   [36:0] add_ln42_92_fu_2473_p2;
wire   [36:0] add_ln42_97_fu_2593_p2;
wire   [36:0] add_ln42_98_fu_2617_p2;
wire   [36:0] add_ln42_99_fu_2641_p2;
wire   [36:0] add_ln42_100_fu_2665_p2;
wire   [36:0] add_ln42_107_fu_2833_p2;
wire   [36:0] add_ln42_108_fu_2849_p2;
wire   [36:0] add_ln42_109_fu_2865_p2;
wire   [36:0] add_ln42_16_fu_639_p2;
wire   [36:0] add_ln42_17_fu_673_p2;
wire   [36:0] add_ln42_35_fu_1105_p2;
wire   [36:0] add_ln42_106_fu_2809_p2;
wire   [36:0] add_ln42_105_fu_2785_p2;
wire   [36:0] add_ln42_104_fu_2761_p2;
wire   [36:0] add_ln42_103_fu_2737_p2;
wire   [36:0] add_ln42_102_fu_2713_p2;
wire   [36:0] add_ln42_101_fu_2689_p2;
wire   [36:0] add_ln42_96_fu_2569_p2;
wire   [36:0] add_ln42_95_fu_2545_p2;
wire   [36:0] add_ln42_94_fu_2521_p2;
wire   [36:0] add_ln42_93_fu_2497_p2;
wire   [36:0] add_ln42_91_fu_2449_p2;
wire   [36:0] add_ln42_90_fu_2425_p2;
wire   [36:0] add_ln42_89_fu_2401_p2;
wire   [36:0] add_ln42_88_fu_2377_p2;
wire   [36:0] add_ln42_87_fu_2353_p2;
wire   [36:0] add_ln42_79_fu_2161_p2;
wire   [36:0] add_ln42_78_fu_2137_p2;
wire   [36:0] add_ln42_76_fu_2089_p2;
wire   [36:0] add_ln42_75_fu_2065_p2;
wire   [36:0] add_ln42_67_fu_1873_p2;
wire   [36:0] add_ln42_66_fu_1849_p2;
wire   [36:0] add_ln42_57_fu_1633_p2;
wire   [36:0] add_ln42_56_fu_1609_p2;
wire   [36:0] add_ln42_48_fu_1417_p2;
wire   [36:0] add_ln42_47_fu_1393_p2;
wire   [36:0] add_ln42_44_fu_1321_p2;
wire   [36:0] add_ln42_43_fu_1297_p2;
wire   [36:0] add_ln42_40_fu_1225_p2;
wire   [36:0] add_ln42_39_fu_1201_p2;
wire   [36:0] add_ln42_38_fu_1177_p2;
wire   [36:0] add_ln42_37_fu_1153_p2;
wire   [36:0] add_ln42_36_fu_1129_p2;
wire   [36:0] add_ln42_33_fu_1057_p2;
wire   [36:0] add_ln42_32_fu_1033_p2;
wire   [36:0] add_ln42_30_fu_985_p2;
wire   [36:0] add_ln42_29_fu_961_p2;
wire   [36:0] add_ln42_21_fu_769_p2;
wire   [36:0] add_ln42_20_fu_745_p2;
wire   [36:0] add_ln42_15_fu_615_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 2'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((layer22_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((real_start == 1'b0) | (layer11_out_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_733_reg_4580 <= {{add_ln42_16_fu_639_p2[36:21]}};
        tmp_734_reg_4590 <= {{add_ln42_35_fu_1105_p2[36:21]}};
        tmp_735_reg_4595 <= {{add_ln42_106_fu_2809_p2[36:21]}};
        tmp_736_reg_4600 <= {{add_ln42_105_fu_2785_p2[36:21]}};
        tmp_737_reg_4605 <= {{add_ln42_104_fu_2761_p2[36:21]}};
        tmp_738_reg_4610 <= {{add_ln42_103_fu_2737_p2[36:21]}};
        tmp_739_reg_4615 <= {{add_ln42_102_fu_2713_p2[36:21]}};
        tmp_740_reg_4620 <= {{add_ln42_101_fu_2689_p2[36:21]}};
        tmp_741_reg_4625 <= {{add_ln42_96_fu_2569_p2[36:21]}};
        tmp_742_reg_4630 <= {{add_ln42_95_fu_2545_p2[36:21]}};
        tmp_743_reg_4635 <= {{add_ln42_94_fu_2521_p2[36:21]}};
        tmp_744_reg_4640 <= {{add_ln42_93_fu_2497_p2[36:21]}};
        tmp_745_reg_4645 <= {{add_ln42_91_fu_2449_p2[36:21]}};
        tmp_746_reg_4650 <= {{add_ln42_90_fu_2425_p2[36:21]}};
        tmp_747_reg_4655 <= {{add_ln42_89_fu_2401_p2[36:21]}};
        tmp_748_reg_4660 <= {{add_ln42_88_fu_2377_p2[36:21]}};
        tmp_749_reg_4665 <= {{add_ln42_87_fu_2353_p2[36:21]}};
        tmp_750_reg_4670 <= {{add_ln42_79_fu_2161_p2[36:21]}};
        tmp_751_reg_4675 <= {{add_ln42_78_fu_2137_p2[36:21]}};
        tmp_752_reg_4680 <= {{add_ln42_76_fu_2089_p2[36:21]}};
        tmp_753_reg_4685 <= {{add_ln42_75_fu_2065_p2[36:21]}};
        tmp_754_reg_4690 <= {{add_ln42_67_fu_1873_p2[36:21]}};
        tmp_755_reg_4695 <= {{add_ln42_66_fu_1849_p2[36:21]}};
        tmp_756_reg_4700 <= {{add_ln42_57_fu_1633_p2[36:21]}};
        tmp_757_reg_4705 <= {{add_ln42_56_fu_1609_p2[36:21]}};
        tmp_758_reg_4710 <= {{add_ln42_48_fu_1417_p2[36:21]}};
        tmp_759_reg_4715 <= {{add_ln42_47_fu_1393_p2[36:21]}};
        tmp_760_reg_4720 <= {{add_ln42_44_fu_1321_p2[36:21]}};
        tmp_761_reg_4725 <= {{add_ln42_43_fu_1297_p2[36:21]}};
        tmp_762_reg_4730 <= {{add_ln42_40_fu_1225_p2[36:21]}};
        tmp_763_reg_4735 <= {{add_ln42_39_fu_1201_p2[36:21]}};
        tmp_764_reg_4740 <= {{add_ln42_38_fu_1177_p2[36:21]}};
        tmp_765_reg_4745 <= {{add_ln42_37_fu_1153_p2[36:21]}};
        tmp_766_reg_4750 <= {{add_ln42_36_fu_1129_p2[36:21]}};
        tmp_767_reg_4755 <= {{add_ln42_33_fu_1057_p2[36:21]}};
        tmp_768_reg_4760 <= {{add_ln42_32_fu_1033_p2[36:21]}};
        tmp_769_reg_4765 <= {{add_ln42_30_fu_985_p2[36:21]}};
        tmp_770_reg_4770 <= {{add_ln42_29_fu_961_p2[36:21]}};
        tmp_771_reg_4775 <= {{add_ln42_21_fu_769_p2[36:21]}};
        tmp_772_reg_4780 <= {{add_ln42_20_fu_745_p2[36:21]}};
        tmp_773_reg_4785 <= {{add_ln42_15_fu_615_p2[36:21]}};
        tmp_reg_4195 <= layer11_out_dout[32'd106];
        tmp_s_reg_4585 <= {{add_ln42_17_fu_673_p2[36:22]}};
        trunc_ln41_3_reg_4190 <= {{layer11_out_dout[96:81]}};
        trunc_ln46_100_reg_4550 <= {{layer11_out_dout[2798:2783]}};
        trunc_ln46_101_reg_4555 <= {{layer11_out_dout[2871:2856]}};
        trunc_ln46_102_reg_4560 <= {{layer11_out_dout[2921:2906]}};
        trunc_ln46_103_reg_4565 <= {{add_ln42_107_fu_2833_p2[36:21]}};
        trunc_ln46_104_reg_4570 <= {{add_ln42_108_fu_2849_p2[36:21]}};
        trunc_ln46_105_reg_4575 <= {{add_ln42_109_fu_2865_p2[36:21]}};
        trunc_ln46_17_reg_4200 <= {{add_ln42_18_fu_697_p2[36:21]}};
        trunc_ln46_18_reg_4205 <= {{add_ln42_19_fu_721_p2[36:21]}};
        trunc_ln46_21_reg_4210 <= {{layer11_out_dout[246:231]}};
        trunc_ln46_22_reg_4215 <= {{add_ln42_22_fu_793_p2[36:21]}};
        trunc_ln46_23_reg_4220 <= {{add_ln42_23_fu_817_p2[36:21]}};
        trunc_ln46_24_reg_4225 <= {{add_ln42_24_fu_841_p2[36:21]}};
        trunc_ln46_25_reg_4230 <= {{add_ln42_25_fu_865_p2[36:21]}};
        trunc_ln46_26_reg_4235 <= {{add_ln42_26_fu_889_p2[36:21]}};
        trunc_ln46_27_reg_4240 <= {{add_ln42_27_fu_913_p2[36:21]}};
        trunc_ln46_28_reg_4245 <= {{add_ln42_28_fu_937_p2[36:21]}};
        trunc_ln46_31_reg_4250 <= {{layer11_out_dout[498:483]}};
        trunc_ln46_32_reg_4255 <= {{add_ln42_31_fu_1009_p2[36:21]}};
        trunc_ln46_35_reg_4260 <= {{layer11_out_dout[596:581]}};
        trunc_ln46_36_reg_4265 <= {{add_ln42_34_fu_1081_p2[36:21]}};
        trunc_ln46_39_reg_4270 <= {{layer11_out_dout[696:681]}};
        trunc_ln46_42_reg_4275 <= {{layer11_out_dout[772:757]}};
        trunc_ln46_45_reg_4280 <= {{layer11_out_dout[846:831]}};
        trunc_ln46_46_reg_4285 <= {{add_ln42_41_fu_1249_p2[36:21]}};
        trunc_ln46_47_reg_4290 <= {{add_ln42_42_fu_1273_p2[36:21]}};
        trunc_ln46_50_reg_4295 <= {{layer11_out_dout[971:956]}};
        trunc_ln46_51_reg_4305 <= {{add_ln42_46_fu_1369_p2[36:21]}};
        trunc_ln46_52_reg_4310 <= {{layer11_out_dout[1096:1081]}};
        trunc_ln46_53_reg_4315 <= {{add_ln42_49_fu_1441_p2[36:21]}};
        trunc_ln46_54_reg_4320 <= {{add_ln42_50_fu_1465_p2[36:21]}};
        trunc_ln46_55_reg_4325 <= {{add_ln42_51_fu_1489_p2[36:21]}};
        trunc_ln46_56_reg_4330 <= {{add_ln42_52_fu_1513_p2[36:21]}};
        trunc_ln46_57_reg_4335 <= {{add_ln42_53_fu_1537_p2[36:21]}};
        trunc_ln46_58_reg_4340 <= {{add_ln42_54_fu_1561_p2[36:21]}};
        trunc_ln46_59_reg_4345 <= {{add_ln42_55_fu_1585_p2[36:21]}};
        trunc_ln46_60_reg_4350 <= {{layer11_out_dout[1346:1331]}};
        trunc_ln46_61_reg_4355 <= {{layer11_out_dout[1371:1356]}};
        trunc_ln46_62_reg_4360 <= {{add_ln42_58_fu_1657_p2[36:21]}};
        trunc_ln46_63_reg_4365 <= {{add_ln42_59_fu_1681_p2[36:21]}};
        trunc_ln46_64_reg_4370 <= {{add_ln42_60_fu_1705_p2[36:21]}};
        trunc_ln46_65_reg_4375 <= {{add_ln42_61_fu_1729_p2[36:21]}};
        trunc_ln46_66_reg_4380 <= {{add_ln42_62_fu_1753_p2[36:21]}};
        trunc_ln46_67_reg_4385 <= {{add_ln42_63_fu_1777_p2[36:21]}};
        trunc_ln46_68_reg_4390 <= {{add_ln42_64_fu_1801_p2[36:21]}};
        trunc_ln46_69_reg_4395 <= {{add_ln42_65_fu_1825_p2[36:21]}};
        trunc_ln46_70_reg_4400 <= {{layer11_out_dout[1646:1631]}};
        trunc_ln46_71_reg_4405 <= {{add_ln42_68_fu_1897_p2[36:21]}};
        trunc_ln46_72_reg_4410 <= {{add_ln42_69_fu_1921_p2[36:21]}};
        trunc_ln46_73_reg_4415 <= {{add_ln42_70_fu_1945_p2[36:21]}};
        trunc_ln46_74_reg_4420 <= {{add_ln42_71_fu_1969_p2[36:21]}};
        trunc_ln46_75_reg_4425 <= {{add_ln42_72_fu_1993_p2[36:21]}};
        trunc_ln46_76_reg_4430 <= {{add_ln42_73_fu_2017_p2[36:21]}};
        trunc_ln46_77_reg_4435 <= {{add_ln42_74_fu_2041_p2[36:21]}};
        trunc_ln46_78_reg_4440 <= {{layer11_out_dout[1898:1883]}};
        trunc_ln46_79_reg_4445 <= {{add_ln42_77_fu_2113_p2[36:21]}};
        trunc_ln46_80_reg_4450 <= {{layer11_out_dout[1997:1982]}};
        trunc_ln46_81_reg_4455 <= {{add_ln42_80_fu_2185_p2[36:21]}};
        trunc_ln46_82_reg_4460 <= {{add_ln42_81_fu_2209_p2[36:21]}};
        trunc_ln46_83_reg_4465 <= {{add_ln42_82_fu_2233_p2[36:21]}};
        trunc_ln46_84_reg_4470 <= {{add_ln42_83_fu_2257_p2[36:21]}};
        trunc_ln46_85_reg_4475 <= {{add_ln42_84_fu_2281_p2[36:21]}};
        trunc_ln46_86_reg_4480 <= {{add_ln42_85_fu_2305_p2[36:21]}};
        trunc_ln46_87_reg_4485 <= {{add_ln42_86_fu_2329_p2[36:21]}};
        trunc_ln46_88_reg_4490 <= {{layer11_out_dout[2246:2231]}};
        trunc_ln46_89_reg_4495 <= {{layer11_out_dout[2322:2307]}};
        trunc_ln46_90_reg_4500 <= {{layer11_out_dout[2373:2358]}};
        trunc_ln46_91_reg_4505 <= {{add_ln42_92_fu_2473_p2[36:21]}};
        trunc_ln46_92_reg_4510 <= {{layer11_out_dout[2471:2456]}};
        trunc_ln46_93_reg_4515 <= {{layer11_out_dout[2546:2531]}};
        trunc_ln46_94_reg_4520 <= {{add_ln42_97_fu_2593_p2[36:21]}};
        trunc_ln46_95_reg_4525 <= {{add_ln42_98_fu_2617_p2[36:21]}};
        trunc_ln46_96_reg_4530 <= {{add_ln42_99_fu_2641_p2[36:21]}};
        trunc_ln46_97_reg_4535 <= {{add_ln42_100_fu_2665_p2[36:21]}};
        trunc_ln46_98_reg_4540 <= {{layer11_out_dout[2721:2706]}};
        trunc_ln46_99_reg_4545 <= {{layer11_out_dout[2772:2757]}};
        trunc_ln46_s_reg_4300 <= {{add_ln42_45_fu_1345_p2[36:21]}};
        trunc_ln_reg_4185 <= {{add_ln42_fu_581_p2[36:21]}};
    end
end

always @ (*) begin
    if (((real_start == 1'b0) | (layer11_out_empty_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((layer22_out_full_n == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((layer22_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((layer22_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer11_out_blk_n = layer11_out_empty_n;
    end else begin
        layer11_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (layer11_out_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        layer11_out_read = 1'b1;
    end else begin
        layer11_out_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        layer22_out_blk_n = layer22_out_full_n;
    end else begin
        layer22_out_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((layer22_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        layer22_out_write = 1'b1;
    end else begin
        layer22_out_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_full_n == 1'b0) & (start_once_reg == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (layer11_out_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((layer22_out_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln42_100_fu_2665_p2 = (y_161_fu_2657_p3 + 37'd67108864);

assign add_ln42_101_fu_2689_p2 = ($signed(y_162_fu_2681_p3) + $signed(37'd137304735744));

assign add_ln42_102_fu_2713_p2 = ($signed(y_163_fu_2705_p3) + $signed(37'd137371844608));

assign add_ln42_103_fu_2737_p2 = (y_164_fu_2729_p3 + 37'd67108864);

assign add_ln42_104_fu_2761_p2 = (y_165_fu_2753_p3 + 37'd201326592);

assign add_ln42_105_fu_2785_p2 = ($signed(y_166_fu_2777_p3) + $signed(37'd137371844608));

assign add_ln42_106_fu_2809_p2 = ($signed(y_167_fu_2801_p3) + $signed(37'd137371844608));

assign add_ln42_107_fu_2833_p2 = (y_168_fu_2825_p3 + 37'd134217728);

assign add_ln42_108_fu_2849_p2 = (trunc_ln5_fu_2839_p4 + 37'd335544320);

assign add_ln42_109_fu_2865_p2 = ($signed(trunc_ln85_1_fu_2855_p4) + $signed(37'd137371844608));

assign add_ln42_15_fu_615_p2 = ($signed(y_76_fu_607_p3) + $signed(37'd137371844608));

assign add_ln42_16_fu_639_p2 = (y_77_fu_631_p3 + 37'd134217728);

assign add_ln42_17_fu_673_p2 = (y_78_fu_665_p3 + 37'd67108864);

assign add_ln42_18_fu_697_p2 = (y_79_fu_689_p3 + 37'd67108864);

assign add_ln42_19_fu_721_p2 = ($signed(y_80_fu_713_p3) + $signed(37'd137371844608));

assign add_ln42_20_fu_745_p2 = ($signed(y_81_fu_737_p3) + $signed(37'd137304735744));

assign add_ln42_21_fu_769_p2 = ($signed(y_82_fu_761_p3) + $signed(37'd137371844608));

assign add_ln42_22_fu_793_p2 = ($signed(y_83_fu_785_p3) + $signed(37'd137237626880));

assign add_ln42_23_fu_817_p2 = (y_84_fu_809_p3 + 37'd67108864);

assign add_ln42_24_fu_841_p2 = ($signed(y_85_fu_833_p3) + $signed(37'd137237626880));

assign add_ln42_25_fu_865_p2 = (y_86_fu_857_p3 + 37'd67108864);

assign add_ln42_26_fu_889_p2 = ($signed(y_87_fu_881_p3) + $signed(37'd137371844608));

assign add_ln42_27_fu_913_p2 = ($signed(y_88_fu_905_p3) + $signed(37'd137170518016));

assign add_ln42_28_fu_937_p2 = (y_89_fu_929_p3 + 37'd67108864);

assign add_ln42_29_fu_961_p2 = (y_90_fu_953_p3 + 37'd201326592);

assign add_ln42_30_fu_985_p2 = ($signed(y_91_fu_977_p3) + $signed(37'd137304735744));

assign add_ln42_31_fu_1009_p2 = ($signed(y_92_fu_1001_p3) + $signed(37'd137371844608));

assign add_ln42_32_fu_1033_p2 = (y_93_fu_1025_p3 + 37'd201326592);

assign add_ln42_33_fu_1057_p2 = ($signed(y_94_fu_1049_p3) + $signed(37'd137237626880));

assign add_ln42_34_fu_1081_p2 = (y_95_fu_1073_p3 + 37'd201326592);

assign add_ln42_35_fu_1105_p2 = ($signed(y_96_fu_1097_p3) + $signed(37'd137304735744));

assign add_ln42_36_fu_1129_p2 = ($signed(y_97_fu_1121_p3) + $signed(37'd137371844608));

assign add_ln42_37_fu_1153_p2 = ($signed(y_98_fu_1145_p3) + $signed(37'd137304735744));

assign add_ln42_38_fu_1177_p2 = ($signed(y_99_fu_1169_p3) + $signed(37'd137304735744));

assign add_ln42_39_fu_1201_p2 = (y_100_fu_1193_p3 + 37'd268435456);

assign add_ln42_40_fu_1225_p2 = ($signed(y_101_fu_1217_p3) + $signed(37'd137304735744));

assign add_ln42_41_fu_1249_p2 = (y_102_fu_1241_p3 + 37'd268435456);

assign add_ln42_42_fu_1273_p2 = ($signed(y_103_fu_1265_p3) + $signed(37'd137371844608));

assign add_ln42_43_fu_1297_p2 = (y_104_fu_1289_p3 + 37'd67108864);

assign add_ln42_44_fu_1321_p2 = ($signed(y_105_fu_1313_p3) + $signed(37'd137304735744));

assign add_ln42_45_fu_1345_p2 = ($signed(y_106_fu_1337_p3) + $signed(37'd137371844608));

assign add_ln42_46_fu_1369_p2 = (y_107_fu_1361_p3 + 37'd67108864);

assign add_ln42_47_fu_1393_p2 = ($signed(y_108_fu_1385_p3) + $signed(37'd137371844608));

assign add_ln42_48_fu_1417_p2 = ($signed(y_109_fu_1409_p3) + $signed(37'd137304735744));

assign add_ln42_49_fu_1441_p2 = ($signed(y_110_fu_1433_p3) + $signed(37'd137371844608));

assign add_ln42_50_fu_1465_p2 = ($signed(y_111_fu_1457_p3) + $signed(37'd137304735744));

assign add_ln42_51_fu_1489_p2 = (y_112_fu_1481_p3 + 37'd134217728);

assign add_ln42_52_fu_1513_p2 = ($signed(y_113_fu_1505_p3) + $signed(37'd137237626880));

assign add_ln42_53_fu_1537_p2 = (y_114_fu_1529_p3 + 37'd67108864);

assign add_ln42_54_fu_1561_p2 = (y_115_fu_1553_p3 + 37'd201326592);

assign add_ln42_55_fu_1585_p2 = ($signed(y_116_fu_1577_p3) + $signed(37'd137371844608));

assign add_ln42_56_fu_1609_p2 = ($signed(y_117_fu_1601_p3) + $signed(37'd137304735744));

assign add_ln42_57_fu_1633_p2 = (y_118_fu_1625_p3 + 37'd201326592);

assign add_ln42_58_fu_1657_p2 = (y_119_fu_1649_p3 + 37'd268435456);

assign add_ln42_59_fu_1681_p2 = (y_120_fu_1673_p3 + 37'd134217728);

assign add_ln42_60_fu_1705_p2 = ($signed(y_121_fu_1697_p3) + $signed(37'd137371844608));

assign add_ln42_61_fu_1729_p2 = (y_122_fu_1721_p3 + 37'd201326592);

assign add_ln42_62_fu_1753_p2 = (y_123_fu_1745_p3 + 37'd268435456);

assign add_ln42_63_fu_1777_p2 = (y_124_fu_1769_p3 + 37'd67108864);

assign add_ln42_64_fu_1801_p2 = ($signed(y_125_fu_1793_p3) + $signed(37'd137237626880));

assign add_ln42_65_fu_1825_p2 = ($signed(y_126_fu_1817_p3) + $signed(37'd137304735744));

assign add_ln42_66_fu_1849_p2 = (y_127_fu_1841_p3 + 37'd67108864);

assign add_ln42_67_fu_1873_p2 = (y_128_fu_1865_p3 + 37'd67108864);

assign add_ln42_68_fu_1897_p2 = (y_129_fu_1889_p3 + 37'd201326592);

assign add_ln42_69_fu_1921_p2 = (y_130_fu_1913_p3 + 37'd67108864);

assign add_ln42_70_fu_1945_p2 = (y_131_fu_1937_p3 + 37'd268435456);

assign add_ln42_71_fu_1969_p2 = ($signed(y_132_fu_1961_p3) + $signed(37'd137371844608));

assign add_ln42_72_fu_1993_p2 = (y_133_fu_1985_p3 + 37'd67108864);

assign add_ln42_73_fu_2017_p2 = (y_134_fu_2009_p3 + 37'd268435456);

assign add_ln42_74_fu_2041_p2 = (y_135_fu_2033_p3 + 37'd201326592);

assign add_ln42_75_fu_2065_p2 = ($signed(y_136_fu_2057_p3) + $signed(37'd137371844608));

assign add_ln42_76_fu_2089_p2 = ($signed(y_137_fu_2081_p3) + $signed(37'd137371844608));

assign add_ln42_77_fu_2113_p2 = (y_138_fu_2105_p3 + 37'd201326592);

assign add_ln42_78_fu_2137_p2 = (y_139_fu_2129_p3 + 37'd67108864);

assign add_ln42_79_fu_2161_p2 = ($signed(y_140_fu_2153_p3) + $signed(37'd137371844608));

assign add_ln42_80_fu_2185_p2 = ($signed(y_141_fu_2177_p3) + $signed(37'd137371844608));

assign add_ln42_81_fu_2209_p2 = (y_142_fu_2201_p3 + 37'd201326592);

assign add_ln42_82_fu_2233_p2 = ($signed(y_143_fu_2225_p3) + $signed(37'd137237626880));

assign add_ln42_83_fu_2257_p2 = ($signed(y_144_fu_2249_p3) + $signed(37'd137371844608));

assign add_ln42_84_fu_2281_p2 = ($signed(y_145_fu_2273_p3) + $signed(37'd137371844608));

assign add_ln42_85_fu_2305_p2 = ($signed(y_146_fu_2297_p3) + $signed(37'd137170518016));

assign add_ln42_86_fu_2329_p2 = (y_147_fu_2321_p3 + 37'd134217728);

assign add_ln42_87_fu_2353_p2 = ($signed(y_148_fu_2345_p3) + $signed(37'd137371844608));

assign add_ln42_88_fu_2377_p2 = (y_149_fu_2369_p3 + 37'd201326592);

assign add_ln42_89_fu_2401_p2 = ($signed(y_150_fu_2393_p3) + $signed(37'd137304735744));

assign add_ln42_90_fu_2425_p2 = (y_151_fu_2417_p3 + 37'd134217728);

assign add_ln42_91_fu_2449_p2 = (y_152_fu_2441_p3 + 37'd268435456);

assign add_ln42_92_fu_2473_p2 = ($signed(y_153_fu_2465_p3) + $signed(37'd137371844608));

assign add_ln42_93_fu_2497_p2 = ($signed(y_154_fu_2489_p3) + $signed(37'd137371844608));

assign add_ln42_94_fu_2521_p2 = ($signed(y_155_fu_2513_p3) + $signed(37'd137371844608));

assign add_ln42_95_fu_2545_p2 = (y_156_fu_2537_p3 + 37'd201326592);

assign add_ln42_96_fu_2569_p2 = ($signed(y_157_fu_2561_p3) + $signed(37'd137237626880));

assign add_ln42_97_fu_2593_p2 = (y_158_fu_2585_p3 + 37'd134217728);

assign add_ln42_98_fu_2617_p2 = ($signed(y_159_fu_2609_p3) + $signed(37'd137371844608));

assign add_ln42_99_fu_2641_p2 = ($signed(y_160_fu_2633_p3) + $signed(37'd137371844608));

assign add_ln42_fu_581_p2 = (y_fu_573_p3 + 37'd268435456);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (layer11_out_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign layer22_out_din = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{trunc_ln46_105_reg_4575}, {trunc_ln46_104_reg_4570}}, {trunc_ln46_103_reg_4565}}, {trunc_ln46_102_reg_4560}}, {tmp_735_reg_4595}}, {trunc_ln46_101_reg_4555}}, {tmp_736_reg_4600}}, {tmp_737_reg_4605}}, {trunc_ln46_100_reg_4550}}, {trunc_ln46_99_reg_4545}}, {tmp_738_reg_4610}}, {trunc_ln46_98_reg_4540}}, {tmp_739_reg_4615}}, {tmp_740_reg_4620}}, {trunc_ln46_97_reg_4535}}, {trunc_ln46_96_reg_4530}}, {trunc_ln46_95_reg_4525}}, {trunc_ln46_94_reg_4520}}, {trunc_ln46_93_reg_4515}}, {tmp_741_reg_4625}}, {tmp_742_reg_4630}}, {trunc_ln46_92_reg_4510}}, {tmp_743_reg_4635}}, {tmp_744_reg_4640}}, {trunc_ln46_91_reg_4505}}, {trunc_ln46_90_reg_4500}}, {tmp_745_reg_4645}}, {trunc_ln46_89_reg_4495}}, {tmp_746_reg_4650}}, {tmp_747_reg_4655}}, {trunc_ln46_88_reg_4490}}, {tmp_748_reg_4660}}, {tmp_749_reg_4665}}, {trunc_ln46_87_reg_4485}}, {trunc_ln46_86_reg_4480}}, {trunc_ln46_85_reg_4475}}, {trunc_ln46_84_reg_4470}}, 
    {trunc_ln46_83_reg_4465}}, {trunc_ln46_82_reg_4460}}, {trunc_ln46_81_reg_4455}}, {trunc_ln46_80_reg_4450}}, {tmp_750_reg_4670}}, {tmp_751_reg_4675}}, {trunc_ln46_79_reg_4445}}, {trunc_ln46_78_reg_4440}}, {tmp_752_reg_4680}}, {tmp_753_reg_4685}}, {trunc_ln46_77_reg_4435}}, {trunc_ln46_76_reg_4430}}, {trunc_ln46_75_reg_4425}}, {trunc_ln46_74_reg_4420}}, {trunc_ln46_73_reg_4415}}, {trunc_ln46_72_reg_4410}}, {trunc_ln46_71_reg_4405}}, {trunc_ln46_70_reg_4400}}, {tmp_754_reg_4690}}, {tmp_755_reg_4695}}, {trunc_ln46_69_reg_4395}}, {trunc_ln46_68_reg_4390}}, {trunc_ln46_67_reg_4385}}, {trunc_ln46_66_reg_4380}}, {trunc_ln46_65_reg_4375}}, {trunc_ln46_64_reg_4370}}, {trunc_ln46_63_reg_4365}}, {trunc_ln46_62_reg_4360}}, {trunc_ln46_61_reg_4355}}, {trunc_ln46_60_reg_4350}}, {tmp_756_reg_4700}}, {tmp_757_reg_4705}}, {trunc_ln46_59_reg_4345}}, {trunc_ln46_58_reg_4340}}, {trunc_ln46_57_reg_4335}}, {trunc_ln46_56_reg_4330}}, {trunc_ln46_55_reg_4325}}, {trunc_ln46_54_reg_4320}}, {trunc_ln46_53_reg_4315}}, {trunc_ln46_52_reg_4310}}, 
    {tmp_758_reg_4710}}, {tmp_759_reg_4715}}, {trunc_ln46_51_reg_4305}}, {trunc_ln46_s_reg_4300}}, {trunc_ln46_50_reg_4295}}, {tmp_760_reg_4720}}, {tmp_761_reg_4725}}, {trunc_ln46_47_reg_4290}}, {trunc_ln46_46_reg_4285}}, {trunc_ln46_45_reg_4280}}, {tmp_762_reg_4730}}, {tmp_763_reg_4735}}, {trunc_ln46_42_reg_4275}}, {tmp_764_reg_4740}}, {tmp_765_reg_4745}}, {trunc_ln46_39_reg_4270}}, {tmp_766_reg_4750}}, {tmp_734_reg_4590}}, {trunc_ln46_36_reg_4265}}, {trunc_ln46_35_reg_4260}}, {tmp_767_reg_4755}}, {tmp_768_reg_4760}}, {trunc_ln46_32_reg_4255}}, {trunc_ln46_31_reg_4250}}, {tmp_769_reg_4765}}, {tmp_770_reg_4770}}, {trunc_ln46_28_reg_4245}}, {trunc_ln46_27_reg_4240}}, {trunc_ln46_26_reg_4235}}, {trunc_ln46_25_reg_4230}}, {trunc_ln46_24_reg_4225}}, {trunc_ln46_23_reg_4220}}, {trunc_ln46_22_reg_4215}}, {trunc_ln46_21_reg_4210}}, {tmp_771_reg_4775}}, {tmp_772_reg_4780}}, {trunc_ln46_18_reg_4205}}, {trunc_ln46_17_reg_4200}}, {tmp_s_reg_4585}}, {tmp_reg_4195}}, {trunc_ln41_3_reg_4190}}, {tmp_733_reg_4580}}, {tmp_773_reg_4785}}, 
    {trunc_ln_reg_4185}};

assign start_out = real_start;

assign tmp_640_fu_597_p4 = {{layer11_out_dout[47:25]}};

assign tmp_641_fu_621_p4 = {{layer11_out_dout[72:50]}};

assign tmp_642_fu_655_p4 = {{layer11_out_dout[121:100]}};

assign tmp_643_fu_679_p4 = {{layer11_out_dout[146:125]}};

assign tmp_644_fu_703_p4 = {{layer11_out_dout[173:150]}};

assign tmp_645_fu_727_p4 = {{layer11_out_dout[196:175]}};

assign tmp_646_fu_751_p4 = {{layer11_out_dout[221:200]}};

assign tmp_647_fu_775_p4 = {{layer11_out_dout[271:250]}};

assign tmp_648_fu_799_p4 = {{layer11_out_dout[297:275]}};

assign tmp_649_fu_823_p4 = {{layer11_out_dout[321:300]}};

assign tmp_650_fu_847_p4 = {{layer11_out_dout[346:325]}};

assign tmp_651_fu_871_p4 = {{layer11_out_dout[372:350]}};

assign tmp_652_fu_895_p4 = {{layer11_out_dout[396:375]}};

assign tmp_653_fu_919_p4 = {{layer11_out_dout[421:400]}};

assign tmp_654_fu_943_p4 = {{layer11_out_dout[446:425]}};

assign tmp_655_fu_967_p4 = {{layer11_out_dout[471:450]}};

assign tmp_656_fu_991_p4 = {{layer11_out_dout[521:500]}};

assign tmp_657_fu_1015_p4 = {{layer11_out_dout[546:525]}};

assign tmp_658_fu_1039_p4 = {{layer11_out_dout[571:550]}};

assign tmp_659_fu_1063_p4 = {{layer11_out_dout[621:600]}};

assign tmp_660_fu_1087_p4 = {{layer11_out_dout[646:625]}};

assign tmp_661_fu_1111_p4 = {{layer11_out_dout[671:650]}};

assign tmp_662_fu_1135_p4 = {{layer11_out_dout[721:700]}};

assign tmp_663_fu_1159_p4 = {{layer11_out_dout[746:725]}};

assign tmp_664_fu_1183_p4 = {{layer11_out_dout[797:775]}};

assign tmp_665_fu_1207_p4 = {{layer11_out_dout[821:800]}};

assign tmp_666_fu_1231_p4 = {{layer11_out_dout[871:850]}};

assign tmp_667_fu_1255_p4 = {{layer11_out_dout[896:875]}};

assign tmp_668_fu_1279_p4 = {{layer11_out_dout[921:900]}};

assign tmp_669_fu_1303_p4 = {{layer11_out_dout[947:925]}};

assign tmp_670_fu_1327_p4 = {{layer11_out_dout[996:975]}};

assign tmp_671_fu_1351_p4 = {{layer11_out_dout[1021:1000]}};

assign tmp_672_fu_1375_p4 = {{layer11_out_dout[1046:1025]}};

assign tmp_673_fu_1399_p4 = {{layer11_out_dout[1071:1050]}};

assign tmp_674_fu_1423_p4 = {{layer11_out_dout[1121:1100]}};

assign tmp_675_fu_1447_p4 = {{layer11_out_dout[1146:1125]}};

assign tmp_676_fu_1471_p4 = {{layer11_out_dout[1172:1150]}};

assign tmp_677_fu_1495_p4 = {{layer11_out_dout[1196:1175]}};

assign tmp_678_fu_1519_p4 = {{layer11_out_dout[1221:1200]}};

assign tmp_679_fu_1543_p4 = {{layer11_out_dout[1246:1225]}};

assign tmp_680_fu_1567_p4 = {{layer11_out_dout[1271:1250]}};

assign tmp_681_fu_1591_p4 = {{layer11_out_dout[1297:1275]}};

assign tmp_682_fu_1615_p4 = {{layer11_out_dout[1322:1300]}};

assign tmp_683_fu_1639_p4 = {{layer11_out_dout[1396:1375]}};

assign tmp_684_fu_1663_p4 = {{layer11_out_dout[1422:1400]}};

assign tmp_685_fu_1687_p4 = {{layer11_out_dout[1446:1425]}};

assign tmp_686_fu_1711_p4 = {{layer11_out_dout[1471:1450]}};

assign tmp_687_fu_1735_p4 = {{layer11_out_dout[1496:1475]}};

assign tmp_688_fu_1759_p4 = {{layer11_out_dout[1521:1500]}};

assign tmp_689_fu_1783_p4 = {{layer11_out_dout[1546:1525]}};

assign tmp_690_fu_1807_p4 = {{layer11_out_dout[1571:1550]}};

assign tmp_691_fu_1831_p4 = {{layer11_out_dout[1596:1575]}};

assign tmp_692_fu_1855_p4 = {{layer11_out_dout[1622:1600]}};

assign tmp_693_fu_1879_p4 = {{layer11_out_dout[1672:1650]}};

assign tmp_694_fu_1903_p4 = {{layer11_out_dout[1696:1675]}};

assign tmp_695_fu_1927_p4 = {{layer11_out_dout[1721:1700]}};

assign tmp_696_fu_1951_p4 = {{layer11_out_dout[1748:1725]}};

assign tmp_697_fu_1975_p4 = {{layer11_out_dout[1772:1750]}};

assign tmp_698_fu_1999_p4 = {{layer11_out_dout[1797:1775]}};

assign tmp_699_fu_2023_p4 = {{layer11_out_dout[1821:1800]}};

assign tmp_700_fu_2047_p4 = {{layer11_out_dout[1847:1825]}};

assign tmp_701_fu_2071_p4 = {{layer11_out_dout[1871:1850]}};

assign tmp_702_fu_2095_p4 = {{layer11_out_dout[1921:1900]}};

assign tmp_703_fu_2119_p4 = {{layer11_out_dout[1946:1925]}};

assign tmp_704_fu_2143_p4 = {{layer11_out_dout[1973:1950]}};

assign tmp_705_fu_2167_p4 = {{layer11_out_dout[2021:2000]}};

assign tmp_706_fu_2191_p4 = {{layer11_out_dout[2046:2025]}};

assign tmp_707_fu_2215_p4 = {{layer11_out_dout[2071:2050]}};

assign tmp_708_fu_2239_p4 = {{layer11_out_dout[2098:2075]}};

assign tmp_709_fu_2263_p4 = {{layer11_out_dout[2123:2100]}};

assign tmp_710_fu_2287_p4 = {{layer11_out_dout[2146:2125]}};

assign tmp_711_fu_2311_p4 = {{layer11_out_dout[2172:2150]}};

assign tmp_712_fu_2335_p4 = {{layer11_out_dout[2197:2175]}};

assign tmp_713_fu_2359_p4 = {{layer11_out_dout[2221:2200]}};

assign tmp_714_fu_2383_p4 = {{layer11_out_dout[2271:2250]}};

assign tmp_715_fu_2407_p4 = {{layer11_out_dout[2296:2275]}};

assign tmp_716_fu_2431_p4 = {{layer11_out_dout[2346:2325]}};

assign tmp_717_fu_2455_p4 = {{layer11_out_dout[2396:2375]}};

assign tmp_718_fu_2479_p4 = {{layer11_out_dout[2422:2400]}};

assign tmp_719_fu_2503_p4 = {{layer11_out_dout[2446:2425]}};

assign tmp_720_fu_2527_p4 = {{layer11_out_dout[2496:2475]}};

assign tmp_721_fu_2551_p4 = {{layer11_out_dout[2521:2500]}};

assign tmp_722_fu_2575_p4 = {{layer11_out_dout[2572:2550]}};

assign tmp_723_fu_2599_p4 = {{layer11_out_dout[2596:2575]}};

assign tmp_724_fu_2623_p4 = {{layer11_out_dout[2622:2600]}};

assign tmp_725_fu_2647_p4 = {{layer11_out_dout[2646:2625]}};

assign tmp_726_fu_2671_p4 = {{layer11_out_dout[2671:2650]}};

assign tmp_727_fu_2695_p4 = {{layer11_out_dout[2698:2675]}};

assign tmp_728_fu_2719_p4 = {{layer11_out_dout[2746:2725]}};

assign tmp_729_fu_2743_p4 = {{layer11_out_dout[2821:2800]}};

assign tmp_730_fu_2767_p4 = {{layer11_out_dout[2847:2825]}};

assign tmp_731_fu_2791_p4 = {{layer11_out_dout[2896:2875]}};

assign tmp_732_fu_2815_p4 = {{layer11_out_dout[2946:2925]}};

assign trunc_ln5_fu_2839_p4 = {{layer11_out_dout[2971:2935]}};

assign trunc_ln85_1_fu_2855_p4 = {{layer11_out_dout[2997:2961]}};

assign trunc_ln85_fu_569_p1 = layer11_out_dout[21:0];

assign y_100_fu_1193_p3 = {{tmp_664_fu_1183_p4}, {14'd0}};

assign y_101_fu_1217_p3 = {{tmp_665_fu_1207_p4}, {15'd0}};

assign y_102_fu_1241_p3 = {{tmp_666_fu_1231_p4}, {15'd0}};

assign y_103_fu_1265_p3 = {{tmp_667_fu_1255_p4}, {15'd0}};

assign y_104_fu_1289_p3 = {{tmp_668_fu_1279_p4}, {15'd0}};

assign y_105_fu_1313_p3 = {{tmp_669_fu_1303_p4}, {14'd0}};

assign y_106_fu_1337_p3 = {{tmp_670_fu_1327_p4}, {15'd0}};

assign y_107_fu_1361_p3 = {{tmp_671_fu_1351_p4}, {15'd0}};

assign y_108_fu_1385_p3 = {{tmp_672_fu_1375_p4}, {15'd0}};

assign y_109_fu_1409_p3 = {{tmp_673_fu_1399_p4}, {15'd0}};

assign y_110_fu_1433_p3 = {{tmp_674_fu_1423_p4}, {15'd0}};

assign y_111_fu_1457_p3 = {{tmp_675_fu_1447_p4}, {15'd0}};

assign y_112_fu_1481_p3 = {{tmp_676_fu_1471_p4}, {14'd0}};

assign y_113_fu_1505_p3 = {{tmp_677_fu_1495_p4}, {15'd0}};

assign y_114_fu_1529_p3 = {{tmp_678_fu_1519_p4}, {15'd0}};

assign y_115_fu_1553_p3 = {{tmp_679_fu_1543_p4}, {15'd0}};

assign y_116_fu_1577_p3 = {{tmp_680_fu_1567_p4}, {15'd0}};

assign y_117_fu_1601_p3 = {{tmp_681_fu_1591_p4}, {14'd0}};

assign y_118_fu_1625_p3 = {{tmp_682_fu_1615_p4}, {14'd0}};

assign y_119_fu_1649_p3 = {{tmp_683_fu_1639_p4}, {15'd0}};

assign y_120_fu_1673_p3 = {{tmp_684_fu_1663_p4}, {14'd0}};

assign y_121_fu_1697_p3 = {{tmp_685_fu_1687_p4}, {15'd0}};

assign y_122_fu_1721_p3 = {{tmp_686_fu_1711_p4}, {15'd0}};

assign y_123_fu_1745_p3 = {{tmp_687_fu_1735_p4}, {15'd0}};

assign y_124_fu_1769_p3 = {{tmp_688_fu_1759_p4}, {15'd0}};

assign y_125_fu_1793_p3 = {{tmp_689_fu_1783_p4}, {15'd0}};

assign y_126_fu_1817_p3 = {{tmp_690_fu_1807_p4}, {15'd0}};

assign y_127_fu_1841_p3 = {{tmp_691_fu_1831_p4}, {15'd0}};

assign y_128_fu_1865_p3 = {{tmp_692_fu_1855_p4}, {14'd0}};

assign y_129_fu_1889_p3 = {{tmp_693_fu_1879_p4}, {14'd0}};

assign y_130_fu_1913_p3 = {{tmp_694_fu_1903_p4}, {15'd0}};

assign y_131_fu_1937_p3 = {{tmp_695_fu_1927_p4}, {15'd0}};

assign y_132_fu_1961_p3 = {{tmp_696_fu_1951_p4}, {13'd0}};

assign y_133_fu_1985_p3 = {{tmp_697_fu_1975_p4}, {14'd0}};

assign y_134_fu_2009_p3 = {{tmp_698_fu_1999_p4}, {14'd0}};

assign y_135_fu_2033_p3 = {{tmp_699_fu_2023_p4}, {15'd0}};

assign y_136_fu_2057_p3 = {{tmp_700_fu_2047_p4}, {14'd0}};

assign y_137_fu_2081_p3 = {{tmp_701_fu_2071_p4}, {15'd0}};

assign y_138_fu_2105_p3 = {{tmp_702_fu_2095_p4}, {15'd0}};

assign y_139_fu_2129_p3 = {{tmp_703_fu_2119_p4}, {15'd0}};

assign y_140_fu_2153_p3 = {{tmp_704_fu_2143_p4}, {13'd0}};

assign y_141_fu_2177_p3 = {{tmp_705_fu_2167_p4}, {15'd0}};

assign y_142_fu_2201_p3 = {{tmp_706_fu_2191_p4}, {15'd0}};

assign y_143_fu_2225_p3 = {{tmp_707_fu_2215_p4}, {15'd0}};

assign y_144_fu_2249_p3 = {{tmp_708_fu_2239_p4}, {13'd0}};

assign y_145_fu_2273_p3 = {{tmp_709_fu_2263_p4}, {13'd0}};

assign y_146_fu_2297_p3 = {{tmp_710_fu_2287_p4}, {15'd0}};

assign y_147_fu_2321_p3 = {{tmp_711_fu_2311_p4}, {14'd0}};

assign y_148_fu_2345_p3 = {{tmp_712_fu_2335_p4}, {14'd0}};

assign y_149_fu_2369_p3 = {{tmp_713_fu_2359_p4}, {15'd0}};

assign y_150_fu_2393_p3 = {{tmp_714_fu_2383_p4}, {15'd0}};

assign y_151_fu_2417_p3 = {{tmp_715_fu_2407_p4}, {15'd0}};

assign y_152_fu_2441_p3 = {{tmp_716_fu_2431_p4}, {15'd0}};

assign y_153_fu_2465_p3 = {{tmp_717_fu_2455_p4}, {15'd0}};

assign y_154_fu_2489_p3 = {{tmp_718_fu_2479_p4}, {14'd0}};

assign y_155_fu_2513_p3 = {{tmp_719_fu_2503_p4}, {15'd0}};

assign y_156_fu_2537_p3 = {{tmp_720_fu_2527_p4}, {15'd0}};

assign y_157_fu_2561_p3 = {{tmp_721_fu_2551_p4}, {15'd0}};

assign y_158_fu_2585_p3 = {{tmp_722_fu_2575_p4}, {14'd0}};

assign y_159_fu_2609_p3 = {{tmp_723_fu_2599_p4}, {15'd0}};

assign y_160_fu_2633_p3 = {{tmp_724_fu_2623_p4}, {14'd0}};

assign y_161_fu_2657_p3 = {{tmp_725_fu_2647_p4}, {15'd0}};

assign y_162_fu_2681_p3 = {{tmp_726_fu_2671_p4}, {15'd0}};

assign y_163_fu_2705_p3 = {{tmp_727_fu_2695_p4}, {13'd0}};

assign y_164_fu_2729_p3 = {{tmp_728_fu_2719_p4}, {15'd0}};

assign y_165_fu_2753_p3 = {{tmp_729_fu_2743_p4}, {15'd0}};

assign y_166_fu_2777_p3 = {{tmp_730_fu_2767_p4}, {14'd0}};

assign y_167_fu_2801_p3 = {{tmp_731_fu_2791_p4}, {15'd0}};

assign y_168_fu_2825_p3 = {{tmp_732_fu_2815_p4}, {15'd0}};

assign y_76_fu_607_p3 = {{tmp_640_fu_597_p4}, {14'd0}};

assign y_77_fu_631_p3 = {{tmp_641_fu_621_p4}, {14'd0}};

assign y_78_fu_665_p3 = {{tmp_642_fu_655_p4}, {15'd0}};

assign y_79_fu_689_p3 = {{tmp_643_fu_679_p4}, {15'd0}};

assign y_80_fu_713_p3 = {{tmp_644_fu_703_p4}, {13'd0}};

assign y_81_fu_737_p3 = {{tmp_645_fu_727_p4}, {15'd0}};

assign y_82_fu_761_p3 = {{tmp_646_fu_751_p4}, {15'd0}};

assign y_83_fu_785_p3 = {{tmp_647_fu_775_p4}, {15'd0}};

assign y_84_fu_809_p3 = {{tmp_648_fu_799_p4}, {14'd0}};

assign y_85_fu_833_p3 = {{tmp_649_fu_823_p4}, {15'd0}};

assign y_86_fu_857_p3 = {{tmp_650_fu_847_p4}, {15'd0}};

assign y_87_fu_881_p3 = {{tmp_651_fu_871_p4}, {14'd0}};

assign y_88_fu_905_p3 = {{tmp_652_fu_895_p4}, {15'd0}};

assign y_89_fu_929_p3 = {{tmp_653_fu_919_p4}, {15'd0}};

assign y_90_fu_953_p3 = {{tmp_654_fu_943_p4}, {15'd0}};

assign y_91_fu_977_p3 = {{tmp_655_fu_967_p4}, {15'd0}};

assign y_92_fu_1001_p3 = {{tmp_656_fu_991_p4}, {15'd0}};

assign y_93_fu_1025_p3 = {{tmp_657_fu_1015_p4}, {15'd0}};

assign y_94_fu_1049_p3 = {{tmp_658_fu_1039_p4}, {15'd0}};

assign y_95_fu_1073_p3 = {{tmp_659_fu_1063_p4}, {15'd0}};

assign y_96_fu_1097_p3 = {{tmp_660_fu_1087_p4}, {15'd0}};

assign y_97_fu_1121_p3 = {{tmp_661_fu_1111_p4}, {15'd0}};

assign y_98_fu_1145_p3 = {{tmp_662_fu_1135_p4}, {15'd0}};

assign y_99_fu_1169_p3 = {{tmp_663_fu_1159_p4}, {15'd0}};

assign y_fu_573_p3 = {{trunc_ln85_fu_569_p1}, {15'd0}};

endmodule //myproject_normalize_array_array_ap_fixed_16_6_5_3_0_120u_config22_s
